### ISSUE TITLE
Hermes context specific help option

### ISSUE THREAD

**Issue by leejw51crypto** [informalsystems/ibc-rs#1003]
## Summary
add context specific help
```
 hermes  start --help
```
currently it shows
```
error: unrecognized option `--help`
```

instead , we can display help for "start" command

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
The Hermes `help` menu is currently implemented as a global option. This means that the `help` argument must come _before_ any specific command. So to obtain the help for command `start`, we would write `hermes help start`.

```
$ hermes help start
hermes 0.3.2
Informal Systems <hello@informal.systems>
Hermes is an IBC Relayer written in Rust.

USAGE:
    hermes start <OPTIONS>

DESCRIPTION:
    Start the relayer in multi-chain mode. Handles packet relaying across all open channels between all chains in the config.
```

The same goes for any other command, including sub-commands, e.g., `hermes help create` or `hermes help create client`.
Would this solve your issue?

Related open: https://github.com/informalsystems/ibc-rs/issues/134

**Comment by leejw51crypto** [comment]
global option works, but when user enters command like this
```
hermes create client
error: missing required free argument

hermes 0.3.2
Informal Systems <hello@informal.systems>
Hermes is an IBC Relayer written in Rust.

FLAGS:
    -c, --config CONFIG       path to configuration file
    -h, --help                print help message
    -j, --json                enable JSON output
```

**Comment by romac** [comment]
Yes, that's an unfortunate limitation of the `gumdrop` crate that we depend on via `abscissa`, the CLI framework  used to build Hermes. When [Abscissa eventually moves to Clap](https://github.com/iqlusioninc/abscissa/pull/479), we'll get a much better command-line UX.

**Comment by leejw51crypto** [comment]
yes, that would work

**Comment by adizere** [comment]
> Yes, that's an unfortunate limitation of the `gumdrop` crate that we depend on via `abscissa`, the CLI framework used to build Hermes. When [Abscissa eventually moves to Clap](https://github.com/iqlusioninc/abscissa/pull/479), we'll get a much better command-line UX.

I did a quick experiment (#1012) with an alternative fix of modifying the help message, so that Hermes explicitly mentions the `help` command (instead of mentioning the `-h` flag, which does not work).

@leejw51crypto @romac could you please have a look over #1012 ?
