### ISSUE TITLE
interactive .hermes/config.toml generation

### ISSUE THREAD

**Issue by leejw51crypto** [informalsystems/ibc-rs#1004]
## Summary
current, writing `.hermes/config.toml` is very hard for user to write from scratch.
instead  , how about
```
hermes --interactive
```
so that user just enter specific information (ip, mnemonics ..) then automatically generate ~/.hermes/config.toml

## Acceptance Criteria

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Closing in favor of https://github.com/informalsystems/ibc-rs/issues/1095
