### ISSUE TITLE
Interchain Accounts - hermes dev environment

### ISSUE THREAD

**Issue by seantking** [informalsystems/ibc-rs#1005]
## Crate
`ibc-relayer`

## Summary of Bug
Hi everyone :wave: 

I have started setting up a local development environment that uses the Hermes relayer. I am enjoying using it so far :+1:. Great work!

I'm working on the interchain accounts module. You can see PR with the new hermes development environment here -> https://github.com/cosmos/interchain-accounts/pull/38

The current demo with interchain accounts works nicely with the golang relayer. You can see the readme for the demo here -> https://github.com/cosmos/interchain-accounts/blob/master/readme.md

The hermes relayer works fine for most of the demo but it seems to not like how I am building the packet here -> https://github.com/cosmos/interchain-accounts/blob/master/x/ibc-account/keeper/relay.go#L78

The only indication that something is wrong is in the following log:
```
May 26 16:28:16.152  WARN ibc_relayer::event::rpc: error while building event send_packet.packet_data
```

## Version

hermes 0.3.0

## Steps to Reproduce
Check out this branch: https://github.com/cosmos/interchain-accounts/pull/38

`make init` - This will start two chains with the interchain accounts module enabled. It will then start the hermes relayer and create a client, connection and one ics27 channel and one ics20 channel. 

You can then step through the demo -> https://github.com/cosmos/interchain-accounts/blob/feat/adding-hermes-relayer-dev-env/readme.md

At the final `intertx send` step you should see the following log. 

```
May 26 16:28:16.152  WARN ibc_relayer::event::rpc: error while building event send_packet.packet_data
```

The IBC packet is either not sent at all or there is an error on the receiving side. As it works with the golang relayer the only thing I can think of is how the packet is being structured before sending. 

To test with the golang relayer:

```
make init-golang-relayer
```

And then step through the demo. The final balance should be `500stake` when successful. 

## Acceptance Criteria

Determine why the hermes relayer has an error while building event `send_packet.packet_data`
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
relevant [discussion](https://github.com/informalsystems/ibc-rs/pull/839#pullrequestreview-647281562)

also I think it is because the event type in [bank is "send"](https://github.com/informalsystems/ibc-rs/blob/7c0418e3f6adf270a2a91f19b39a0141234c7545/relayer/src/event/rpc.rs#L104)

I am a little confused why ibc-rs isn't building the [send packet](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet.go#L124) event. Does ibc-go need to add support for something?

**Comment by seantking** [comment]
Ah, thank you, I didn't see the conversation. 

Regardless, there is something going wrong for sure as the last step doesn't complete on the receiving side for the interchain account. The final balance should be `500stake` not `1000stake`.

**Comment by ancazamfir** [comment]
I followed the steps and I don't see an issue. The balance is updated after the last command:
```icad tx intertx send cosmos-sdk $VAL_2 500stake --source-port ibcaccount --source-channel channel-0 --chain-id test-1 --gas 90000 --home ./data/test-1 --node tcp://localhost:16657 --from val1```

I don't understand ica well but from what I can tell there are two IBC transfers that happen in the instructions and they are triggered by the `icad tx intertx...` commands. 

In order to see if there are any un-relayed packets you can execute (use the right config.toml):
```
hermes -c config-ica.toml query packet unreceived-packets test-1 ibcaccount channel-0
hermes -c config-ica.toml query packet unreceived-packets test-2 ibcaccount channel-0
hermes -c config-ica.toml query packet unreceived-acks test-2 ibcaccount channel-0
hermes -c config-ica.toml query packet unreceived-acks test-1 ibcaccount channel-0
```
Here is an output snipet:
```
ancas-mbp:interchain-accounts ancaz$ icad q bank balances $IBC_ACCOUNT --chain-id test-2
balances:
- amount: "1000"
  denom: stake
pagination:
  next_key: null
  total: "0"
ancas-mbp:interchain-accounts ancaz$ icad tx intertx send cosmos-sdk $VAL_2 500stake --source-port ibcaccount --source-channel channel-0 --chain-id test-1 --gas 90000 --home ./data/test-1 --node tcp://localhost:16657 --from val1
{"body":{"messages":[{"@type":"/intertx.MsgSend","chain_type":"cosmos-sdk","source_port":"ibcaccount","source_channel":"channel-0","sender":"cosmos1mjk79fjjgpplak5wq838w0yd982gzkyfrk07am","to_address":"cosmos17dtl0mjt3t77kpuhg2edqzjpszulwhgzuj9ljs","amount":[{"denom":"stake","amount":"500"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"90000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"324","txhash":"CAB8E0385C7AFE8D086574D46500603269A422AD6598F4D60AA3788FB100ED4B","codespace":"","code":0,"data":"0A060A0473656E64","raw_log":"[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"send\"},{\"key\":\"module\",\"value\":\"ibc_channel\"}]},{\"type\":\"send_packet\",\"attributes\":[{\"key\":\"packet_data\",\"value\":\"{\\\"data\\\":\\\"Co8BCowBChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEmwKLWNvc21vczFwdDZhcjhsYXdtdnZxNWhheGMzbDN6aGpmbDA0dTU2ZnMybmRoORItY29zbW9zMTdkdGwwbWp0M3Q3N2twdWhnMmVkcXpqcHN6dWx3aGd6dWo5bGpzGgwKBXN0YWtlEgM1MDA=\\\",\\\"type\\\":\\\"RUNTX\\\"}\"},{\"key\":\"packet_timeout_height\",\"value\":\"0-0\"},{\"key\":\"packet_timeout_timestamp\",\"value\":\"9223372036854775807\"},{\"key\":\"packet_sequence\",\"value\":\"2\"},{\"key\":\"packet_src_port\",\"value\":\"ibcaccount\"},{\"key\":\"packet_src_channel\",\"value\":\"channel-0\"},{\"key\":\"packet_dst_port\",\"value\":\"ibcaccount\"},{\"key\":\"packet_dst_channel\",\"value\":\"channel-0\"},{\"key\":\"packet_channel_ordering\",\"value\":\"ORDER_ORDERED\"},{\"key\":\"packet_connection\",\"value\":\"connection-0\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"send"},{"key":"module","value":"ibc_channel"}]},{"type":"send_packet","attributes":[{"key":"packet_data","value":"{\"data\":\"Co8BCowBChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEmwKLWNvc21vczFwdDZhcjhsYXdtdnZxNWhheGMzbDN6aGpmbDA0dTU2ZnMybmRoORItY29zbW9zMTdkdGwwbWp0M3Q3N2twdWhnMmVkcXpqcHN6dWx3aGd6dWo5bGpzGgwKBXN0YWtlEgM1MDA=\",\"type\":\"RUNTX\"}"},{"key":"packet_timeout_height","value":"0-0"},{"key":"packet_timeout_timestamp","value":"9223372036854775807"},{"key":"packet_sequence","value":"2"},{"key":"packet_src_port","value":"ibcaccount"},{"key":"packet_src_channel","value":"channel-0"},{"key":"packet_dst_port","value":"ibcaccount"},{"key":"packet_dst_channel","value":"channel-0"},{"key":"packet_channel_ordering","value":"ORDER_ORDERED"},{"key":"packet_connection","value":"connection-0"}]}]}],"info":"","gas_wanted":"90000","gas_used":"56050","tx":null,"timestamp":""}
ancas-mbp:interchain-accounts ancaz$ icad tx intertx send cosmos-sdk $VAL_2 500stake --source-port ibcaccount --source-channel channel-0 --chain-id test-1 --gas 90000 --home ./data/test-1 --node tcp://localhost:16657 --from val1
{"body":{"messages":[{"@type":"/intertx.MsgSend","chain_type":"cosmos-sdk","source_port":"ibcaccount","source_channel":"channel-0","sender":"cosmos1mjk79fjjgpplak5wq838w0yd982gzkyfrk07am","to_address":"cosmos17dtl0mjt3t77kpuhg2edqzjpszulwhgzuj9ljs","amount":[{"denom":"stake","amount":"500"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"90000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: n
cancelled transaction
ancas-mbp:interchain-accounts ancaz$ icad q bank balances $IBC_ACCOUNT --chain-id test-2
balances:
- amount: "500"
  denom: stake
pagination:
  next_key: null
  total: "0"
ancas-mbp:interchain-accounts ancaz$ icad q bank balances $VAL_2 --chain-id test-2
balances:
- amount: "92999989500"
  denom: stake
pagination:
  next_key: null
  total: "0"
```

**Comment by ancazamfir** [comment]
> relevant [discussion](https://github.com/informalsystems/ibc-rs/pull/839#pullrequestreview-647281562)
> 
> also I think it is because the event type in [bank is "send"](https://github.com/informalsystems/ibc-rs/blob/7c0418e3f6adf270a2a91f19b39a0141234c7545/relayer/src/event/rpc.rs#L104)
> 
> I am a little confused why ibc-rs isn't building the [send packet](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet.go#L124) event. Does ibc-go need to add support for something?
> 
> Edit: I understand the issue now, because ibc-rs listens for message.action (the message that is delivered to base app). I guess this is a problem with the event system since it is hard to distinguish the difference between events atm

The `May 26 16:28:16.152  WARN ibc_relayer::event::rpc: error while building event send_packet.packet_data`..comes from a try to decode `send_packet` attributes from the events for `message.action: send`. Since ICA is using this message action for IBC transfers we added it to our event extractor so we try now for intra-chain sends as well. You can ignore the warning. In fact this will be lowered as a trace in the next release (many people found it confusing).

**Comment by seantking** [comment]
> I followed the steps and I don't see an issue. The balance is updated after the last command:
> `icad tx intertx send cosmos-sdk $VAL_2 500stake --source-port ibcaccount --source-channel channel-0 --chain-id test-1 --gas 90000 --home ./data/test-1 --node tcp://localhost:16657 --from val1`
> 
> I don't understand ica well but from what I can tell there are two IBC transfers that happen in the instructions and they are triggered by the `icad tx intertx...` commands.
> 
> In order to see if there are any un-relayed packets you can execute (use the right config.toml):
> 
> ```
> hermes -c config-ica.toml query packet unreceived-packets test-1 ibcaccount channel-0
> hermes -c config-ica.toml query packet unreceived-packets test-2 ibcaccount channel-0
> hermes -c config-ica.toml query packet unreceived-acks test-2 ibcaccount channel-0
> hermes -c config-ica.toml query packet unreceived-acks test-1 ibcaccount channel-0
> ```
> 
> Here is an output snipet:
> 
> ```
> ancas-mbp:interchain-accounts ancaz$ icad q bank balances $IBC_ACCOUNT --chain-id test-2
> balances:
> - amount: "1000"
>   denom: stake
> pagination:
>   next_key: null
>   total: "0"
> ancas-mbp:interchain-accounts ancaz$ icad tx intertx send cosmos-sdk $VAL_2 500stake --source-port ibcaccount --source-channel channel-0 --chain-id test-1 --gas 90000 --home ./data/test-1 --node tcp://localhost:16657 --from val1
> {"body":{"messages":[{"@type":"/intertx.MsgSend","chain_type":"cosmos-sdk","source_port":"ibcaccount","source_channel":"channel-0","sender":"cosmos1mjk79fjjgpplak5wq838w0yd982gzkyfrk07am","to_address":"cosmos17dtl0mjt3t77kpuhg2edqzjpszulwhgzuj9ljs","amount":[{"denom":"stake","amount":"500"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"90000","payer":"","granter":""}},"signatures":[]}
> 
> confirm transaction before signing and broadcasting [y/N]: y
> {"height":"324","txhash":"CAB8E0385C7AFE8D086574D46500603269A422AD6598F4D60AA3788FB100ED4B","codespace":"","code":0,"data":"0A060A0473656E64","raw_log":"[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"send\"},{\"key\":\"module\",\"value\":\"ibc_channel\"}]},{\"type\":\"send_packet\",\"attributes\":[{\"key\":\"packet_data\",\"value\":\"{\\\"data\\\":\\\"Co8BCowBChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEmwKLWNvc21vczFwdDZhcjhsYXdtdnZxNWhheGMzbDN6aGpmbDA0dTU2ZnMybmRoORItY29zbW9zMTdkdGwwbWp0M3Q3N2twdWhnMmVkcXpqcHN6dWx3aGd6dWo5bGpzGgwKBXN0YWtlEgM1MDA=\\\",\\\"type\\\":\\\"RUNTX\\\"}\"},{\"key\":\"packet_timeout_height\",\"value\":\"0-0\"},{\"key\":\"packet_timeout_timestamp\",\"value\":\"9223372036854775807\"},{\"key\":\"packet_sequence\",\"value\":\"2\"},{\"key\":\"packet_src_port\",\"value\":\"ibcaccount\"},{\"key\":\"packet_src_channel\",\"value\":\"channel-0\"},{\"key\":\"packet_dst_port\",\"value\":\"ibcaccount\"},{\"key\":\"packet_dst_channel\",\"value\":\"channel-0\"},{\"key\":\"packet_channel_ordering\",\"value\":\"ORDER_ORDERED\"},{\"key\":\"packet_connection\",\"value\":\"connection-0\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"send"},{"key":"module","value":"ibc_channel"}]},{"type":"send_packet","attributes":[{"key":"packet_data","value":"{\"data\":\"Co8BCowBChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEmwKLWNvc21vczFwdDZhcjhsYXdtdnZxNWhheGMzbDN6aGpmbDA0dTU2ZnMybmRoORItY29zbW9zMTdkdGwwbWp0M3Q3N2twdWhnMmVkcXpqcHN6dWx3aGd6dWo5bGpzGgwKBXN0YWtlEgM1MDA=\",\"type\":\"RUNTX\"}"},{"key":"packet_timeout_height","value":"0-0"},{"key":"packet_timeout_timestamp","value":"9223372036854775807"},{"key":"packet_sequence","value":"2"},{"key":"packet_src_port","value":"ibcaccount"},{"key":"packet_src_channel","value":"channel-0"},{"key":"packet_dst_port","value":"ibcaccount"},{"key":"packet_dst_channel","value":"channel-0"},{"key":"packet_channel_ordering","value":"ORDER_ORDERED"},{"key":"packet_connection","value":"connection-0"}]}]}],"info":"","gas_wanted":"90000","gas_used":"56050","tx":null,"timestamp":""}
> 
> ancas-mbp:interchain-accounts ancaz$ icad q bank balances $IBC_ACCOUNT --chain-id test-2
> balances:
> - amount: "500"
>   denom: stake
> pagination:
>   next_key: null
>   total: "0"
> ancas-mbp:interchain-accounts ancaz$ icad q bank balances $VAL_2 --chain-id test-2
> balances:
> - amount: "92999989500"
>   denom: stake
> pagination:
>   next_key: null
>   total: "0"
> ```

Thank you for spending time looking at this :pray: 

Yes you are actually correct. I think I was working with some incorrect data on my side. It's working out of the box for me now.

**Comment by seantking** [comment]
> > relevant [discussion](https://github.com/informalsystems/ibc-rs/pull/839#pullrequestreview-647281562)
> > also I think it is because the event type in [bank is "send"](https://github.com/informalsystems/ibc-rs/blob/7c0418e3f6adf270a2a91f19b39a0141234c7545/relayer/src/event/rpc.rs#L104)
> > I am a little confused why ibc-rs isn't building the [send packet](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet.go#L124) event. Does ibc-go need to add support for something?
> > Edit: I understand the issue now, because ibc-rs listens for message.action (the message that is delivered to base app). I guess this is a problem with the event system since it is hard to distinguish the difference between events atm
> 
> The `May 26 16:28:16.152 WARN ibc_relayer::event::rpc: error while building event send_packet.packet_data`..comes from a try to decode `send_packet` attributes from the events for `message.action: send`. Since ICA is using this message action for IBC transfers we added it to our event extractor so we try now for intra-chain sends as well. You can ignore the warning. In fact this will be lowered as a trace in the next release (many people found it confusing).

Aha, I understand now. Thank you for the response.

**Comment by seantking** [comment]
Happy to close this issue :+1: 

Thank you!

**Comment by andynog** [comment]
As per @seantking ack, will close the issue. Thanks!
