### ISSUE TITLE
Cargo build fails for current master

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#101]
## Summary of Bug

Vanilla install of `ibc-rs` does not compile.

## Steps to Reproduce

```
git clone git@github.com:informalsystems/ibc-rs.git
cd ibc-rs/
cargo build
```

Output:

```
...
   Compiling tendermint v0.13.0 (https://github.com/informalsystems/tendermint-rs.git#740cb66e)
   Compiling relayer-modules v0.1.0 (/private/tmp/ibc-rs/modules)
error[E0412]: cannot find type `Proof` in module `abci`
  --> modules/src/ics23_commitment/mod.rs:21:34
   |
21 | pub type CommitmentProof = abci::Proof;
   |                                  ^^^^^ not found in `abci`
   |
help: possible candidate is found in another module, you can import it into scope
   |
1  | use tendermint::merkle::proof::Proof;
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: could not compile `relayer-modules`.
```

Possibly related to #96 .
Master head is at this [commit](https://github.com/informalsystems/ibc-rs/commit/07614579fb5ab6da517b083fe723e5c51a339465).
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
just fixed in cf63bda..sorry, in the rush to fix forgot to switch to new branch and committed to master by mistake :(
If you update you should be able to build.
