### ISSUE TITLE
Source and destination chains should be distinguished through generic type parameters

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-rs#1010]
## Crate

`ibc-rs`

## Summary

Right now both source and destination chains have the same static or dynamic types. This makes it very easy to mix up values coming from either chains, and makes it difficult for readers to verify the correctness of the relayer algorithms. The chains should instead be parameterized by generic parameters, so that values from different chains would have different types and thus impossible to get mixed up.

For example, we could redesign the `ForeignClient` type to be:

```rust
pub struct ForeignClient<SourceChain, DestChain> {
  src_chain: SourceChain,
  dst_chain: DestChain,
  ...
}

impl <SourceChain: ChainHandle, TargetChain: ChainHandle>
  ForeignClent<SourceChain, DestChain>
{ ... }
```

The chain traits should also has associated types like `Height` so that the associated values cannot get mixed up.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Looks like this was addressed via #1276.
