### ISSUE TITLE
More information on returned configuration error

### ISSUE THREAD

**Issue by colin-axner** [informalsystems/ibc-rs#1020]
## Crate

relayer-cli

## Summary

using v0.3.2
```
hermes -c config_example.toml start cosmoshub-4 akashnet-2 -c channel-95
    Finished release [optimized] target(s) in 0.11s
     Running `target/release/hermes -c config_example.toml start cosmoshub-4 akashnet-2 -c channel-95`
Error: chain runtime error: event monitor error: failed to create WebSocket driver: WebSocket Error: IO error: Connection refused (os error 111) (code: 1)
```
Note, I modified config_example with the information necessary. I just didn't want to modify my config in ~/.hermes.

## Problem Definition

I'm not sure which chain the connection failed for

## Proposal

Indicate which chain failed. 

## Acceptance Criteria

Printing the chain-id for the failed connection

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
I fixed my bug. As the error indicated the web socket address was wrong :+1:

**Comment by adizere** [comment]
Thanks for pointing this out!

The fix this is to augment the error type [ClientCreationFailed](https://github.com/informalsystems/ibc-rs/blob/c375c719d8828b63b2ed0b8f8d1f96db99410138/relayer/src/event/monitor.rs#L49) with additional fields, for capturing the culprit chain identifier & address.
