### ISSUE TITLE
indicate config file error when applicable

### ISSUE THREAD

**Issue by colin-axner** [informalsystems/ibc-rs#1021]
## Crate

relayer-cli

## Summary of Bug

```
hermes help start
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/hermes help start`
error: hermes fatal error: parse error: unknown variant `naive`, expected `packets` or `all` for key `global.strategy` at line 31 column 1
```

## Version

master

## Steps to Reproduce

build master, run:
```
hermes -c config_example.toml start cosmoshub-4 akashnet-2 -p transfer -c channel-95
    Finished release [optimized] target(s) in 0.11s
     Running `target/release/hermes -c config_example.toml start cosmoshub-4 akashnet-2 -p transfer -c channel-95`
error: unexpected free argument `cosmoshub-4`

hermes 0.3.2
Informal Systems <hello@informal.systems>
For help, run `hermes [<FLAGS>] help <COMMAND>`, for example: `hermes help create client`

FLAGS:
    -c, --config CONFIG       path to configuration file
    -j, --json                enable JSON output
```

follow the provided hint ``For help, run `hermes [<FLAGS>] help <COMMAND>``

## Acceptance Criteria

The help command displays the help page for `hermes start`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
Ah! The issue was in parsing my configuration file! Is there any way to indicate this in the error message?

**Comment by adizere** [comment]
> Ah! The issue was in parsing my configuration file! Is there any way to indicate this in the error message?

Indeed. There was a breaking change which we didn't signal very well (#924), specifically the `global.strategy` field. 

https://github.com/informalsystems/ibc-rs/blob/cdecd3674af564bb069681c2335185853e878a70/config.toml#L1-L5

Unfortunately, the message which Hermes prints upon doing

```
hermes help start
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/hermes help start`
error: hermes fatal error: parse error: unknown variant `naive`, expected `packets` or `all` for key `global.strategy` at line 31 column 1
```
is not at all a help message. The config.toml could not be parsed, which prevents executing the `help` command. Hermes should be more explicit about this..

**Comment by colin-axner** [comment]
Thanks for the reply @adizere. I eventually managed to deduce the issue based on the error message, but it would be great if the error message could be prefixed with "configuration file error" or something like that? Would this be possible?
