### ISSUE TITLE
Add a `keys delete` command to remove keys from Hermes configuration

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#1065]
## Crate

Hermes should provide a command to remove keys from its configuration. This might help with key maintenance and also to remove incompatible keys.

## Summary

As a user/operator I want to have a command to remove a previously added keys for a chain removed from Hermes keys store (`~/.hermes/keys)

## Problem Definition

Currently we only support updating keys adding or restoring them again. But there might be cases where a key needs to be removed (e.g. incompatible key)

## Proposal

We should implement a command e.g. `keys delete [chain-id] -n [key-name]`

We could also implement a `keys delete --all` to clean the whole key store if it makes sense.

## Acceptance Criteria

Keys are removed using the Hermes command

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
Should we name the command `delete` instead of `clean`? Just to stay consistent with `gaiad`?
