### ISSUE TITLE
Adding key generation algorithm for "eth_secp256k1"

### ISSUE THREAD

**Issue by leejw51crypto** [informalsystems/ibc-rs#1071]
currently, we can generate keys like this, default algo is secp256k1
```
hermes keys restore ethermint-2  -m "my mnemocnis.." -t 60
```
that's different from ethermint's one.

```
ethermintd keys add $KEY --keyring-backend test --algo "eth_secp256k1"
```

so we can add like this
```
hermes keys restore ethermint-2  -m "my mnemocnis.." -t 60 --algo "eth_secp256k1"
```
so user can freely designate 20 payload address representaion algorithm.

for example
```
secp256k1:   pubkey->sha256->last 20 bytes
eth_secp256k1: pubkey->sha256->ripemd160->20 bytes
```

also we can support other cosmos network which uses different address logic.

**Comment by adizere** [comment]
This seems related to https://github.com/informalsystems/ibc-rs/issues/1155.

@leejw51crypto we plan to get to this by end of October. Please let us know if that timeline is OK, or if you have more specific time constraints in mind.

**Comment by xlab** [comment]
We at InjectiveLabs also run Ethermint-compatible chain, implemented full support for the `eth_ secp256k1` keys here
https://github.com/InjectiveLabs/ibc-rs/commit/28e7c65097a45c0fcfeaca792dbb72744b404355

**Comment by devashishdxt** [comment]
@xlab How do you handle 2nd point in #1267?

**Comment by xlab** [comment]
@devashishdxt I just got up to the 2nd point. Debugging to see what's wrong there on the ibc-rs side.

**Comment by RiccardoM** [comment]
Is there any cherry pick we can do to fix this issue?
