### ISSUE TITLE
`hermes keys add` and `hermes keys restore` are redundant

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#1075]
## Crate
relayer-cli

## Summary
We could reduce the number of commands supported under `hermes keys`.

## Problem Definition
With the `--hd-path` command implemented for both `keys add` and `keys restore`, the two commands essentially require the same parameters but in a different format. One requests the mnemonic from a file, the other from the stdin.

It would simpler to only maintain one code base instead.

## Proposal
a.) Merge the two commands into add that has both the `-f` and the `-m` command. They are interchangeable but only one can be defined.
b.) Come up with other solutions so there's only one code that supports adding/restoring keys.

## Acceptance Criteria
Done: The process of adding/restoring keys is straightforward.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mircea-c** [comment]
I'd like to add that the `-p` flag used in the `restore` command is very unsafe. The mnemonic has to be pasted in the command line and then is possibly saved to shell history file. I would eliminate this completely in favour of reading the mnemonics from a file or from stdin.
