### ISSUE TITLE
CLI auto-complete support

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#1096]
## Crate

`ibc-relayer-cli`

## Summary

Add auto-complete support using a rust crate (`clap`/`gumdrop`) that can automatically generate the completions file (see [Clap::gen_completions()](https://docs.rs/clap/2.33.3/clap/struct.App.html#method.gen_completions)).

## Acceptance Criteria

We should be able to achieve something like this ->
![Clap auto-complete demo](http://i.imgur.com/icbrIYe.gif)

The hermes documentation and README.md should provide instructions for setting this up. Also, installers/packages should be updated to include and source the completions file. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rnbguy** [comment]
I ended up here because of this. :smile:
https://github.com/informalsystems/ibc-rs/blob/09a4b114b7fd414547c539bc8d541470c30b8164/scripts/gm/bin/shell-support#L110

I can take a look at this. This can be done in the same way `rustup completions (bash|fish|zsh)`.

Here is how [Archlinux distributes shell completions for Rustup](
https://github.com/archlinux/svntogit-community/blob/packages/rustup/trunk/PKGBUILD#L36-L44).

```
    # Generate completion files.
    mkdir -p "$pkgdir/usr/share/bash-completion/completions"
    "$pkgdir"/usr/bin/rustup completions bash > "$pkgdir/usr/share/bash-completion/completions/rustup"
    "$pkgdir"/usr/bin/rustup completions bash cargo > "$pkgdir/usr/share/bash-completion/completions/cargo"
    mkdir -p "$pkgdir/usr/share/fish/vendor_completions.d"
    "$pkgdir"/usr/bin/rustup completions fish > "$pkgdir/usr/share/fish/vendor_completions.d/rustup.fish"
    mkdir -p "$pkgdir/usr/share/zsh/site-functions"
    "$pkgdir"/usr/bin/rustup completions zsh > "$pkgdir/usr/share/zsh/site-functions/_rustup"
    "$pkgdir"/usr/bin/rustup completions zsh cargo > "$pkgdir/usr/share/zsh/site-functions/_cargo"
```

**Comment by mzabaluev** [comment]
This should be easy to do with clap 3.x.

**Comment by rnbguy** [comment]
[`clap_generate`](https://docs.rs/clap_generate) used to exist already, which is now deprecated in favor of [`clap_complete`](https://docs.rs/clap_complete) when clap 3.x reached stable.

My changes for Modelator are at informalsystems/modelator@0aa7d41.

---
<sup>I feel `clap` should provide a `shell-completion` feature to do this automatically.</sup>

**Comment by mzabaluev** [comment]
I think we need to approach this by way of #1752, when we can start using clap 3.0 stable.

**Comment by mzabaluev** [comment]
> My changes for Modelator are at [informalsystems/modelator@0aa7d41](https://github.com/informalsystems/modelator/commit/0aa7d41).

@rnbguy Any chance to get the `rnbguy/rust/clap-v3` branch for modelator merged soon? I've used it in #1777 draft, let's see if MBTs pass.

**Comment by mzabaluev** [comment]
> @rnbguy Any chance to get the `rnbguy/rust/clap-v3` branch for modelator merged soon?

I'm a bit out of date and see https://github.com/informalsystems/modelator/pull/163 has been merged. The question then turns into "when is the next release?"

**Comment by rnbguy** [comment]
I will do a patch release at the end of the day :)

**Comment by rnbguy** [comment]
modelator `0.4.2` is up :smiley:
