### ISSUE TITLE
Make more use of generic types

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#1103]
## Summary

We should make more using of generic types instead of dynamic traits to abstract over the implementation. For example, instead of a function like fn handler(chain1: Box<dyn ChainHandler>, chain2: Box<dyn ChainHandler>), it could instead be written as fn handle<Chain1: ChainHandler, Chain2: ChainHandler>(chain1: Chain1, chain2: Chain2). The chain implementations could then have associated types such as Height, Connection, etc. This would make it less likely to accidentally mix up the values when forwarding them from one chain to another.

(copied from @soareschen's original proposal [here](https://github.com/informalsystems/ibc-rs/discussions/1055#discussioncomment-839782))
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
The main use-case for generic types was in the context of the ChainHandle. Since 1253 fixed that, let's close this PR. We'll consider down the road if further investments in generics are worth.
