### ISSUE TITLE
First release + more mature repo standards

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#112]
## Summary

Preparations for the first release.

## Proposal

Minimal list of prerequisites:

- CHANGELOG
- README update
- release not necessarily aligned with milestones, e.g., this release fill fall between milestones [5](https://github.com/informalsystems/ibc-rs/milestone/5) and [6](https://github.com/informalsystems/ibc-rs/milestone/6).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
> release not necessarily aligned with milestones, e.g., this release fill fall between milestones 5 and 6.

Yes, this was on purpose. Milestones are mid-month to allow for release preparation by end of month. But now with releases every every month not sure it makes sense anymore.
