### ISSUE TITLE
Add filtering to `query channels` to show channels between a pairs of chains

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#1132]
## Crate
relayer-cli

## Summary
Current `hermes query channels <chain-id>` shows all channels on the specified chains.
It would be very useful to show all channels between two chains.

## Problem Definition
Needed for operations (Dex, osmosis, etc).

## Proposal
Extend `query channels` to take an optional destination chain. In addition add the `--verbose` option to show client and connection ids on the counterparty chain. In this case the output should use, for each channel, the same format as in #1062 

```query channels <chain-id> [--destination-chain <chain-id>] [--verbose]```
e.g.:

```
$ query channels ibc-0 -d ibc-1

Success: [
    PortChannelId {
        channel_id: ChannelId(
            "channel-0",
        ),
        port_id: PortId(
            "transfer",
        ),
    },
    PortChannelId {
        channel_id: ChannelId(
            "channel-1",
        ),
        port_id: PortId(
            "transfer",
        ),
    },
]
```

```
$ query channels ibc-0 -d ibc-1 --verbose
...
```

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Found out that the filtering implemented in #1243 does not work. 

Note: The option `--destination-chain` was renamed into `--counterparty-chain` as part of ADR 010 and its implementation.

Examples:

- we have a single channel opened between `ibc-0` and `ibc-1` in these examples;
- filtering by the same chain as the chain we're querying
```
$ hermes query channels --chain ibc-0 --counterparty-chain ibc-0
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/hermes query channels --chain ibc-0 --counterparty-chain ibc-0`
2022-06-24T08:03:53.395055Z  INFO ThreadId(01) using default configuration from '/Users/adi/.hermes/config.toml'
2022-06-24T08:03:53.396324Z DEBUG ThreadId(01) Options: QueryChannelsCmd { chain_id: ChainId { id: "ibc-0", version: 0 }, dst_chain_id: Some(ChainId { id: "ibc-0", version: 0 }), verbose: false }
2022-06-24T08:03:53.404463Z TRACE ThreadId(01) spawned chain runtime chain=ibc-0
Success: [
    PortChannelId {
        channel_id: ChannelId(
            "channel-0",
        ),
        port_id: PortId(
            "transfer",
        ),
    },
]
```

- filtering by a non-existing chain `ibc-10`


```
$ hermes query channels --chain ibc-0 --counterparty-chain ibc-10
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/hermes query channels --chain ibc-0 --counterparty-chain ibc-10`
2022-06-24T08:11:37.139260Z  INFO ThreadId(01) using default configuration from '/Users/adi/.hermes/config.toml'
2022-06-24T08:11:37.140570Z DEBUG ThreadId(01) Options: QueryChannelsCmd { chain_id: ChainId { id: "ibc-0", version: 0 }, dst_chain_id: Some(ChainId { id: "ibc-10", version: 10 }), verbose: false }
2022-06-24T08:11:37.149776Z TRACE ThreadId(01) spawned chain runtime chain=ibc-0
Success: [
    PortChannelId {
        channel_id: ChannelId(
            "channel-0",
        ),
        port_id: PortId(
            "transfer",
        ),
    },
]
```

Tested w/ versions:
- master: baf0e3f60f37934cab89526f47f7cb6524f7d92c
- and as part of PR https://github.com/informalsystems/ibc-rs/pull/2275
