### ISSUE TITLE
High Level Goal - IBC Relayer  

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#114]
## Summary
High Level Goal for 2020: Production ready IBC Relayer  

## Proposal
Implementation of the IBC Relayer that provides:

- clear specifications
  [x] protocol spec: #84, #82 
  [x] TLA #70, #71, #89, #106, #124 
  [ ] ADR #67 

- correct and efficient relay algorithm implementation
    [ ] concurrency architecture (#326) and implementation (#327)
    [ ] relayer `config executor` implementation (tbd)
    [ ] relayer `link` implementation (#328)
    [ ] relayer `chain` implementation for events (tbd)
    [x]  clear separation of concerns #85, #90 
    [ ]  Events: #102 (small dependency on cosmos-sdk)
    [ ] finish all queries (serialization/ deserialization with protobuf/ json, etc as required) #128
    [ ]  transaction signing and submission #47,  #206, #207, #277, #208,
    [ ]  integration with secure keystores, e.g. KMS

-  testability 
    [ ]  testing infrastructure for UT and MBT
    [ ]  CI #32

-  handling bad full nodes
   [ ]  proof verification (integrate with confio's ics23 in Rust, probably needs some updates) #96 - not needed for end-to-end demonstration of functionality, but needed to detect faulty full nodes ...
   [ ]  allow connections to multiple RPC nodes
   [ ]  drop RPC nodes giving bad IBC Events
   [ ]  drop RPC nodes giving bad IBC Query responses

 -  debugability
   [ ]  proper error definition, propagation, introspection (e.g. via logs) #68
   [ ]  ability to query the relayer state
   [ ]  comprehensive chain query commands
   [ ]  ability to perform single step IBC transactions via CLI
   [ ]  log relayer events to file

 -  usability 
   [ ]  refine the config file specification and implementation #69, #99
   [ ]  documentation: rustdoc (with examples), README.md
   [ ]  other userdocs

**Comment by adizere** [comment]
We set milestones at roughly the middle of each month, e.g., _September 15, 2020_ is the deadline for [0.8-8mo](https://github.com/informalsystems/ibc-rs/milestone/9). Do we plan to use this buffer time of two weeks (Sept 15 to end of September) in a specific way or is the misalignment just a coincidence?

**Comment by adizere** [comment]
Perhaps we can additionally consider the following: ADR for "Relayer requirements on Light Client" (suggested in #60).

**Comment by adizere** [comment]
One more functionality that I believe would be important for this milestone, in the category "usability," is to automate the relayer bootstrapping procedure. Currently, bootstrapping the relayer involves some manual steps (see [description](https://github.com/informalsystems/ibc-rs#running-the-relayer)), which can be captured in a simple script and thus improve usability.

**Comment by adizere** [comment]
Moved most of the relevant issues from here into #385.
