### ISSUE TITLE
Hermes schedule execution routine can drop op. data

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1153]
This bug was observed during operation for the Osmosis app. @greg-szabo pointed out the underlying issue and we uncovered it looking directly at logs.

## Crate

`ibc-relayer`

## Summary of Bug

The `execute_schedule` method can potentially drop an operational data, thus Hermes will never relay the messages
associated with that data. The method is as follows

https://github.com/informalsystems/ibc-rs/blob/c78b793d99571df4781cec4c2cfcb18ed68098d1/relayer/src/link.rs#L1289-L1302

The scenario that can lead to a dropped op. data is as follows:

1. line 1290: Hermes removes some op. data that have been scheduled earlier, and retains X operational data to be sent to the Destination chain in the vector `dst_ods`.
    - this means that `len(dst_ods) = X`
    - it is important that X is strictly larger than 1, let's take as example 2

2. line 1294: Hermes takes the first element (among 2 of them) from the vector `dst_ods`
3. line 1295: Hermes attempts to run `relay_from_operational_data(..)?` on that first element
    - suppose that the method `relay_from_operational_data` fails
    - in this case, the whole method `execute_schedule` returns because of the `?`
4. the second element from vector `dst_ods` is never handled

Similarly, any elements from the vector `src_ods` is never handled either. So Hermes never sends those messages.

## Version

de62a4b9329dc00df11720627846d3ef9e3ada87

## Acceptance Criteria

- [ ] clarify if `relay_from_operational_data` can fail
- [ ] reproduce the problem in an automated (integration) test if possible
    - the main difficult in reproducing is in making the method `relay_from_operational_data` fail: unclear if that is easily made to fail
- [ ] `execute_schedule` should not remove multiple elements from the scheduled op. data, instead should remove them one by one

____

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Adi mentioned that @ancazamfir is convinced that the `relay_from_operational` data method is (mostly) infallible, such that in most cases no operational data will be dropped. Looking at the method in a vacuum, it seems like it will only drop operational data when the max number of retries have been attempted, or some undocumented non-recoverable error occurs: 

https://github.com/informalsystems/ibc-rs/blob/master/relayer/src/link/relay_path.rs#L481-L515

Is this a correct assessment?

**Comment by adizere** [comment]
This matches my understanding.

The point of this issue is to refactor `execute_schedule` and `relay_from_operational_data` to clarify the interactions there:
- it should be obvious when errors propagate up the stack (i.e., when `relay_from_operational_data` fails), and
- to prevent a leaky pipeline (i.e., prevent dropping operational data in `execute_schedule`).

**Comment by seanchen1991** [comment]
I would say the above listed concerns are pretty distinct. 

> it should be obvious when errors propagate up the stack (i.e., when relay_from_operational_data fails)
This seems to indicate the need to simplify this code flow. I thought #1154 had some interesting suggestions along these lines. Perhaps we should revisit those ideas? 

> to prevent a leaky pipeline (i.e., prevent dropping operational data in execute_schedule)
I think for this concern, we should start off verifying that this problem does indeed exist with an integration test, and then figure out what code changes need to occur from there.

**Comment by seanchen1991** [comment]
Posting @soareschen's thoughts on how to approach testing this issue:
> I think if we want, we could try testing that at the unit level by working on `RelayPath` directly. So the step would be something like:
1. Do not automatically start the relayer
2. Perform an IBC transfer
3. Manually create a `Link` and `RelayPath`
4. Manually call `relay_path.schedule_packet_clearing()` (maybe? so that the pending packets are added to the queue)
5. Manually perform the steps in `spawn_packet_worker`, i.e. call `relay_path.refresh_schedule()`
6. Check that the packet is in the relay path
7. Call `chain.shutdown()`
8. Call `relay_path.execute_schedule()`, which should fail because the chain handle has stopped.
9. Check that the packet is still in the relay path
So the whole complexity of the test depends on whether it is difficult to create a `Link` and perform manual relaying without the supervisor. With my previous refactoring, hopefully that is easier now. At a quick glance, it seems like `Link::new()` only requires a `Channel`, which is already available inside `ConnectedChannel`.
If you want to test this, you should first try and see if you can perform a manual relaying by directly calling the methods in Link and RelayPath without the supervisor. That might be worth adding as a separated integration test and submitted as a separate PR.

**Comment by seanchen1991** [comment]
@adizere and I came up with a revised set of steps for the `execute_schedule` integration test:

1. Do not automatically start the relayer
2. Perform 2 IBC transfers
3. Manually create a `Link` and `RelayPath`
4. Manually call `relay_path.schedule_packet_clearing() in order to add the pending packets to the queue
5. Check that the packets are in the relay path
6. Shut down the destination chain
7. Call `relay_path.execute_schedule()`, which should fail because the destination chain is unreachable
8. Check that the _second_ packet is still in the relay path

**Comment by adizere** [comment]
> 2. Perform 2 IBC transfers

Sean rightly pointed out that creating 2 IBC transfers on the same direction (chain A -> B) will result in a _single_ operational data that batches both those packets. This means that 

> 5. Check that the packets are in the relay path

There will be a single op. data in the relay path. Therefore, step 8 will not work: we cannot check that there is a second packet (i.e. second op. data) in the relay path, since the second packet was batched with the first packet.

To fix this, I suggest at step 2 we do a packet in _each_ direction, A -> B and B ->A. This will result in two operational data elements, one in `relay_path.src_operational_data`, and another one in `relay_path.dst_operational_data`. We keep all the other steps. Then at step 7. when we execute the schedule, it will result in 
- both op. data being dequeued
- one of them fails (the first one to execute)
- the other operational data will be dropped (should be re-queued for execution), thus reproducing the original issue.

**Comment by seanchen1991** [comment]
I've refactored the test to encode these revised steps. However, I'm not sure the test is really capturing the issue. 

After setting up the `Link`s and `RelayPath`s in both directions (each `RelayPath` only captures one direction) and calling `schedule_packet_clearing` on both `RelayPath`s, then killing one of the chains before calling `execute_schedule` on _one_ of the `RelayPath`s, the other piece of operational data seems to not be affected. However, it doesn't make sense to me why it would be in the first place; intuitively I would assume that calling `relay_path_a_to_b.execute_schedule()` would not affect the operational data on `relay_path_b_to_a`. So I'm not sure if this test as it currently stands is actually capturing the behavior we're attempting to diagnose.

**Comment by adizere** [comment]
> However, it doesn't make sense to me why it would be affected in the first place; intuitively I would assume that calling `relay_path_a_to_b.execute_schedule()` would not affect the operational data on `relay_path_b_to_a`. So I'm not sure if this test as it currently stands is actually capturing the behavior we're attempting to diagnose.

You're right again, the scenario sketched above is still not enough to reproduce the original issue.

One more idea, what if we do:

```rust
        chains.node_a.chain_driver().ibc_transfer_token(...)
        relay_path_a_to_b.schedule_packet_clearing(None)?;

        chains.node_a.chain_driver().ibc_transfer_token(...)
        relay_path_a_to_b.schedule_packet_clearing(None)?;
```

that is, essentially two separate transfers in the same direction and two calls to `schedule_packet_clearing`. Then I think we should see two separate operational data

```rust
        assert_eq!(relay_path_a_to_b.dst_operational_data.len(), 2);
```

then killing `node_b` and executing `relay_path_a_to_b.execute_schedule() {` should lead to an internal error and dropping of both operational data. The first operational data encounters the error and propagates it, while the second operational data is never even attempted (is dropped, but the correct behavior is that is should be put back in the queue of `relay_path_a_to_b.dst_operational_data`).
