### ISSUE TITLE
"thread 'main' panicked at 'OpenSSL library directory does not exist: /usr/bin/lib'" (v0.6.0-rc2)

### ISSUE THREAD

**Issue by lightiv** [informalsystems/ibc-rs#1162]
## Crate

I new to this so I am not sure which Crate but this occurs during install

## Summary of Bug

error: failed to run custom build command for `openssl-sys v0.9.65`

Caused by:
 process didn't exit successfully: `/home/lightiv/ibc-rs/target/release/build/openssl-sys-a14e45a2013c726c/build-script-main` (exit status: 101)

## Version

v0.6.0-rc2

## Steps to Reproduce

Fresh install of Ubuntu 20.04 LTS/Rust/Go
git checkout v0.6.0-rc2
cargo build --release --bin hermes

## Acceptance Criteria

hermes completes installation

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by lightiv** [comment]
Note:  this issue occurs for v0.6.0-rc1 and v0.5.0 for me.

**Comment by lightiv** [comment]
OpenSSL version install: OpenSSL 1.1.1f  31 Mar 2020

**Comment by lightiv** [comment]
Reboot and attempted install
```
cargo build --release --bin hermes
   Compiling ibc-relayer-cli v0.5.0 (/home/lightiv/ibc-rs/relayer-cli)
   Compiling openssl-sys v0.9.65
   Compiling const_fn v0.4.8
error: failed to run custom build command for `openssl-sys v0.9.65`

Caused by:
  process didn't exit successfully: `/home/lightiv/ibc-rs/target/release/build/openssl-sys-a14e45a2013c726c/build-script-main` (exit status: 101)
```

**Comment by lightiv** [comment]
```
  --- stderr
  thread 'main' panicked at 'OpenSSL library directory does not exist: /usr/bin/lib', /home/lightiv/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.65/build/main.rs:66:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
     1: std::panicking::begin_panic_fmt
               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
     2: build_script_main::main
     3: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by lightiv** [comment]
openssl version -a
```
OpenSSL 1.1.1k  25 Mar 2021
built on: Fri Jul  9 03:52:44 2021 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(8x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/ssl/lib/engines-1.1"
Seeding source: os-specific
```

**Comment by lightiv** [comment]
The problem is that the error is looking for the lib here:
```/usr/local/ssl/bin/openssl/lib```
which conflicts with the binary openssl  in the same path.  My   lib path is here:
```/usr/local/ssl/lib```

This prevents me from manually creating the directory structure it is looking for.

**Comment by romac** [comment]
Hi!

The `openssl` crate documentation has some information about pointing `openssl-sys` towards your OpenSSL installation: https://docs.rs/openssl/0.10.35/openssl/#manual

In your case, setting the environment variable `OPENSSL_DIR` to `/usr/local/ssl` should likely do it.

I will close this issue already as it's not a problem with Hermes per-se, feel free to re-open it if the problem persists.

Cheers
