### ISSUE TITLE
Call verification functions from outside

### ISSUE THREAD

**Issue by yito88** [informalsystems/ibc-rs#1198]
## Crate
IBC

## Summary
I want to call verification functions for connection and channel without messages handling.

## Problem Definition
They are general functions and can be used not only for handling a message. These verification functions in `connection` and `channel` are private because `ics03_connection::handler::verify` and `ics04_channel::handler::verify` are not public. If they are public, we can use them without messages.

## Proposal
Just insert `pub` for `verify` to `ics03_connection::handler` and `ics04_channel::handler`

## Acceptance Criteria
We can call these verification functions from outside
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hello,
Thanks for opening an issue! We can get this done fast.
It would be good if you could review the PR https://github.com/informalsystems/ibc-rs/pull/1204, even though this is a simple fix.
