### ISSUE TITLE
Hermes Causes Osmosis Sentry to Crash When Accessing gRPC

### ISSUE THREAD

**Issue by lightiv** [informalsystems/ibc-rs#1220]
## Crate

Hermes Relayer

## Summary of Bug

Hermes Causes Osmosis Sentry to Crash When Accessing gRPC.  gRPC is enable by default and the Osmosis Sentry node runs fine BUT when I enable Hermes to access the node it cause it to crash.  I see that a transaction will output a long, long string of data and the node stops reading blocks.

## Version

git version 2.25.1

## Steps to Reproduce

For me, In stall the Osmosis sentry and then configure Hermes to access it.  The problem occurs withing 5 minutes

```
Jul 21 05:35:24 osmosis-sentry-02 cosmovisor[2904]: 5:35AM INF Error reconnecting to peer. Trying again addr={"id":"00c328a33578466c711874ec5ee7ada75951f99a","ip":"35.82.201.64","port":26656} err="auth failure: secret conn failed: read tcp 94.16.108.152:40766->35.82.201.64:26656: i/o timeout" module=p2p tries=4
Jul 21 05:35:25 osmosis-sentry-02 cosmovisor[2904]: 5:35AM INF ABCIQuery data=0A087472616E7366657212096368616E6E656C2D301A0B18FFFFFFFFFFFFFFFFFF01 module=rpc path=/ibc.core.channel.v1.Query/PacketAcknowledgements result={"code":0,"codespace":"","height":"436445","index":"0","info":"","key":null,"log":"","proofOps":null,"value":"CjkKCHRyYW5zZmVyEgljaGFubmVsLTAYASIgCPdVftUYJv4Y2EUSvyTsdQAe268hI6R333KgqfNkCnwKOQoIdHJhbnNmZXISCWNoYW5uZWwtMBgKIiAI91V+1Rgm/hjYRRK/JOx1AB7bryEjpHffcqCp82QKfAo5Cgh0cmFuc2ZlchIJY2hhbm5lbC0wGGQiIAj3VX7VGCb+GNhFEr8k7HUAHtuvISOkd99yoKnzZAp8CjoKCHRyYW5zZmVyEgljaGFubmVsLTAY6AciIAj3VX7VGCb+GNhFEr8k7HUAHtuvISOkd99yoKnzZAp8CjoKCHRyYW5zZmVyEgljaGFubmVsLTAYkE4iIAj3VX7VGCb+GNhFEr8k7HUAHtuvISOkd99yoKnzZAp8CjoKCHRyYW5zZmVyEgljaGFubmVsLTAYkU4iIAj3VX7VGCb+GNhFEr8k7HUAHtuvISOkd99yoKnzZAp8CjoKCHRyYW5zZmVyEgljaGFubmVsLTAYkk4iIAj3VX7VGCb+GNhFEr8k7...........
```
## Acceptance Criteria

Hermes 6 is able to access gRPC for Osmosis witout killing the node

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hello,

Thanks for opening this issue, seems quite critical!

Could you please provide further info, concretely:

- how do you run Hermes? Is it `hermes start`, or some other command?
    - it may be useful to paste somewhere the whole Hermes log file so we can see what might have gone wrong
- can we also see you Hermes config.toml file?

**Comment by jackzampolin** [comment]
I've also experienced this. Requires restart of the node.

**Comment by lightiv** [comment]
I run Hermes using a service that starts it with ```hermes start```

Do you have an e-mail address I can send the log and config.toml file to?

**Comment by andynog** [comment]
> I've also experienced this. Requires restart of the node.

@jackzampolin are you also using cosmovisor to run the node ?

**Comment by ancazamfir** [comment]
gRPC should not crash full nodes so some fix needs to go into abci/SDK for that. 
But we should fix hermes to not give the full node a cause to crash: Not seeing any logs attached here but the little snippet seems to indicate the crash happens on acknowledgment query. Maybe the output is too big. hermes uses `pagination: ibc_proto::cosmos::base::query::pagination::all()` in the request. I guess hermes could limit the number of items in the response by doing multiple requests/ pages.

**Comment by hu55a1n1** [comment]
Hi @lightiv, can you provide an update on this, please? Is this still a problem with the latest release?

**Comment by lightiv** [comment]
Hi Need to update the be lates binary which I will do today and get back with you.  Thanks.

**Comment by lightiv** [comment]
I am running 7.0.1 and gRPC still kills the node which this output being the final gashp.

![IBC_OSMO_Death](https://user-images.githubusercontent.com/36428473/134409439-a0b69521-6f4d-4265-8a84-d9faf108e8e5.PNG)
.

**Comment by lightiv** [comment]
Oh, wait.  By the time I finished the above post the console had timed out and when I reconnected the node was running.  I will let it go for a bit.  The above is Osmosis.  I will try Akash also.

**Comment by romac** [comment]
@lightiv Are you still seeing the same issue with Hermes 0.7.2? Even if we haven't gotten to using pagination yet, this version  should be much lighter load on the nodes now, both at startup and during normal operations.

**Comment by lightiv** [comment]
I have had this running for a couple of hours on the Akash and Osmosis nodes having issues and they have not become unresponsive.  The Akash node is running fine and appears to be keeping up with the current block height.  The Osmosis node is crawling and continually slowing.  It will not be able to get to the current block height.

**Comment by lightiv** [comment]
Oh, sorry need to refresh.  Let me update to v0.7.2 and get back to you.  I am currently on v7.0.1.

**Comment by lightiv** [comment]
I have upgraded to v0.7.3 and I am not having any issues with the Osmosis node crashing.  The problem now is that hermes times out accessing gRPC:
```
Oct 18 03:23:03 hermes[661828]: Oct 18 03:23:03.701 ERROR ThreadId(01) skipped workers for connection connection-13 on chain osmosis-1, reason:
Oct 18 03:23:03 hermes[661828]:    0: relayer error
Oct 18 03:23:03 hermes[661828]:    1: error in underlying transport when making GRPC call
Oct 18 03:23:03 hermes[661828]:    2: transport error: error trying to connect: tcp connect error: Connection timed out (os error 110)
Oct 18 03:23:03 hermes[661828]:    3: error trying to connect: tcp connect error: Connection timed out (os error 110)
Oct 18 03:23:03 hermes[661828]:    4: tcp connect error: Connection timed out (os error 110)
Oct 18 03:23:03 hermes[661828]:    5: Connection timed out (os error 110)
Oct 18 03:23:03 hermes[661828]: Location:
Oct 18 03:23:03 hermes[661828]:    /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.3/src/tracer_impl/eyre.rs:31
```
I have verified that gRPC is accessible externally:
```
grpcurl -plaintext 0.0.0.0:9090 list

cosmos.auth.v1beta1.Query
cosmos.bank.v1beta1.Query
cosmos.base.reflection.v1beta1.ReflectionService
cosmos.base.tendermint.v1beta1.Service
cosmos.distribution.v1beta1.Query
cosmos.evidence.v1beta1.Query
cosmos.gov.v1beta1.Query
cosmos.params.v1beta1.Query
cosmos.slashing.v1beta1.Query
cosmos.staking.v1beta1.Query
cosmos.tx.v1beta1.Service
cosmos.upgrade.v1beta1.Query
grpc.reflection.v1alpha.ServerReflection
ibc.applications.transfer.v1.Query
ibc.core.channel.v1.Query
ibc.core.client.v1.Query
ibc.core.connection.v1.Query
osmosis.claim.v1beta1.Query
osmosis.epochs.v1beta1.Query
osmosis.gamm.v1beta1.Query
osmosis.incentives.Query
osmosis.lockup.Query
osmosis.mint.v1beta1.Query
osmosis.poolincentives.v1beta1.Query
testdata.Query
```

**Comment by lightiv** [comment]
The issues I was having has been resolved by installing everything on one box.  I am now relaying.
