### ISSUE TITLE
Invalid JSON Accessing Akash Node 26657

### ISSUE THREAD

**Issue by lightiv** [informalsystems/ibc-rs#1227]
## Crate

relayer

## Summary of Bug

Jul 22 04:07:34 hermes-ibc-relayer01 hermes[703]: Jul 22 04:07:34.671 ERROR [cosmoshub-4:transfer/channel-97 → akashnet-2] worker: schedule execution encountered error: failed during query to chain id akashnet-2 with underlying error: RPC error to endpoint http://185.207.106.67/:26657/: Parse error. Invalid JSON: expected value at line 1 column 1 (code: -32700) path=packet::channel-97/transfer:cosmoshub-4->akashnet-2

I also get these error from PANIC ALERTER also.  I have tried multiple Akash Sentries with the same error.

Akash Version: v0.12.1

## Version

hermes 0.6.0

## Steps to Reproduce

Configure akashnet-2 in hermes and watch the journalctl output

## Acceptance Criteria

Hermes is able to access Akash RPC without an error.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by lightiv** [comment]
This correlates with Issue  #1221

**Comment by romac** [comment]
Can you try building Hermes from this branch https://github.com/informalsystems/ibc-rs/tree/romac/hermes-log-var and running it with:

```bash
$ HERMES_LOG='tendermint_rpc=debug,ibc_relayer=info' hermes start
```

This should print the raw JSON response we get from the node, and might therefore help diagnose the issue.

```
Aug 03 13:16:27.121 DEBUG Incoming response: {
  "jsonrpc": "2.0",
  "id": "e29a8094-b5bf-472e-9ce5-97b73fb68349",
  "result": {}
}
Aug 03 13:16:27.123 DEBUG Incoming response: {
  "jsonrpc": "2.0",
  "id": "96aae607-6e04-47be-bb0d-e2814673cca8",
  "result": {
    "txs": [],
    "total_count": "0"
  }
}
```

**Comment by adizere** [comment]
Closing as dup of #1221. Will continue debugging & tracking there.
