### ISSUE TITLE
Separate generated code from `prost` and `tonic` in `proto-compiler`

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-rs#1238]
## Crate

`ibc-proto`, `ibc-proto-compiler`

## Summary

This is a follow up on #1164. We want to separate the generated code from `prost` and `tonic`, and put the `tonic` code behind an `std` feature flag. This is so that the generated `prost` code can still be used in no_std mode, as `prost` supports no_std but `tonic` doesn't.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
One awkward solution to have separate code is to generate two sets of files:

1. one set including both prost and tonic (i.e., the same set of file we currently generate in ibc-proto);
2. one set with just prost, without tonic's client- and server-side logic, i.e., by setting `false` to buid_client and build_server

https://github.com/informalsystems/ibc-rs/blob/f9a24edb74808f3be23b087d7a4ce6fc86fe251c/proto-compiler/src/cmd/compile.rs#L106-L107

This solution is sub-optimal but not that difficult to implement.

**Comment by romac** [comment]
`tonic-build` 0.5 can add custom attributes on the Rust modules containing the gRPC code (see https://docs.rs/tonic-https://docs.rs/tonic-build/0.5.2/tonic_build/struct.Builder.html#method.server_mod_attributebuild/0.5.2/tonic_build/struct.Builder.html#method.client_mod_attribute).

So I guess what we could do is:
1. wait for Prost 0.9 and Tonic 0.6
2. add an `std` feature to the `ibc-proto` crate
3. use the aforementioned feature to disable the gRPC code when the `std` feature is disabled
