### ISSUE TITLE
Building Hermes 0.6.1 with Cargo fails on MacOS

### ISSUE THREAD

**Issue by AdityaSripal** [informalsystems/ibc-rs#1251]
Tried to build Hermes on mac with cargo and get the following error:

`error[E0658]: use of unstable library feature 'debug_non_exhaustive'`

Tried both commands:
`cargo install ibc-relayer-cli --bin hermes --locked`

`cargo install ibc-relayer-cli --bin hermes`

Both failed with same error

**Comment by romac** [comment]
Which version of Rust are you on? This feature was stabilized in Rust 1.53.

**Comment by AdityaSripal** [comment]
Hello Yes it now works. Thanks!
