### ISSUE TITLE
Specify channel closing handshake in TLA+

### ISSUE THREAD

**Issue by istoilkovska** [informalsystems/ibc-rs#126]
## Summary

Specify creation and handling of channel closing datagrams in the relayer TLA+ specification.

## Proposal

Add support for channel closing datagrams.

On the chain side:
 - add handlers for processing channel closing handshake datagrams

On the relayer side:
 - define operator for creating  channel closing handshake datagrams

Properties: 
 - ensure that closed channels cannot be reopened

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Please don't forget to cleanup the relayer spec by deleting the [relayer-old](https://github.com/informalsystems/ibc-rs/tree/master/docs/spec/relayer-old) directory, according to this [comment](https://github.com/informalsystems/ibc-rs/pull/117#discussion_r448324773).
