### ISSUE TITLE
gm fails silently when missing dependencies on mac

### ISSUE THREAD

**Issue by haasted** [informalsystems/ibc-rs#1261]
## Crate
Gaiad Manager `gm`

## Summary of Bug

If an external prerequisites is missing when running `gm`, the script will fail silently on mac os x.

## Version

v0.0.6

## Steps to Reproduce

Remove a dependency, e.g. stoml, or change the check in `enforce_requirements` to something nonsensical, e.g. `STOML="$(which stoml12345)" `.

Run `gm`. The informational error messages that are in `enforce_requirements` does not seem to get printed. 

## Acceptance Criteria

Receive a helpful message stating which dependency is missing.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by greg-szabo** [comment]
Nice find @haasted ! The fix is in progress.
