### ISSUE TITLE
`hermes` is not compatible with ethermint

### ISSUE THREAD

**Issue by devashishdxt** [informalsystems/ibc-rs#1267]
## Crate

`relayer`

## Summary

`hermes` is not compatible with https://github.com/tharsis/ethermint

## Problem Definition

- Why do we need this feature?
  To use `hermes` with chains based on `ethermint`.

- What problems may be addressed by introducing this feature?
  `hermes` will no longer be non-compatible with `ethermint`

- Are there any disadvantages of including this feature?
  No

## Proposal

To be able to use `hermes` with `ethermint`, we need two things added in `hermes`:

1. Adding key generation algorithm using `eth-secp256k1` (#1071)
2. Currently, the code in relayer assumes that all the accounts are of type `BaseAccount` ([here](https://github.com/informalsystems/ibc-rs/blob/142c7dc29c7636d1c9ece51ce8fd6f7c50ca3477/relayer/src/chain/cosmos.rs#L1936)). In case of `ethermint`, this account is of type `EthAccount` ([proto](https://github.com/tharsis/ethermint/blob/75b7f56b001d88cb91fc276f35b08cd695a62683/proto/ethermint/types/v1alpha1/account.proto#L12)). This can be done in code by checking `type_url` value of `prost::Any` type returned by `QueryAccountRequest`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by charleenfei** [comment]
🎉 🎉
