### ISSUE TITLE
`create channel` command fails to execute

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#1300]
## Crate
hermes

## Summary of Bug
Since 0.5.0 the `create channel` command fails. It works if I use Hermes 0.4.0.
I tried with gaiad 4.2.1 and several 0.5.x versions.

## Version
0.5.0, 0.6.0, 0.6.1, 0.6.2

## Steps to Reproduce
gm.toml:
```
[chain-1]
  ports_start_at = 27000

[chain-2]
  ports_start_at = 27010

[global]
  gaiad_binary = "/opt/bin/gaiad_5.0.5"
  ports_start_at = 27030

  [global.hermes]
    binary = "/opt/bin/hermes_0.6.0"
```

Hermes config:
```
[global]
strategy = 'packets'
log_level = 'info'

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id='chain-1'
rpc_addr='http://localhost:27000'
grpc_addr='https://localhost:27002'
websocket_addr='ws://localhost:27000/websocket'
rpc_timeout='1s'
account_prefix='cosmos'
key_name='wallet'
store_prefix='ibc'
fee_denom='stake'
fee_amount=1000
gas=500000
clock_drift='5s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='chain-2'
rpc_addr='http://localhost:27010'
grpc_addr='https://localhost:27012'
websocket_addr='ws://localhost:27010/websocket'
rpc_timeout='1s'
account_prefix='cosmos'
key_name='wallet'
store_prefix='ibc'
fee_denom='stake'
fee_amount=1000
gas=500000
clock_drift='5s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'
```

Command ran:
```
"/opt/bin/hermes_0.6.0" create channel chain-1 chain-2 --port-a transfer --port-b transfer

Aug 18 02:12:25.415  INFO using default configuration from '/root/.hermes/config.toml'
Aug 18 02:12:25.425  INFO Creating new clients, new connection, and a new channel with order ORDER_UNORDERED
Aug 18 02:12:25.444 ERROR [chain-2 -> chain-1:07-tendermint-0]  failed CreateClient: error raised while creating client: failed while building client state from src chain (chain-2) with error: GRPC error: transport error: error trying to connect: received corrupt message
Error: error raised while creating client: Create client failed (ClientCreate("failed while building client state from src chain (chain-2) with error: GRPC error: transport error: error trying to connect: received corrupt message"))
```

## Acceptance Criteria
The command finishes without error, as in v0.4.0.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
The config doesn't seem correct.
```
fee_denom='stake'
fee_amount=1000
gas=500000
```
should be something like:
```
max_gas = 500000
gas_price = { price = 0.01, denom = 'stake' }
gas_adjustment = 0.1
```

Also try `127.0.0.1` instead of `localhost`. 
I tried to create channel and clients on different versions and master and it works. CI also should have failed.

**Comment by greg-szabo** [comment]
It was localhost originally, I changed it to 127.0.0.1 to check if name resolution causes it.

The config is the one that worked with 0.4.0 (before the config change). I changed the config for the one you mention for the newer versions.

From: Anca Zamfir ***@***.***>
Reply-To: informalsystems/ibc-rs ***@***.***>
Date: Wednesday, August 18, 2021 at 08:54
To: informalsystems/ibc-rs ***@***.***>
Cc: Greg Szabo ***@***.***>, Author ***@***.***>
Subject: Re: [informalsystems/ibc-rs] `create channel` command fails to execute (#1300)


The config doesn't seem correct.

fee_denom='stake'

fee_amount=1000

gas=500000

should be something like:

max_gas = 500000

gas_price = { price = 0.01, denom = 'stake' }

gas_adjustment = 0.1

Also try 127.0.0.1 instead of localhost.
I tried to create channel and clients on different versions and master and it works. CI also should have failed.

**Comment by ancazamfir** [comment]
`hermes create client chain-1 chain-2` might also give better hints on what is wrong.

**Comment by greg-szabo** [comment]
oh, you're right, I'll do that, thanks. I'll report back.

**Comment by ancazamfir** [comment]
I tried two chains with the hermes config below (just your config with the corrections), gaiad v5.0.5 and hermes v0.6.2. All looks good.
```
[global]
strategy = 'packets'
log_level = 'trace'

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id='chain-1'
rpc_addr='http://127.0.0.1:27000'
grpc_addr='https://127.0.0.1:27002'
websocket_addr='ws://127.0.0.1:27000/websocket'
rpc_timeout='1s'
account_prefix='cosmos'
key_name='wallet'
store_prefix='ibc'
max_gas = 3000000
gas_price = { price = 0.01, denom = 'stake' }
gas_adjustment = 0.1
clock_drift='5s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='chain-2'
rpc_addr='http://127.0.0.1:27010'
grpc_addr='https://127.0.0.1:27012'
websocket_addr='ws://127.0.0.1:27010/websocket'
rpc_timeout='1s'
account_prefix='cosmos'
key_name='wallet'
store_prefix='ibc'
max_gas = 3000000
gas_price = { price = 0.01, denom = 'stake' }
gas_adjustment = 0.1
clock_drift='5s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'
```

**Comment by greg-szabo** [comment]
We did a troubleshooting session with Adi and were able to reproduce some errors with hermes 0.6.2 in an indeterministic way. We could not reproduce any of the errors using hermes 0.7.0

I'm closing this ticket and if I ever come across any more errors with the new hermes versions, I'll open a new one.
