### ISSUE TITLE
`create client` command fails when connecting two blockchains scaffolded with starport

### ISSUE THREAD

**Issue by crodriguezvega** [informalsystems/ibc-rs#1301]
## Crate

hermes

## Summary of Bug

On v0.6.2 the `create client` command fails with `Error: relayer error` when trying to connect two chains scaffolded with `starport` v0.17.1.

## Version

hermes 0.6.2
starport 0.17.1
macOS Big Sur 11.2.3

## Steps to Reproduce

Configuration files used can be found in attached [zip file](https://github.com/informalsystems/ibc-rs/files/7020244/configs.zip).

Install `starport` v0.17.1 (executables can be found [here](https://github.com/tendermint/starport/releases/tag/v0.17.1)).

Run `starport scaffold chain github.com/alice/planet`. This will create a folder called `planet` and scaffold a cosmos blockchain.

Then copy `earth.yaml` and `mars.yaml` in the root of the `planet` folder.

From one terminal window go to `planet` folder and run `starport chain serve -c ./earth.yaml`. Wait for it to finish booting up.

From another terminal window go as well to `planet` folder and run `starport chain serve -c ./mars.yaml`.

Now you should have two blockchains running in parallel.

For hermes, use the `config.toml` file in the zip file.

Run `hermes -c config.toml keys restore earth -n bob -m "alley afraid soup fall idea toss can goose become valve initial strong forward bright dish figure check leopard decide warfare hub unusual join cart"` to restore the keys of bob in earth blockchain.

Run `hermes -c config.toml keys restore mars -n eve -m "record gift you once hip style during joke field prize dust unique length more pencil transfer quit train device arrive energy sort steak upset"` to restore the keys of eve in mars blockchain.

Finally run `hermes -c config.toml create client earth mars`. The output should be just `Error: relayer error`.

## Acceptance Criteria

The command finishes without error and clients are created on both blockchains.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Many thanks Carlos for flagging this! The instructions were very helpful, I was able to reproduce the issue.

The underlying problem is as follows:

> Error:
   0: relayer error
   1: event monitor error
   2: failed to create WebSocket driver for chain mars with address ws://127.0.0.1:26559/websocket

Looking at config.toml, it seems that the ports for the websocket are incorrect. I did the following changes:

```diff
-websocket_addr = 'ws://127.0.0.1:26557/websocket'
+websocket_addr = 'ws://127.0.0.1:26657/websocket' 
...
-websocket_addr = 'ws://127.0.0.1:26559/websocket'
+websocket_addr = 'ws://127.0.0.1:26659/websocket'
```

Note that the `websocket_addr` port is identical to the `rpc_addr` port.

After this modification, creating a client works:

```
Success: CreateClient(
    CreateClient(
        Attributes {
            height: Height {
                revision: 0,
                height: 553,
            },
            client_id: ClientId(
                "07-tendermint-0",
            ),
            client_type: Tendermint,
            consensus_height: Height {
                revision: 0,
                height: 506,
            },
        },
    ),
)
```

Let us know if other problems arise, otherwise please feel free to close this issue!

**Comment by adizere** [comment]
One more remark -- upgrading to Hermes 0.7.0 will provide you with clearer error messages. The fact that you were seeing just `Error: relayer error.` was a problem in itself in Hermes 0.6.2, which we fixed in the meantime.

**Comment by crodriguezvega** [comment]
@adizere Thank you very much for spotting my mistake!

I tried to create the client on both chains with the port change you proposed and v7.0.1, and everything works fine.
