### ISSUE TITLE
configuring clients AllowUpdate bools via config.toml

### ISSUE THREAD

**Issue by damiannolan** [informalsystems/ibc-rs#1320]
## Crate

- relayer
- relayer-cli

## Summary

Is it possible to configure the following boolean fields for clients via hermes config.toml?

```
allow_update_after_expiry
allow_update_after_misbehaviour
```

I don't see an option to enable/disable this functionality via the CLI `hermes create client` either, and currently both bools seemingly default to false (see below).

This would be useful to allow for recovery of clients via gov proposals.

```
Success: ClientState {
    chain_id: ChainId {
        id: "agoricdev-3",
        version: 3,
    },
    trust_level: TrustThreshold {
        numerator: 1,
        denominator: 3,
    },
    trusting_period: 1209600s,
    unbonding_period: 1814400s,
    max_clock_drift: 5s,
    frozen_height: Height {
        revision: 0,
        height: 0,
    },
    latest_height: Height {
        revision: 3,
        height: 489366,
    },
    upgrade_path: [
        "upgrade",
        "upgradedIBCState",
    ],
    allow_update: AllowUpdate {
        after_expiry: false,
        after_misbehaviour: false,
    },
}
``` 
____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hi, thanks for raising this issue!

> Is it possible to configure the following boolean fields for clients via hermes config.toml?

No. At the moment Hermes does not support configuring this fields in any way.

We're considering two approaches to fix this: (1) by making the two fields `true` by default, or (2) by changing `hermes create client` CLI to allow optional CLI parameters for adjusting these two fields.
Approach (1) is simpler and

The CLIs with approach (2) will look something like:

> create client <host-chain-id> <target-chain-id> [--update-after-expiry <true|false>] [--update-after-expiry <true|false>]

**Comment by adizere** [comment]
I checked in current Hermes and it seems that the flags __do__ default to `true` and it's been like that [since 0.3.0](https://github.com/informalsystems/ibc-rs/commit/f993e25924d1be81f16779f6f86eb37c8a3e9951).

https://github.com/informalsystems/ibc-rs/blob/1a0a31bb2d3cdc2cf2335f20bf8a049d09409a28/relayer/src/chain/cosmos.rs#L1713-L1715


@damiannolan can you confirm that the clients you create with Hermes (please use 0.7.0 if possible) have the fields set to `true`? If so, I will close this issue.

**Comment by damiannolan** [comment]
Confirmed v0.7.0 defaults to true, I had been experimenting with multiple binaries as I needed compatibility with an older sdk version so I think this is where I ended up having defaults as false. 

Feel free to close this. Thanks @adizere
