### ISSUE TITLE
Compatibility check doesn't seem to handle non semantic versions properyly, emits a warning

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#1337]
## Crate

ibc-relayer

## Summary of Bug

Hermes might issue a warning when a theoretically valid version (but not semantic version).

## Version

v.0.6.2

## Steps to Reproduce

Running Hermes on a chain that has a version such as `0.42.0-rc0` might trigger this. For example the compatibility list requires `>=0.41.3 and <= 0.42.6`.

`Sep 08 10:30:46.443  WARN Hermes health check failed while verifying the application compatibility for chain regen-1:http://[ip_address]:9090/; caused by: SDK module at version '0.42.0-rc0' does not meet compatibility requirements >=0.41.3, <=0.42.6 for application regen:v1.0.0-1b7c80ef102d3ae7cc40bba3ceccd97a64dadbfd
Sep 08 10:30:46.443  WARN some Hermes features may not work in this mode!`

## Acceptance Criteria

I'm not sure if there's a easy way to check compatibility if chains don't follow a semantic versioning scheme. Since this is a warning it's not a high priority for now. Just reporting it.

____

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
This indeed follows the [semver spec](https://semver.org/spec/v2.0.0-rc.1.html#spec-item-10): (emphasis mine)

> A pre-release version indicates that the version is unstable and **might not** satisfy the intended compatibility requirements as denoted by its associated normal version

Which means that the spec leaves the handling of pre-release version to us. If we feel that's the right to do, I guess we could remove the pre-release version and match against that. What do you think @andynog @adizere?
