### ISSUE TITLE
Header parsing panic kills chain runtime

### ISSUE THREAD

**Issue by Galadrin** [informalsystems/ibc-rs#1342]
## Crate

Hermes ibc_relayer v0.7

## Summary of Bug

When running hermes ibc_relayers between Osmosis and Cosmoshub, packet worker stop after panic.
Log of the error can be found at this link:
https://pastebin.com/uGDZSFjU

config file can be provided if needed.
on gaiad side, no logs exept this line at hermes startup :
```
9:49AM ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":43862,"Zone":""}
9:49AM ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket
```
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Thank you for flagging this issue! We're investigating it and would appreciate if you could share your config.toml file.

**Comment by Galadrin** [comment]
Hi, this is my config for hermes right now 
https://pastebin.com/Pbca30tz
