### ISSUE TITLE
Transaction simulation seems to fail

### ISSUE THREAD

**Issue by mdyring** [informalsystems/ibc-rs#1372]
## Crate

hermes ibc relayer

## Summary of Bug

Possibily related to #1354. We see a large number of the below log entries for both e-money, osmosis and other chains. It seems that simulation fails leading to max gas being used.

```
5:00AM INF ABCIQuery data= module=rpc path=/cosmos.tx.v1beta1.Service/Simulate result={"code":18,"codespace":"sdk","height":"1266720","index":"0","info":"","key":null,"log":"rpc error: code = InvalidArgument desc = invalid empty tx: invalid request","proofOps":null,"value":null}
5:03AM INF ABCIQuery data= module=rpc path=/cosmos.tx.v1beta1.Service/Simulate result={"code":18,"codespace":"sdk","height":"1266734","index":"0","info":"","key":null,"log":"rpc error: code = InvalidArgument desc = invalid empty tx: invalid request","proofOps":null,"value":null}
5:06AM INF ABCIQuery data= module=rpc path=/cosmos.tx.v1beta1.Service/Simulate result={"code":18,"codespace":"sdk","height":"1266747","index":"0","info":"","key":null,"log":"rpc error: code = InvalidArgument desc = invalid empty tx: invalid request","proofOps":null,"value":null}
```

## Version

0.7.1

## Steps to Reproduce

It appears to happen "out of the box".

## Acceptance Criteria

Simulation should not fail and gas should be correctly estimated for transactions to minimise fees.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hi Martin, many thanks for opening this issue! Seems quite critical so we'll dedicate some time to it right away.

Three concerns to help us debug:

1. The error message "desc = invalid empty tx" seems to indicate empty transactions being fed into the /simulate endpoint. I'm not familiar to the log structure you pasted, however, so I might be wrong. Can you confirm that my assumption is correct -- namely that the simulated transactions are empty?
2. Is there __any__ transaction that is __not__ using max bytes?
3. Can we please have the Hermes log, ideally with [`log_level = debug`](https://github.com/informalsystems/ibc-rs/blob/79210ec95f40ecb7aabcc5691c5d3a07ffbef280/config.toml#L23) or `trace`.

**Comment by adizere** [comment]
Potentially related to #1354

**Comment by adizere** [comment]
We were able to confirm this is a dup of 1354. We're working on it as high priority.
