### ISSUE TITLE
Acknowledgements don't seem to be marked as sent

### ISSUE THREAD

**Issue by michaelfig** [informalsystems/ibc-rs#1377]
## Crate

hermes

## Summary of Bug

Sending transfer packets from `cosmoshub-testnet` to `agoricstage-15` don't ever seem to clear the list of acknowledgement packets.  I'm not sure if they're actually being sent or not, the log just seems to indicate a problem.

## Version

0.7.1

## Steps to Reproduce

<details>
<summary>here is Hermes config.toml</summary>

```
[global]
strategy = 'all'
filter = false
log_level = 'trace'
clear_packets_interval = 100

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]                                                               
id = 'agoricstage-15'
rpc_addr = 'http://143.198.36.204:26657'
grpc_addr = 'http://143.198.36.204:9090'
websocket_addr = 'ws://143.198.36.204:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'agoric'
key_name = 'stagekey'
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'urun' }
gas_adjustment = 0.1
clock_drift = '5s'
trusting_period = '14days'                                               

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[[chains]]                                                               
id = 'cosmoshub-testnet'
rpc_addr = 'https://rpc.testnet.cosmos.network:443'
grpc_addr = 'https://grpc.testnet.cosmos.network:443'
websocket_addr = 'wss://rpc.testnet.cosmos.network:443/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'hubkey'
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'uphoton' }
gas_adjustment = 0.1
clock_drift = '5s'
trusting_period = '14days'                                               

[chains.trust_threshold]
numerator = '1'
denominator = '3'
```

</details>

send a transfer packet from `cosmoshub-testnet` to `agoricstage-15`:

<details><summary>note the logs</summary>

```
Sep 21 23:14:08 hermes hermes[78028]: Sep 21 23:14:08.592  INFO [agoricstage-15:transfer/channel-0 -> cosmoshub-testnet] clearing pending packets height=Some(Height { revision: 15, height: 103699 })
Sep 21 23:14:09 hermes hermes[78028]: Sep 21 23:14:09.254 DEBUG [agoricstage-15:transfer/channel-0 -> cosmoshub-testnet] packets that have acknowledgments on agoricstage-15: [Some(1)..Some(10)] (total=10)
Sep 21 23:14:09 hermes hermes[78028]: Sep 21 23:14:09.254 DEBUG [agoricstage-15:transfer/channel-0 -> cosmoshub-testnet] ack packets to send out to cosmoshub-testnet of the ones with acknowledgments on agoricstage-15: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 (first 10 shown here; total=10)
Sep 21 23:14:10 hermes hermes[78028]: Sep 21 23:14:10.082  INFO [agoricstage-15:transfer/channel-0 -> cosmoshub-testnet] found unprocessed WriteAcknowledgement events for [] (first 10 shown here; total=0)
Sep 21 23:14:10 hermes hermes[78028]: Sep 21 23:14:10.082  INFO [agoricstage-15:transfer/channel-0 -> cosmoshub-testnet] finished scheduling pending packets clearing height=Some(Height { revision: 15, height: 103699 })
```

</details>

The above appeared after sending a total of 10 transfer packets.  Each time there was one more `ack packets to send out`.

I've verified that those messages appear to repeat about every 10 minutes.

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
You can check that packets have been received and acknowledged using:
- [hermes query packet unreceived-packets](https://hermes.informal.systems/commands/queries/packet.html#unreceived-packets)
- [hermes query packet unreceived-acks ](https://hermes.informal.systems/commands/queries/packet.html#unreceived-acknowledgments)

With `hermes start`, hermes checks for unrelayed packets every N blocks (configurable, default 100). The logs you show are for acks so you will see this periodically. It does the following:
- queries all sequences that have been acknowledged by the receive side (lines 2 and 3 in your log snippet)
- queries the sender for the sequences from the set above for which `MsgAknowledgment` has not been received (line 4, showing no sequences so there are no pending msgs to be sent).

We should clean a bit the logs though, that `ack packets to send out to cosmoshub-testnet of the ones with acknowledgments...` line in particular is confusing. 
We also brought up an optimization with the SDK team to be able to query the receive side by passing the list of sequences that still have packet commitments on the sender side. Once [this](https://github.com/cosmos/ibc-go/issues/370) is in we should be able to log meaningful information.

**Comment by michaelfig** [comment]
Unreceived acks shows the following (and it's definitely more than 100 blocks since my last acknowledgement):

```
$ hermes query packet unreceived-acks cosmoshub-testnet transfer channel-76
Sep 22 19:14:08.377  INFO using default configuration from '/home/hermes/.hermes/config.toml'
Sep 22 19:14:08.378 DEBUG Options: QueryUnreceivedAcknowledgementCmd { chain_id: ChainId { id: "cosmoshub-testnet", version: 0 }, port_id: PortId("transfer"), channel_id: ChannelId("channel-76") }
Sep 22 19:14:09.666 TRACE [cosmoshub-testnet] subscribing to query: tm.event = 'Tx'
Sep 22 19:14:09.738 TRACE [cosmoshub-testnet] subscribing to query: tm.event = 'NewBlock'
Sep 22 19:14:09.811 TRACE [cosmoshub-testnet] subscribed to all queries
Sep 22 19:14:09.811 DEBUG [cosmoshub-testnet] starting event monitor
Sep 22 19:14:10.627  WARN Health checkup for chain 'agoricstage-15' failed
Sep 22 19:14:10.627  WARN     Reason: 
   0: Hermes health check failed while verifying the application compatibility for chain agoricstage-15:http://143.198.36.204:9090/; caused by: SDK module at version '0.44.0' does not meet compatibility requirements >=0.41.3, <=0.43.0 for application ag-cosmos-server:0.26.18-

Location:
   /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.2/src/tracer_impl/eyre.rs:10

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Sep 22 19:14:10.627  WARN     Some Hermes features may not work in this mode!
Sep 22 19:14:10.925 TRACE [agoricstage-15] subscribing to query: tm.event = 'Tx'
Sep 22 19:14:10.999 TRACE [agoricstage-15] subscribing to query: tm.event = 'NewBlock'
Sep 22 19:14:11.073 TRACE [agoricstage-15] subscribed to all queries
Sep 22 19:14:11.073 DEBUG fetched from source chain cosmoshub-testnet the following channel IdentifiedChannelEnd { port_id: PortId("transfer"), channel_id: ChannelId("channel-76"), channel_end: ChannelEnd { state: Open, ordering: Unordered, remote: Counterparty { port_id: PortId("transfer"), channel_id: Some(ChannelId("channel-0")) }, connection_hops: [ConnectionId("connection-81")], version: "ics20-1" } }
Sep 22 19:14:11.073 DEBUG [agoricstage-15] starting event monitor
Success: [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
]
```

**Comment by ancazamfir** [comment]
How is the access node for `agoricstage-15` configured wrt to tx indexing and pruning? Looks like when we query the Tx-es that include events for those sequence numbers (1-10) none is found.

**Comment by michaelfig** [comment]
> How is the access node for `agoricstage-15` configured wrt to tx indexing and pruning? Looks like when we query the Tx-es that include events for those sequence numbers (1-10) none is found.

Thanks for pointing this out.  I will dig deeper before I blame Hermes again. :smile:

**Comment by adizere** [comment]
ps. The annoying "Hermes health check failed" warning should disappear if you're using 0.7.2.

**Comment by adizere** [comment]
Closing as it was more of a question than an issue.
