### ISSUE TITLE
gm-connector for e2e testing in Rust

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#1412]
## Crate
relayer
gm-connector

## Summary
gm-connector is a Rust library that allows Rust tests to start/stop/manage SDK networks through `gm` (Gaiad Manager).

## Problem Definition
e2e testing in Rust is complex and it has dependencies completely unrelated to Rust (or to the code we oversee): network binaries, configuration, ports, etc.

During developer testing it is possible to contain these dependencies with `gm` Gaiad Manager. `gm` allows the user to describe multiple network nodes and their dependencies on each other in a simple TOML file.

`gm-connector` should allow the developer to do the same in Rust tests either ran locally or in CI. `gm-connector` deals with telling `gm` to start/stop any network nodes as well as it returns endpoints to the developer for RPC, gRPC and other connection types.
Subsequently, `gm-connector` should also allow the developer to read/change the network configuration of each node.

What problems may be addressed by introducing this feature?

e2e testing now uses a lot of different kind of dependencies (Python, network binaries, etc). The relevant dependencies are lowered.

What benefits does IBC-rs stand to gain by including this feature?

Easier e2e testing using Rust native tools.

Are there any disadvantages of including this feature?

Yet another Rust library to maintain. (Fortunately, it is only used in testing.)

## Proposal
Write an initial version of `gm-connector` and see if it resolves dependencies as expected.

## Acceptance Criteria
At least one e2e test can be run successfully without invoking Python.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
After discussing with @soareschen and @greg-szabo, we have concluded that:

- There is no need for `gm-connector`, so we can close this issue;
- `gm` definitely valuable now, and will definitely be needed in the future for developer network setup & manual/complex tests
- `gm` may grab new users in the future (e.g., gaiad or ibc-go team) and then we may consider moving it in its own repo to cover those use-case.
