### ISSUE TITLE
Move ibc-proto source code into ibc-rs

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#142]
## Summary
https://github.com/informalsystems/ibc-proto can be moved into ibc-rs.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
Is this blocking on anything? Should we move it in for v0.0.2?

**Comment by greg-szabo** [comment]
It’s just waiting for me to get to it. We can schedule it into 0.0.2.

________________________________
