### ISSUE TITLE
Invecstigate: why is counterparty proto an Option in Rust?

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#146]
## Summary of Bug
Anca:
I was curious how we ended up with option for the counterparty field? What in the .proto definition (Counterparty counterparty = 5 [(gogoproto.nullable) = false];) makes prost to decide it should be an option?

same for the prefix in counterparty cosmos.ibc.commitment.MerklePrefix prefix = 3 [(gogoproto.nullable) = false];

## Version
ibc-proto 0.1.0

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
This seems to give an answer:

https://github.com/danburkert/prost/blob/fdf9fdf730e2554a6c2bce693f7600e350358c7d/README.md#message-fields

> Message fields are converted to the corresponding struct type. The table of field modifiers above applies to message fields, except that proto3 message fields without a modifier (the default) will be wrapped in an Option. ...

Both the Counterparty as well as the MerklePrefix are `#[prost(message` fields.

**Comment by greg-szabo** [comment]
Seems like this is resolved. Reopen if there are more questions.
