### ISSUE TITLE
query channel given channel id and port id

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#148]
Following the success of #130, we should do the same thing for channels - given a channel id and a port id, fetch the ChannelEnd.

ABCIQuery.Path = `store/ibc/key`
ABCIQuery.Data = `channelEnds/ports/{port identifier}/channels/{channel identifier}`

See [ICS 24](https://github.com/cosmos/ics/tree/master/spec/ics-024-host-requirements#path-space).

Note this query requires both a channel id and port id.

**Comment by adizere** [comment]
This issue is (partially?) covered in Greg's PR #152.

**Comment by greg-szabo** [comment]
Yes, it's partially covered. As soon as #152 is merged, someone can start working on implementing a decent validation. The validation in #152 is only a "happy path" or "example" (no error handling) so the underlying code can work.
