### ISSUE TITLE
query ClientState given client id

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#149]
Given a client id, query the ClientState object.

Note ClientState is an interface, instantiated by the concrete type of client (eg. a Tendermint client). So a real result here will involve Tendermint-specific data structures. 

Note this also doesn't have a protobuf file yet, it's defined as a [Go struct](https://github.com/cosmos/cosmos-sdk/blob/a65bcdd7e551ffc8414f58d85f00d74295a42864/x/ibc/07-tendermint/types/client_state.go#L28). This may be blocking for now (since it means we're dealing with Amino-encoded validators ...)

Opened a related issue on the SDK: https://github.com/cosmos/cosmos-sdk/issues/6736

ABCIQuery.Path = `store/ibc/key`
ABCIQuery.Data = `clients/{identifier}/clientState`

**Comment by ebuchman** [comment]
This is blocked on the SDK upgrading to use the tendermint v0.34 release (currently a Release Candidate), but that should probably happen shortly.

**Comment by ancazamfir** [comment]
Finished after all the protobuf updates, tm releases, #292 and #308.
