### ISSUE TITLE
query ConsensusState given client id and height

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#150]
Given a client id and height, query the ConsensusState. 

This is similar to #149 in that ConsensusState is an interface with concrete implementations depending on the client type (eg. for Tendermint). So it has Tendermint specific data structures. 

This type is simpler than the ClientState, but it also doesn't have a proto file yet. It's defined as a [Go struct.](https://github.com/cosmos/cosmos-sdk/blob/a65bcdd7e551ffc8414f58d85f00d74295a42864/x/ibc/07-tendermint/types/consensus_state.go#L15). Since it contains the validator set, it will depend on Amino for now ...

ABCIQuery.Path = `store/ibc/key`
ABCIQuery.Data = `clients/{identifier}/consensusState/{height}`

**Comment by ebuchman** [comment]
This is blocked on the SDK upgrading to use the tendermint v0.34 release (currently a Release Candidate), but that should probably happen shortly.

**Comment by ancazamfir** [comment]
Finished after all the protobuf updates, tm releases, #292 and #308.
