### ISSUE TITLE
Hermes may use `max_gas` higher than the chain's configured max gas

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#1500]
Many thanks to @mankenavenkatesh for the help in finding and debugging this

## Crate
relayer

## Summary of Bug
If the hermes config `max_gas` is higher than the chain's max gas any transaction using `max_gas` will be silently dropped by the tendermint mempool's post Tx check. This causes the hermes runtime cached account sequence to become invalid. 
The problem is harder to debug when the health check doesn't get to check the chain's consensus parameters because either a (different) check of another chain or previous check for this chain failed. see #1453

## Version
master

## Steps to Reproduce
Configure `max_gas` in hermes higher than the chain's max gas.

## Acceptance Criteria
IMO, even with #1453 fixed, hermes should use the minimum between the configured max gas and the chain's max gas.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Fixed in #1542
