### ISSUE TITLE
query connections given client id

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#151]
Given a client id, query the list of connection identifiers.

This is an easy one that just returns a list of connection identifiers.

ABCIQuery.Path = `store/ibc/key`
ABCIQuery.Data = `clients/{identifier}/connections`

**Comment by greg-szabo** [comment]
#152 changes a lot of the underlying code and gives it the basics but validation is incomplete. There is a todo in the code to finish that.

**Comment by andynog** [comment]
Implemented a good chunk of the logic to query client connections. But got stuck trying to figure out how to parse the result returned by the simapp. If I run simapp (docker version) and do the following command:

`curl 'localhost:26657/abci_query?path="store/ibc/key"&data="clients/clientidone/connections"'`

I get this result:

```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "response": {
      "code": 0,
      "log": "",
      "info": "",
      "index": "0",
      "key": "Y2xpZW50cy9jbGllbnRpZG9uZS9jb25uZWN0aW9ucw==",
      "value": "Chtjb25uZWN0aW9ucy9jb25uZWN0aW9uaWRvbmU=",
      "proof": null,
      "height": "1177",
      "codespace": ""
    }
  }
}
```
and the value decoded is `connections/connectionidone` (the connection identifier). So following the pattern we have to convert the result, I need to create an array of this connections as the response. But in my code I currently have

`let res: Result<ConnectionEnd, Error> = block_on(query(&chain, opts));`

where it should be more like something

`let res: Result<Vec<ConnectionId>, Error> = block_on(query(&chain, opts));`

but then had some issues trying to implement the TryFromRaw trait for this. Need to put a bit more thinking on it. The current implementation compiles but if you run:

```
./target/debug/relayer -c ./relayer/relay/tests/config/fixtures/relayer_conf_example.toml query client connections chain_A ethbridge -h 4 -p false
```

you get an empty response value

```
 Options QueryClientConnectionsOptions { client_id: ClientId("ethbridge"), height: 4, proof: false }
query client connections error Empty response value
```

**Comment by andynog** [comment]
Found a way to parse the client connections response. If you use the command below (with docker simapp running):

``` 
./target/debug/relayer -c ./relayer/relay/tests/config/fixtures/relayer_conf_example.toml query client connections chain_A clientidone -h 4 -p false
```

It shows the client connections:

```
Options QueryClientConnectionsOptions { client_id: ClientId("clientidone"), height: 4, proof: false }
query client connections result:  ["connections/connectionidone"]
```

I think this issue can be closed. The only tweak that might need to do is to migrate a struct I've declared (RawClientConnections) in ics02_client/query.rs that probably should live in ibc-proto crate.
