### ISSUE TITLE
Hermes requires chains use ibc-go >=1.1, <1.2 but ibc-go has already released 1.2.2 

### ISSUE THREAD

**Issue by reuvenpo** [informalsystems/ibc-rs#1548]
## Crate

This one, `ibc-rs`

## Summary of Bug

When starting an instance of `hermes` and connecting to a chain using the latest `ibc-go`, a compatibility error is emitted.

## Version

v0.8.0 (latest) and the pre-release before it. I have not checked earlier versions.

## Steps to Reproduce

- compile a chain with latest `ibc-go`.
- install latest hermes
- start two chains
- connect hermes to both
- create a channel+connection+etc
- start hermes

## Acceptance Criteria

- If this is intended: extend support to more versions of `ibc-go`.
- If this is not intentional: remove the error and allow connecting to chains with `ibc-go` 1.2.*

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hey, thanks for flagging this problem.

Hermes requires some changes to be compatible with ibc-go v1.2. It currently has full support only for ibc-go <v1.2, so we explicitly output a warning when a chain is built with >=ibc-go v1.2. PR https://github.com/informalsystems/ibc-rs/pull/1438 will fix this.
