### ISSUE TITLE
`hermes tx raw` shows all the data bytes in a column

### ISSUE THREAD

**Issue by mpoke** [informalsystems/ibc-rs#1559]
## Summary of Bug

`hermes tx raw ft-transfer` shows all the data bytes in a column, which makes it hard to look at the other attributes. It would be more appropriate to compact the bytes output.

The same issue is with all messages that contain data, e.g., `packet-ack`.

## Version

v0.8.0

## Acceptance Criteria

- [ ] consider fixing via the suggestion in #175 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Thanks for opening this issue! What output format would you think is most appropriate here? Byte vector on a single line, hex, base64, something else?

**Comment by mpoke** [comment]
> Thanks for opening this issue! What output format would you think is most appropriate here? Byte vector on a single line, hex, base64, something else?

I think a byte vector would be better. I guess since it's a tool for testing/dev it's useful to see the data bytes.
