### ISSUE TITLE
Call `delete_packet_commitment` instead of `delete_packet_acknowledgement` after receiving acknowledgement packets

### ISSUE THREAD

**Issue by livelybug** [informalsystems/ibc-rs#1573]
## Crate

modules

## Summary of Bug

After reading the comments in ibc-go: 
[// if packet commitment still exists on the original sending chain, then packet ack has not been received
		// since processing the ack will delete the packet commitment](https://github.com/cosmos/ibc-go/blob/823ef675bbf38a48faa3ba670fb6b8228d58b9fd/modules/core/04-channel/keeper/grpc_query.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L460)

I think the corresponding logic in ibc-rs may need to adjust accordingly:
After receiving acknowledgement packets from the relayer via an unordered channel, the chain should call [delete_packet_commitment](https://github.com/informalsystems/ibc-rs/blob/ac687821bcfb74173d9e637a6e7f972c6c2058d0/modules/src/core/ics04_channel/context.rs#L194), instead of [delete_packet_acknowledgement](https://github.com/informalsystems/ibc-rs/blob/ac687821bcfb74173d9e637a6e7f972c6c2058d0/modules/src/core/ics04_channel/context.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L163)

Otherwise, the `query_unreceived_acknowledgement` is possible to return the ack packets already received. 

## Version

ac687821bcfb74173d9e637a6e7f972c6c2058d0

## Steps to Reproduce

* Start 2 substrate chains chain_a and chain_b;
* Start the Hermes relayer monitoring the 2 chains above;
* chain_a emits a SendPacket event;
* The event is relayed by the relayer to chain_b;
* chain_b emits a WriteAck event;
* The relayer detects the WriteAck event;
* The relayer sends ack packets to chain_a **repeatedly every time it detects a new block event**; 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
Thanks for opening this issue @livelybug! Nice catch! 👌
