### ISSUE TITLE
ICS02/07 - Create and Update Client

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#159]
Re #119. We already have the ICS07 msg types, so we should build out the ICS07 logic for processing those messages.

This can start using an abstract kv store, but it should ultimately leverage #158 

This logic is effectively light client logic from tendermint-rs, so it will likely intersect with ongoing work there.

We should also be thinking about this in the context of https://github.com/informalsystems/tendermint-rs/issues/461 and the ongoing fork detection work.

This task should focus on CreateClient and UpdateClient methods. 
See for example how it is implemented in the Cosmos SDK: 
- https://github.com/cosmos/cosmos-sdk/blob/master/x/ibc/02-client/keeper/client.go

Relevants specs: 
- https://github.com/cosmos/ics/tree/master/spec/ics-002-client-semantics
- https://github.com/cosmos/ics/tree/master/spec/ics-007-tendermint-client

Relevant code in the Cosmos SDK:
- https://github.com/cosmos/cosmos-sdk/tree/master/x/ibc/02-client
- https://github.com/cosmos/cosmos-sdk/tree/master/x/ibc/07-tendermint

**Comment by adizere** [comment]
Relevant discussion for the work on this issue: https://github.com/cosmos/ics/issues/456.

**Comment by ebuchman** [comment]
So I believe a lot of this was done in #197 but some stuff is still stubbed out. We can leave this open for now but @romac when you get back can you make a follow up issue with the specific items left todo

**Comment by ebuchman** [comment]
@romac should we close this?
