### ISSUE TITLE
Rename CLI options ambiguous with clap-provided -h/--help and -V/--version

### ISSUE THREAD

**Issue by mzabaluev** [informalsystems/ibc-rs#1611]
As discussed in #1576, some of the commands use `-h` as a short flag to provide the height parameter, and one command uses `--version` to identify the channel version. This is at odds with the convention used by clap and generally in GNU-like CLI for these names to be reserved for help and version printouts.

This is a breaking change for CLI users, so should not be just slipped in a routine patch release.

- `-h`
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/query/channel.rs#L27
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/query/connection.rs#L28
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/query/packet/ack.rs#L30
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/query/packet/commitment.rs#L37
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/query/client.rs#L33
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/query/client.rs#L175
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/query/channel_ends.rs#L29
   - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/tx/client.rs#L69
- `--version`
  - https://github.com/informalsystems/ibc-rs/blob/c33820497a319779c4de4c52a0f0038298be1722/relayer-cli/src/commands/create/channel.rs#L60

**Comment by adizere** [comment]
For the version problem, we can consider renaming that flag into `channel-version`

**Comment by mzabaluev** [comment]
> we can consider renaming that flag into `channel-version`

Can also soft-rename it by leaving `--version` as an alias until everyone's comfortable with removing the old name.
Did I mention that clap is awesome? :grin:

**Comment by mzabaluev** [comment]
> For the version problem, we can consider renaming that flag into `channel-version`

This is now done as part of #1576.
