### ISSUE TITLE
Crate naming

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#167]
## Summary

I'm confused about the name we give to our modules crate, specifically: 

https://github.com/informalsystems/ibc-rs/blob/6f89b2ddbd16c3b7b77476a0ef0683b5f531fe14/modules/Cargo.toml#L1-L3

As far as I understand it, the modules implementation should not exclusively cover functionality useful for the relayer (but also handlers).

## Proposal

Either `modules` or `ibc-modules` could be a better name.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
This seems to have bveen fixed.

**Comment by adizere** [comment]
I'm not sure. In the master branch, the name of the crate is unchanged:

https://github.com/informalsystems/ibc-rs/blob/9c733d7af1ee7c2dee07086c24f2a94f4d169825/modules/Cargo.toml#L2

**Comment by ebuchman** [comment]
Woops I was looking at the root Cargo.toml
