### ISSUE TITLE
What's the story with `paths-cosmos` and the `cosmos` vs `ics` path modules? 

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#170]
in `modules/src/path.rs`: 

```rust
#[cfg(feature = "paths-cosmos")]
use cosmos as paths;
#[cfg(not(feature = "paths-cosmos"))]
use ics as paths;
```

What's the difference between these? We should clarify in comments at least how to use them and the expectation re how they need to be synchronized ...

**Comment by greg-szabo** [comment]
I asked this from Anca before. The reason was that at one point there were two different and incompatible implementations for this.
They have merged since then and we can remove one. If I recall, we should remove the cosmos one and keep ICS for naming conventions.

**Comment by greg-szabo** [comment]
(As well as the feature from the Cargo.toml)

**Comment by greg-szabo** [comment]
In a follow up issue I'm happy to reorganize paths and introduce a trait for them (I already wanted to do that). The queries need to implement a lot of extra code because of paths and I think we can reduce it.

**Comment by ebuchman** [comment]
Cool thanks. I think there is a Path trait already?

**Comment by ebuchman** [comment]
Actually I wonder if that trait and all those path structs in path.rs even buys us anything? I would think the only purpose of those structs is to call to_string() on them to get the actual path, so why bother with the constructing the structs at all when we could just call the path functions directly?

**Comment by greg-szabo** [comment]
Now you're seeing it. :) My phrasing was not correct but I'm working on that right now.
