### ISSUE TITLE
Use `derive_more` for cleaner Display implementations

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#175]
We could perhaps consider using the [`derive_more`](https://docs.rs/derive_more) crate to make this more readable. Downside is that it pulls in quite a few dependencies, though they are compile-time only. This can be mitigated a bit by only using the [features](https://github.com/JelteF/derive_more/blob/ece3773ef924e5d2691a61797d4d40fdfbfff56b/Cargo.toml#L41-L65) we need.

_Originally posted by @romac in https://github.com/informalsystems/ibc-rs/pull/174#discussion_r461464130_

**Comment by adizere** [comment]
Will take the suggestion here into account when fixing #1559.
