### ISSUE TITLE
Complete ICS20 ft-transfer implementation

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#1759]
## Crate
ibc

## Summary
This is an attempt to gather all requirements for a complete ICS20 implementation. 

## Problem Definition
- [x] #1758 
- [ ] ICS20 Keeper - this would require access to an `AccountReader/Keeper` and a `BankReader/Keeper`, similar to the ibc-go's `Keeper` (see https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/keeper.go) ->
```go
type Keeper struct {
        // ...
	ics4Wrapper   types.ICS4Wrapper
	channelKeeper types.ChannelKeeper
	portKeeper    types.PortKeeper
	authKeeper    types.AccountKeeper
	bankKeeper    types.BankKeeper
}
```
The `Keeper` must additionally provide helper methods for port-binding, denom-traces, etc.
- [ ] ICS26 callbacks (See https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/ibc_module.go)
- [ ] Relay code (See https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/keeper/relay.go)

## Proposal
I propose we design an API that doesn't make assumptions on the SDK stack. A detailed proposal can be discussed via a draft PR. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Wizdave97** [comment]
@hu55a1n1  @adizere  put up a draft PR for the ICS 20 Keeper, please give a review https://github.com/informalsystems/ibc-rs/pull/1884
