### ISSUE TITLE
Update MSRV to Rust 1.58

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#1765]
# Update to Rust release 1.58

[🦀 Blog post](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html)

- [x] Update the version in `rust-toolchain.toml`.
- [x] Run `cargo clippy --all-features --all-targets --fix`, review and commit the automatic fixes, and fix all reported lints. Try to resolve the root causes for the lints rather than silencing them with `#[allow(...)]`.

## Update the MSRV

Additional steps to perform in order to make the new minimal supported Rust version:

- [x] Update the `rust-version` fields in all `Cargo.toml` files.
- [x] Update the `msrv` field in `clippy.toml` and fix all lints reported by `cargo clippy --all-features --all-targets`.
- [x] Update the MSRV shields in README files:
  - `README.md`
  - `relayer-rest/README.md`
- [x] Update the MSRV in the guide: `guide/src/pre_requisites.md`
- [x] Add a `.changelog` entry to the `breaking-changes` section, announcing the new MSRV.

**Comment by lightyear15** [comment]
Uff...
it's hard to keep up with you guys...
I am spending more time updating my toolchain and IDE than actually developing code :sweat_smile:
