### ISSUE TITLE
Investigate async traits

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#177]
Not very important right now, but just pointing out that async methods are somewhat supported on stable Rust via the [`async-trait`](https://docs.rs/async-trait) crate. This crate sometimes yield weird compile-time errors and incurs a [boxing of the returned `Future`](https://docs.rs/async-trait/0.1.36/async_trait/#explanation) but has otherwise worked pretty well for us in the past.

_Originally posted by @romac in https://github.com/informalsystems/ibc-rs/pull/174#discussion_r461459878_

**Comment by romac** [comment]
We already use the `async-trait` crate in many places in tendermint-rs and in ibc-rs. I think we can close this as it's worked pretty well for us so far.
