### ISSUE TITLE
Hermes is blocking on resolving trust height

### ISSUE THREAD

**Issue by Galadrin** [informalsystems/ibc-rs#1774]
## Crate

Hermes release v0.9.0  and release v0.10.0

## Summary of Bug

During operation, Hermes is blocking for a while on this line :
`WARN ThreadId(76) [osmosis-1 -> cosmoshub-4:07-tendermint-259] resolving trusted height from the full list of consensus state heights for target height 1-2806606; this may take a while`

This line happen very often ( a grep on the last our of logs give 31 lines of log matching "this may take a while")
![image](https://user-images.githubusercontent.com/5019960/149619396-0d9215aa-f6ad-48a4-8cf3-da877018ade8.png)

Nothing is logged around this line.

I submit my observation in a discussion with @adizere on january
He ask me to provide some lines of log above :
```
2022-01-08T09:51:56.563308Z  INFO ThreadId(227) [cosmoshub-4:transfer/channel-141 -> osmosis-1] relay op. data of 1 msgs(s) to Destination (height 4-8991080), delayed by: 319.98345ms [try 1/5]
2022-01-08T09:51:56.563348Z  INFO ThreadId(227) [cosmoshub-4:transfer/channel-141 -> osmosis-1] prepending Destination client update @ height 4-8991080
2022-01-08T09:51:56.572633Z  WARN ThreadId(227) [cosmoshub-4 -> osmosis-1:07-tendermint-1] resolving trusted height from the full list of consensus state heights for target height 4-8991080; this may take a while
```

## Version

This issue happen with both v0.9.0 and v0.10.0

## Steps to Reproduce

N/A

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Looking at the log lines you provided

> 2022-01-08T09:51:56.563308Z  INFO ThreadId(227) [cosmoshub-4:transfer/channel-141 -> osmosis-1] relay op. data of 1 msgs(s) to Destination (height 4-8991080), delayed by: 319.98345ms [try 1/5]
2022-01-08T09:51:56.563348Z  INFO ThreadId(227) [cosmoshub-4:transfer/channel-141 -> osmosis-1] prepending Destination client update @ height 4-8991080
2022-01-08T09:51:56.572633Z  WARN ThreadId(227) [cosmoshub-4 -> osmosis-1:07-tendermint-1] resolving trusted height from the full list of consensus state heights for target height 4-8991080; this may take a while

and at the code:

https://github.com/informalsystems/ibc-rs/blob/2757031e029c5456f7cfe483bcca0e34ba2d5ef4/relayer/src/foreign_client.rs#L648-L654


It seems like Hermes is entering a corner-case here where the latest height of the client `07-tendermint-1` on `osmosis-1` is higher than `4-8991080`. In other words, this client was updated with a header newer than `4-8991080`. This can happen for various reasons, but it mostly boils down to another (concurrent) Hermes instance having updated this client while the current relayer instance was still generating and assembling messages. It is weird, however, that this happens over and over again.

Some questions to help us debug/solve:

- Is it possible that your full node is struggling to keep up with the network?
- Are you running with [`misbehavior = true`](https://github.com/informalsystems/ibc-rs/blob/9edf729331fcce73473f9277373ddab8df00189c/config.toml#L24)?  If so, consider setting that to `false`.
- Would you be willing to run from a dev branch?
    - I prepared this branch for you, having a tweak that may alleviate the problem: https://github.com/informalsystems/ibc-rs/tree/adi/1774_trial
    - The fix is not ideal (it impacts the correctness of misbehavior detection) but I'm curious if it helps so let us know how the logs look like.

**Comment by Galadrin** [comment]
> * Is it possible that your full node is struggling to keep up with the network?
Yes, it's totally possible, and can be the early sign of the issue we have this weekend.
Our relayer infra stop relaying claiming for "already handled" packets.
Reseting the node with state-sync resolved our issue.

> * Are you running with [`misbehavior = true`](https://github.com/informalsystems/ibc-rs/blob/9edf729331fcce73473f9277373ddab8df00189c/config.toml#L24)?  If so, consider setting that to `false`.

```
[mode.clients]
enabled = true
refresh = true
misbehaviour = false
```

> * Would you be willing to run from a dev branch?
  
>   * I prepared this branch for you, having a tweak that may alleviate the problem: https://github.com/informalsystems/ibc-rs/tree/adi/1774_trial
>   * The fix is not ideal (it impacts the correctness of misbehavior detection) but I'm curious if it helps so let us know how the logs look like.

I will try it. the issue seems to be less present since we resync the node. (93 match in 24h on "this may take a while")

**Comment by adizere** [comment]
Closing as this was resolved by a more careful state-sync of the node, so it's unlikely a bug in Hermes. Will reopen in case the symptoms appear again.
