### ISSUE TITLE
Client update based on Beefy protocol

### ISSUE THREAD

**Issue by livelybug** [informalsystems/ibc-rs#1775]
In Beefy protocol, there's one data structure, MMR root, "one level higher" than block header. The MMR root of chainA is generated and broadcasted once every N new blocks are generated. After `ChainA`'s light client on `ChainB` receives a tx containing a new MMR root, it will verify the MMR root, and then verify any of the N headers based on the verified MMR root asynchronously. 

From the architectural perspective, is it a good idea to do the 2 asynchronous verifications in the existing function [check_header_and_update_state](https://github.com/octopus-network/ibc-rs/blob/b98094a57620d0b3d9f8d2caced09abfc14ab00f/modules/src/ics02_client/client_def.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L174)?

Kindly reply if any comments.  thank you.

**Comment by livelybug** [comment]
> In Beefy protocol, there's one data structure, MMR root, "one level higher" than block header. The MMR root of chainA is generated and broadcasted once every N new blocks are generated. After CahinA's light client on chainB receives a tx containing a new MMR root, it will verify the MMR root, and then verify any of the N headers based on the verified MMR root asynchronously.
> 
> From the architectural perspective, is it a good idea to do the 2 asynchronous verifications in the existing function [check_header_and_update_state](https://github.com/octopus-network/ibc-rs/blob/b98094a57620d0b3d9f8d2caced09abfc14ab00f/modules/src/ics02_client/client_def.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L174)?
> 
> Kindly reply if any comments. thank you.

@andynog This is a possible architectural change integrating Beefy light client to substrate-ibc.

**Comment by adizere** [comment]
I'm not sure what you mean by "asynchronous". In general, all verification methods should be called synchronously, whenever the IBC module is processing a transaction containing a client update message.

Can you expand or detail on the sequence of actions you have in mind?

**Comment by livelybug** [comment]
Let me try to describe more about the "asynchronous", which may not be accurate under this scenario:
* Under Grandpa consensus, a Relayer submits an update client tx to ChainB after receiving an `IbcEvent::NewBlock` event from ChainA. ChainB will be able to verify the header in the update client tx immediately via function `check_header_and_update_state`. Then any tx belonging to the same header can also be verified by ChainB accordingly. 
* After applying Beefy protocol, ChainB cannot verify the header immediately after receiving, as ChainB may not have verified the MMR root the header belongs to. 

    Which header belongs to which MMR root? The relayer receives [MMR root](https://github.com/octopus-network/substrate/blob/3d73e0625a97c49e2f9d4c0ddbafad6455ff5ff7/primitives/beefy/src/commitment.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L37) via subscription [subscribeJustifications](https://polkadot.js.org/docs/substrate/rpc/#generateproofleafindex-u64-at-blockhash-mmrleafproof). Let's say the message containing an MMR root is pushed to the relayer every 8 blocks, then headers of block height 1-8 can be verified/belong to the MMR root of [block number](https://github.com/octopus-network/substrate/blob/3d73e0625a97c49e2f9d4c0ddbafad6455ff5ff7/primitives/beefy/src/commitment.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48) 8; headers of block height 1-16 can be verified/belong to the MMR root of block number 16; headers of block height 1-24 can be verified / belong to the MMR root of block number 24; ...       

* Therefore, under Beefy protocol, a header's verification may have to "wait" until the corresponding MMR root is verified. The "wait" makes "asynchronous".

**Comment by livelybug** [comment]
A temporary solution for this issue:
* The relayer subscribes to MMR root events, prepares MMR proof,  and submits the proof to the Substrate chain, similar to [this function](https://github.com/octopus-network/octopusxt/blob/3aebe15fb68871587672beba912367645b2ec03f/src/update_client_state.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L191)
* A function in Substrate-Ibc pallet [receives the submission above, verify the MMR root, and updates the client state](https://github.com/octopus-network/substrate-ibc/blob/1f6bdb98d9eedc10e839f1db0d5a1200fef3af11/src/lib.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1025). The function will be integrated into [the ibc-rs modules](https://github.com/informalsystems/ibc-rs/tree/master/modules) eventually.

**Comment by Wizdave97** [comment]
@adizere the refactor of `checkHeaderAndUpdateState` being discussed here should be the same as the `02-client-refactor` in `ibc-go` here https://github.com/cosmos/ibc-go/blob/02-client-refactor/modules/light-clients/07-tendermint/types/update.go.

**Comment by hu55a1n1** [comment]
@livelybug can you confirm that the refactoring in PR #2284 (specifically to the [`ClientDef::check_header_and_update_state()` method here](https://github.com/informalsystems/ibc-rs/pull/2284/files#diff-4e82ff47b3f9fd113d5c3f25bf46cfaee2e969ebbc290328f65874108b8be676L31) as mentioned by @Wizdave97 above) addresses this issue?

**Comment by DaviRain-Su** [comment]
> @adizere the refactor of `checkHeaderAndUpdateState` being discussed here should be the same as the `02-client-refactor` in `ibc-go` here https://github.com/cosmos/ibc-go/blob/02-client-refactor/modules/light-clients/07-tendermint/types/update.go.
> 
> The `checkHeaderAndUpdateState` needs to be refactored into component functions as done in ibc-go linked above, because of the reasons mentioned above.
this link is break down.

**Comment by hu55a1n1** [comment]
@DaviRain-Su, that branch has been deleted and superseded by the `updated-02-client-refactor` branch. I believe the refactoring being referred to is in this PR -> https://github.com/cosmos/ibc-go/pull/1871, you will find the diff for [modules/light-clients/07-tendermint/types/update.go](https://github.com/cosmos/ibc-go/blob/02-client-refactor/modules/light-clients/07-tendermint/types/update.go) there. The PR has since been merged and the branch deleted.

**Comment by livelybug** [comment]
The MMR root update service is integrated into this [branch](https://github.com/octopus-network/ibc-rs/tree/dev)
