### ISSUE TITLE
Hermes ignores IBC events emitted by `BeginBlock`/`EndBlock`

### ISSUE THREAD

**Issue by michaelfig** [informalsystems/ibc-rs#1793]
## Crate

`relayer::event`

## Summary of Bug

`get_all_events` doesn't return IBC events that are raised in `BeginBlock` or `EndBlock`, only transactions.  This prevents `ChannelOpenInit` from within `EndBlock`, which is what Agoric needs for dynamic (smart-contract driven) IBC.

## Version

v0.10.0

## Steps to Reproduce

1. Modify your chain to do the following in EndBlock:
```go
	ctx.EventManager().EmitEvents(sdk.Events{
		sdk.NewEvent(
			sdk.EventTypeMessage,
			sdk.NewAttribute(sdk.AttributeKeyModule, channeltypes.AttributeValueCategory),
		),
	})
```
2. Run `hermes listen mychain`
3. Note that the `message.module = 'ibc_channel'` event is not detected by Hermes

## Acceptance Criteria

`hermes listen mychain` reports events emitted in EndBlock.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
This seems either a regression of https://github.com/informalsystems/ibc-rs/pull/1409 (or we need to extend that work to cover additional types of packets beyond `SendPacket`).

**Comment by michaelfig** [comment]
https://github.com/agoric-labs/cosmos-sdk/tree/mfig-endblock-ibc-event has a hack to raise `message.module = 'ibc_channel'` in `EndBlock`.

To reproduce this problem, you can do:

```
git clone https://github.com/agoric-labs/cosmos-sdk -b mfig-endblock-ibc-event
cd cosmos-sdk
make build
./build/simd --help
```

Simd is then a Cosmos SDK chain that will produce those events on every block.

**Comment by ancazamfir** [comment]
Just to double check, does `hermes` config file include:
```
[mode.channels]
enabled = true
```

**Comment by michaelfig** [comment]
> Just to double check, does `hermes` config file include:

Yes, I was able to reproduce both with and without the config you mentioned.

**Comment by hu55a1n1** [comment]
Hi @michaelfig, can you please confirm if this issue is fixed by #1801?

**Comment by michaelfig** [comment]
> can you please confirm if this issue is fixed by #1801?

Hi @hu55a1n1 ,

After further testing, I find that in the code as of #1801, Hermes doesn't detect newly-created `EndBlock` events, only ones that happened before Hermes started. So, I have to restart Hermes to get it to process the newly-sent events.

Is there any chance it's related to this issue, or should I file a separate one?

**Comment by michaelfig** [comment]
Oh, probably my mistake!  I had been testing #1840, and didn't look too closely at it.  Turns out #1801 was not included in it.

I'm now testing them both together.

**Comment by michaelfig** [comment]
> I'm now testing them both together.

And I've verified that this current issue is fixed and should remain closed, but I see a potentially-related problem in #1844.
