### ISSUE TITLE
Release ibc-rs v0.11.0

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1798]
# Release IBC-RS v0.11.0

⚡

- [ ] Add guide documentation/example for using autocompletion, ref: #1789 

The usual TODOs:
- [ ] Create a new release in the changelog, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Bump all crate versions to the new version.
- [ ] Reassign unfinished issues of previous milestone to the next milestone.
- [ ] Update Cargo.lock file (if re-publishing `ibc-relayer-cli`)

**Comment by rnbguy** [comment]
To prepare a autocompletion guide, you can refer to the help message produced from `rustup completions`.

I maintain [`hermes-relayer`](https://aur.archlinux.org/packages/hermes-relayer-bin) for ArchLinux. I will package `v0.11.0` following [`rustup`'s PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/rustup/trunk/PKGBUILD).
