### ISSUE TITLE
Upgrade all crates to at least version 0.1.0

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#181]
## Summary of Bug
Most of our crates are on v0.0.1 currently. `Config.toml` has the option to cut the last or last two segments of the version for compatibility and tracking version dependency. (For example: use version `0.1` or version `0.1.1`. The first case will use the latest 0.1 version.)

We should give the option to our developers to do compatible upgrades. Our first published crate should be at least 0.1.0.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by greg-szabo** [comment]
Based on today's discussion, we'll revisit this when we are ready to share our code on crates.io with external developers. Internal releases with 0.0. will stick around until then to get us into the habit of regular releases.

**Comment by adizere** [comment]
With the upcoming [`v0`](https://github.com/informalsystems/ibc-rs/milestone/7) release, we'll aim to publish all three crates aligned at v0.1.0.
