### ISSUE TITLE
Retire the `mode.packets.filter` option from the configuration

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1817]
Let's deprecate the mode.packets `filter` option.

_Originally posted by @adizere in https://github.com/informalsystems/ibc-rs/issues/1814#issuecomment-1022157289_

**Comment by romac** [comment]
What should we do about the 2nd type of filter that is currently enabled when `mode.packets.filter = true`, namely:

> # 2. Filter for all activities based on client state trust threshold; this filter
> #   is parametrized with (numerator = 1, denominator = 3), so that clients with
> #   thresholds different than this will be ignored.

I would suggest we always enable it, and revisit this once we start working on a policy language, what do you think?

**Comment by adizere** [comment]
> I would suggest we always enable it, and revisit this once we start working on a policy language, what do you think?

Agree!

**Comment by adizere** [comment]
Closed by #1819
