### ISSUE TITLE
Add CONTRIBUTING.md and update CHANGELOG.md

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#182]
## Summary
Check out tendermint-rs CONTRIBUTING.md and implement it in this repo.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
Done in #190
