### ISSUE TITLE
Clean up unhelpful extra folder names in crate libs

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#186]
## Summary

The modules crate's exported features are in an unnecessary long path.

For example in the CLI acceptance.rs file, here's how module components are imported:
```
use relayer_modules::ics03_connection::connection::ConnectionEnd;
use relayer_modules::ics03_connection::exported::Connection;
use relayer_modules::ics03_connection::exported::State as ConnectionState;
use relayer_modules::ics04_channel::channel::ChannelEnd;
use relayer_modules::ics04_channel::exported::Channel;
use relayer_modules::ics04_channel::exported::Order;
use relayer_modules::ics04_channel::exported::State as ChannelState;
use relayer_modules::ics23_commitment::CommitmentPrefix;
use relayer_modules::ics24_host::identifier::{ChannelId, ClientId, ConnectionId, PortId};
use relayer_modules::ics24_host::Path::{ChannelEnds, ClientConnections, Connections};
```

### Proposal:
Remove the extra path where unnecessary, like `exported`, `connection`, etc.

For example, updated list:
```
use relayer_modules::ics03_connection::ConnectionEnd;
use relayer_modules::ics03_connection::Connection;
use relayer_modules::ics03_connection::State as ConnectionState;
use relayer_modules::ics04_channel::ChannelEnd;
use relayer_modules::ics04_channel::Channel;
use relayer_modules::ics04_channel::Order;
use relayer_modules::ics04_channel::State as ChannelState;
use relayer_modules::ics23_commitment::CommitmentPrefix;
use relayer_modules::ics24_host::{ChannelId, ClientId, ConnectionId, PortId};
use relayer_modules::ics24_host::Path::{ChannelEnds, ClientConnections, Connections};
```
(Makes easier to couple them too.)

To do this, the `mod.rs` file has to be updated. For example, instead of
```
pub mod connection;
```
it will read:
```
mod connection;
pub use connection::ConnectionEnd;
```

It's a bit of extra work for us since all published components need to be listed in the `mod.rs` file (unless there's some globbing option I'm not aware of), but it's beneficial for the developers: it reads more easily.

Please comment your opinions here. This is an opinionated idea, we may or may not want to do it.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
This is similar to what you did with `ibc-proto`. That was confusing to me initially, but I like the idea. Just a remark: This modification on its own can be confusing to newcomers. Specifically it is not intuitive what this trick achieves just by just reading `mod.rs`:

```
mod connection;
pub use connection::ConnectionEnd;
```

So I suggest at least a little comment in `mod.rs` to explain what's happening 

The `exported` module brings up a related problem I believe. Parts of this module (and its intended functionality) may be unnecessary and we can remove it, but perhaps let's double check with @ancazamfir for confirmation. (Note that I [removed](https://github.com/informalsystems/ibc-rs/commit/c799254c60138db4131de148c0375014fcd7d4ae#diff-0eb9b3af2e4a00837a1b1a854c9ea18c) parts of the ICS03 `exported` module already in separate work.)

**Comment by ancazamfir** [comment]
> The exported module brings up a related problem I believe. Parts of this module (and its intended functionality) may be unnecessary and we can remove it..

yes, we should remove the traits from the `exported.rs` files (in both connection and channel folders).

**Comment by romac** [comment]
The `exported` namespace is not a thing anymore.
