### ISSUE TITLE
`max_expected_time_per_block` in `ChannelReader` returns `Result`

### ISSUE THREAD

**Issue by yito88** [informalsystems/ibc-rs#1864]
## Crate
`ibc`

## Summary
`max_expected_time_per_block` should return `Result<u64, Ics04Error>` in `ChannelReader`

## Problem Definition
Getting the parameter could fail in some implementation

## Proposal
`max_expected_time_per_block` and `block_delay` return `Result`

```rust
    /// Returns the maximum expected time per block
    fn max_expected_time_per_block(&self) -> Result<Duration, Error>;

    fn block_delay(&self, delay_period_time: Duration) -> Result<u64, Error> {
        let expected_time_per_block = self.max_expected_time_per_block()?;
        ...
```

## Acceptance Criteria
`max_expected_time_per_block` and `block_delay` return `Result`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Can you please explain further why this method would possibly fail on some implementations? Would it be possible for the implementation to return a default/made-up value in cases where we cannot return a max_expected_time_per_block?

**Comment by yito88** [comment]
Thank you for the question.
It happens in our case where the parameter is stored into the persistent storage and the read failed due to IO failure.
It's possible to return a default value. However, other reader's functions can return `Result` for the read failure with `implementation_specific` error. That's why the function should returns `Result` as other functions.

**Comment by hu55a1n1** [comment]
I think our expectation with `max_expected_time_per_block` was that it was a user-defined constant that would be part of the binary or read from a config file on startup. That is the reason reading it cannot fail. (IIUC, this is also [how ibc-go implements it](https://github.com/cosmos/ibc-go/blob/c27d5b5f26b55d07489cc02fd0b8ce9fa8218e9a/modules/core/03-connection/keeper/params.go#L10).)

**Comment by yito88** [comment]
I understand that. We should return the default value in cases where some failure happens.
Thanks!
