### ISSUE TITLE
Support for CosmWasm in ibc-proto

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1869]
Supporting cosmwasm environment for ibc-proto

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Sorry, didn't see there was already an issue for this. Closing in favor of #1913 (for which I've already added a changelog entry in #1914).
