### ISSUE TITLE
error in parsing config.toml : same config file cannot be used on upgrade from version 1.10.0 to version 1.11.1 

### ISSUE THREAD

**Issue by rmadrona** [informalsystems/ibc-rs#1911]
## Crate

ibc-relayer
## Summary of Bug

I am relaying gravity-bridge-3 chain to osmosis using a filter on channel.
working ok with version  hermes --version hermes 0.10.0+7cf3541
I noticed this version had memory leak issue as it was using 15GB virtual memory
I installed latest version hermes version hermes 0.11.1+e16d5f6
Errors in the log when restarting : The Hermes configuration file at path '/home/gravity/.hermes/config.toml' is invalid, reason: parse error: unknown field `filter`, expected one of `enabled`, `clear_interval`, `clear_on_start`, `tx_confirmation` for key `mode.packets` at line 249 column 1
## Version
hermes version hermes 0.11.1+e16d5f6

 md5sum hermes 
fcc7483a0c1103a97ca08bd4a6b754b0  hermes

## Steps to Reproduce
Setup a communication channel with a packet_filter option.
This option is not valid.

228 [[chains]]
229 id = 'gravity-bridge-3'
230 rpc_addr = 'http://x.x.x.x:26657'
231 grpc_addr = 'http://y.y.y.y:9090'
232 websocket_addr = 'ws://z.z.z.z/websocket'
233 rpc_timeout = '10s'
234 account_prefix = 'gravity'
235 key_name = 'gbkey'
236 store_prefix = 'ibc'
237 default_gas = 100000
238 max_gas = 6000000
239 gas_price = { price = 0.000, denom = 'ugraviton' }
240 gas_adjustment = 0.8
241 max_msg_num = 30
242 max_tx_size = 2097152
243 clock_drift = '5s'
244 max_block_time = '10s'
245 trusting_period = '14days'
246 trust_threshold = { numerator = '1', denominator = '3' }
247 address_type = { derivation = 'cosmos' }
248 
249 [chains.packet_filter]
250 policy = 'allow'
251 list = [
252    ['transfer', 'channel-10'],
253  ]

install hermes 1.11.1 on a system running 1.10.0 with a config file including packet_filter
sudo systemctl restart hermes

## Acceptance Criteria

Documentation still refers to 
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-10'],
]

Option packet_filter accepted or documentation fixed accordingly
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Hermes tries to follow the [semver specification](https://semver.org) as best as possible, and as we are not at version 1.0 yet, the semver specification [allows any kind of breaking changes between any minor or patch version](https://semver.org/#spec-item-4). We try to keep breaking changes for minor version updates, eg. v0.10.0 to v0.11.0 and only release backward-compatible patch versions, eg. v0.11.0 to v0.11.1.

The error you are running into stems from the `mode.packets.filter` option having been removed in v0.11.0, [as documented in the changelog](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md#note-for-operators).

You can simply remove the `mode.packets.filter` option, as per the changelog linked above, and Hermes should resume normal operations :)

**Comment by romac** [comment]
Just to be clear, the `chains.packet_filter` option you have above in your configuration file is still perfectly valid with Hermes v0.11.x :)

**Comment by rmadrona** [comment]
Thanks for your prompt answer.
I was refering to current https://github.com/informalsystems/ibc-rs/blob/master/config.toml which still reference this filteri option.
I will follow the doc you mentionned for the upgrade and get back if needed.
Regards,

**Comment by romac** [comment]
I am sorry but I don't see a `mode.packets.filter` option nor any reference to it in the config: https://github.com/informalsystems/ibc-rs/blob/master/config.toml#L38-L59

**Comment by romac** [comment]
As I said above, the `chains.packet_filter` option is still perfectly valid. All you need to do is remove the `filter = true` setting under the `[mode.packets]` section, as documented in the changelog

**Comment by rmadrona** [comment]
It is clear now. 
Just commented out this line fixed my issue, as it is remove in template config.toml
filter = true
Thanks for your patience, I will read change logs when it is time for next upgrade.

**Comment by romac** [comment]
No problem! :)
