### ISSUE TITLE
Confusing command line options parsing and error

### ISSUE THREAD

**Issue by jtremback** [informalsystems/ibc-rs#1935]
## Crate

Not sure, using Hermes binary

## Summary of Bug

There are two possible places to put options in a call to hermes on the command line. One is directly after the word `hermes`, and one is after the subcommand, i.e. `keys restore` in this example: `hermes keys restore [OPTIONS] --mnemonic <MNEMONIC> <CHAIN_ID>`

First of all, IMO this is confusing. But that's just my opinion. Worse is that the documentation doesn't identify the first possible arguments position, and doesn't identify which arguments go where:

```
USAGE:
    hermes create channel <OPTIONS>

DESCRIPTION:
    Create a new channel between two chains

POSITIONAL ARGUMENTS:
    chain_a_id                identifier of the side `a` chain for the new channel
    chain_b_id                identifier of the side `b` chain for the new channel (optional)

FLAGS:
    -c, --connection-a CONNECTION-A
    --port-a PORT-A           identifier of the side `a` port for the new channel
    --port-b PORT-B           identifier of the side `b` port for the new channel
    -o, --order ORDER         the channel ordering, valid options 'unordered' (default) and 'ordered'
    -v, --channel-version VERSION     the version for the new channel
```
____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by mzabaluev** [comment]
The command implementations follow the CLI conventions as implemented by [clap](https://docs.rs/clap/latest/clap/).

There is a twist, though: there are global flags applicable to all commands, `--config` and `--json`, and these in current implementation must precede any subcommand words. I have checked whether it's possible to make them global options which can be recognized at any subcommand depth, but it does not seem to be easy with the structural approach using the `derive` macro.

All other flags, including ones taking an argument, follow the complete subcommand "path" and can be mixed with positional arguments in arbitrary order, except after `--` which can only be followed by positional arguments.

One general way to reduce confusion would be to get rid of positional arguments in commands where currently their number and order is not mnemonically obvious, converting them to named flags.

**Comment by adizere** [comment]
Thanks for flagging this Jehan, I also got confused a few times by the implicit ordering of options.

Given Mikhail's preliminary findings, seems there is no obvious way for us to fix this problem without changing the underlying CLI framework we're using, which is a very complex change.

Will move this in the Backlog but keep it open as a valuable feedback for now.
