### ISSUE TITLE
Remove WARN logging level for missing chain id in configuration file

### ISSUE THREAD

**Issue by karzak** [informalsystems/ibc-rs#1936]
## Crate

`relayer`

## Summary

When running hermes, I don't see why `missing chain for id ({}) in configuration file` should be log_level = WARN. 

## Problem Definition

 In practice, relayers know which chains they are trying to relay between, and this message becomes very noisy/redundant. If you are relaying between chains with lower traffic, 90% of logs are just that warning, making it difficult to parse when actual errors/warnings occur.

## Proposal

I wouldn't log anything for this event because things happening on chains that are not in `config.toml` are irrelevant to the relayer operator. I could also see making it log_level = DEBUG.

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
Hi guys, I wish I had thought of the simple solution myself. This will definitely make logs easier to read.

**Comment by adizere** [comment]
@karzak and @faddat: We added a fix to the problem, it is currently in `master`. Feel free to test and we would appreciate any feedback, thanks!

We plan to release the fix next week as part of `v0.14.0`.
