### ISSUE TITLE
Derive serde's `Serialize` and `Deserialize` for structs in `ibc-proto::ibc::core` and `ibc_proto::ibc::applications`

### ISSUE THREAD

**Issue by Wizdave97** [informalsystems/ibc-rs#1988]
## Summary
Hello, we need serde's Serialize and Deserialize implemented for some structs in the `ibc-proto::ibc` module, these structs are being used in our rpc interface so they need to implement the Serialize and Deserialize traits.

## Problem Definition

Are there any disadvantages of including this feature? --> No

## Proposal
Serialize and Deserialize should be implemented for structs in the `ibc_proto::ibc::core` and `ibc_proto::ibc::applications` modules when `std` is enabled

## Acceptance Criteria
 All structs in `ibc_proto::ibc::core` and `ibc_proto::ibc::applications` have Deserialize and Serialize implemented when `std` is enabled

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Wizdave97** [comment]
@romac  could this be implemented in the next release, open to working on it.

**Comment by romac** [comment]
Sure, happy to release it for 0.13.0 if you can open a PR by the end of the week :)

**Comment by Wizdave97** [comment]
> Sure, happy to release it for 0.13.0 if you can open a PR by the end of the week :)

@romac Is any of the code in the `ibc
-proto`  module auto generated?

**Comment by Wizdave97** [comment]
Okay, thank you
