### ISSUE TITLE
Determine how to handle the 'proof' parameter for queries to the private store

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#205]
In a discussion in #196, it was brought up the fact that some queries such as `clients/{identifier}/connections` that target the private store allows the `proof` parameter to be specified. The discussion was that if we need to set (hardcode) this parameter to false since we know that is the only valid value or if we should allow users to specify an invalid value (e.g. true) and get an error message (right now an error `client connections query error store error: requested proof for privateStore path` is shown). This is affects other queries too e.g. `clients/{identifier}/clientState`.

This is a UX decision too, need to think the best way to refactor the code for this. Hardcoding the value to false in these use cases is the quick solution, but there might be a need eventually some architecture decisions (e.g. know if the query targets a private or provable store and handle accordingly).

Reference: https://github.com/cosmos/ics/tree/master/spec/ics-024-host-requirements

**Comment by ancazamfir** [comment]
Let's remove the `-p` option from `QueryClientConnectionsCmd` as there is no benefit to it, especially that the default is `true` which fails the query immediately.
