### ISSUE TITLE
Only allow channel-ids of the form `channel-{N}`

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#2068]
## Summary of Bug
The `ChannelId::FromStr` impl does check if the given string is a valid ICS24 identifier but doesn't check if it is of the form `channel-{N}`. 

## Version
master

## Acceptance Criteria
- [ ] It shouldn't be possible to create a channel that isn't of the form `channel-{N}`. 
- [ ] Should we remodel `ChannelId` as `ChannelId(u64)` instead?
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Good catch! Let's model it as a newtype of u64 indeed!
