### ISSUE TITLE
Wildcard based packet filtering isn't working as expected

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#2075]
## Summary of Bug
Packet filtering wildcards are not working as expected, for eg. the below wilcard `PortId` 'transfer*' is matching 'ft-transfer'.
```toml
policy = 'allow'
list = [
    ['transfer*', 'channel-1'],
]
```

## Version
v0.13.0

## Failing test
```rust 
#[test]
fn packet_filter_regex() {
    let allow_policy = r#"
            policy = 'allow'
            list = [
              ['transfer*', 'channel-1'],
            ]
            "#;

    let pf: PacketFilter = toml::from_str(allow_policy).expect("could not parse filter policy");
    assert!(!pf.is_allowed(
        &PortId::from_str("ft-transfer").unwrap(),
        &ChannelId::from_str("channel-1").unwrap()
    ));
}
```

## Acceptance Criteria
The above test must pass or we should clarify what the wildcard means/matches; the documentation describes the wildcard `ica*` as all identifiers starting with `ica` -> https://github.com/informalsystems/ibc-rs/blob/master/config.toml#L206-L212
```md
#             Optionally, each element may also contains wildcards, for eg. 'ica*'
#             to match all identifiers starting with 'ica' or '*' to match all identifiers.
```
____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by romac** [comment]
Looks like we forgot to anchor the regex with `^` and `$`
