### ISSUE TITLE
Relayer CLIs for connection messages

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#208]
## Summary
We should be able to send transactions from the relayer CLI for all IBC connection messages. Light client requests should be made to fetch the headers at required heights, chains should be queried for connection and consensus state with proofs, etc.

##  Proposal
The following CLIs should be implemented by the relayer:

1. `relayer tx raw conn-init <to-chain-A> <remote-chain-B> <client-B-on-A> <client-A-on-B> <conn-id-on-A> <conn-id-on-B> `  (#206)
      - sends a `MsgConnectionOpenInit` to `to-chain-A` with 
    ```
    connection_id = conn-id-on-A,
    client_id = client-B-on-A,
    counterparty_connection_id = conn-id-on-B,
    counterparty_client_id = client-A-on-B,
    counterparty_commitment_prefix = get_store_prefix(remote-chain-B),
    signer = get_account(to-chain-A),
    ```

2.  ConnOpenTry:  #358
3. ConnOpenAck: #359
4. ConnOpenConfirm: #360

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Closed already as part of v0.0.5
