### ISSUE TITLE
CheckTx equivalent for modules

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#2094]
## Summary
The ibc-rs module provides a `deliver()` method that is somewhat equivalent to Tendermint ABCI's `DeliverTx`, but we're missing a `CheckTx` equivalent. 

## Proposal
We might want to look at ibc-go's antehandlers to determine what checks need to done -> https://github.com/cosmos/ibc-go/blob/main/modules/core/ante/ante.go

## Acceptance Criteria
- [ ] Provide a method that lib users can use in their ABCI app's `CheckTx` implementation. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
As discussed, this is not needed.
