### ISSUE TITLE
Add support for selecting specific wallet for packet clearing CLI

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#2111]
## Summary

Add `-k <KEY>` option for `clear packets` CLI, just like Hermes provides one for `tx raw ft-transfer -k <KEY>`

## Problem Definition

Hermes operators typically run one `start` instance in the background and then sometimes require a second instance to do packet `clear`ing in parallel. This second instance should not be reusing the same wallet as the first, otherwise it would result in `account sequence mismatch` errors. Currently, it is not possible to start `clear packets` with a separate wallet.

## Acceptance Criteria

- [ ] Add support for using a specific <KEY> with option `-k` as part of `clear packets` CLI

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
I'm not sure what a `key` looks like. What's an example key I could use to test this flow?

**Comment by ancazamfir** [comment]
I think we should have the `-k` for all CLIs. Is there a way to have a generic solution for all CLIs? i.e. overwrite the key in the chain config if -k flag is present.
