### ISSUE TITLE
Relayer dependency does not compile.

### ISSUE THREAD

**Issue by deuszx** [informalsystems/ibc-rs#2139]
## Summary of Bug

I'm working on a project where `relayer` is my dependency. I've added it as follows:
```
[dependencies.ibc-relayer]
git = "https://github.com/informalsystems/ibc-rs"
```
but the code fails to compile b/c of the error:
```
error[E0277]: the trait bound `DerivationPath: From<&StandardHDPath>` is not satisfied
   --> /home/mateusz/.cargo/git/checkouts/ibc-rs-a065dcf743eaa6c9/dee7489/relayer/src/keyring.rs:412:57
    |
412 |         .and_then(|k| k.derive_priv(&Secp256k1::new(), &DerivationPath::from(hd_path)))
    |                                                         ^^^^^^^^^^^^^^^^^^^^ the trait `From<&StandardHDPath>` is not implemented for `DerivationPath`
    |
    = help: the following implementations were found:
              <DerivationPath as From<&'a [ChildNumber]>>
              <DerivationPath as From<Vec<ChildNumber>>>
```

The problem seems to come from this line: https://github.com/informalsystems/ibc-rs/blob/master/relayer/src/keyring.rs#L412 . I don't see anything about it being changed recently. My code used to work fine as well and suddenly stopped yesterday.

## Version

https://github.com/informalsystems/ibc-rs/commit/37dbe8c42ae09403432ebfcfdb2a8a34d86909e9

## Steps to Reproduce

1. Add `relayer` as a dependency to your project.
2. Compile.

Repository with the minimal failing sample https://github.com/deuszx/ibc-failing-sample

## Acceptance Criteria

Projects starts compiling again.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by DaviRain-Su** [comment]
I have encountered this problem, here you need to modify the version of the hdpath dependent bitcoin in Cargo.toml to 0.27, you check the bitcoin crate you depend on will have multiple versions of dependencies

**Comment by deuszx** [comment]
Hey @DaviRain-Su , thanks. Do you mean this one https://github.com/informalsystems/ibc-rs/blob/master/relayer/Cargo.toml#L44 ? And change from `=0.27` to strictly `0.27.0?

**Comment by DaviRain-Su** [comment]
Here I directly modified the hdpath dependency in cargo.lock by changing the bitcoin dependency to 0.288.

**Comment by DaviRain-Su** [comment]
> Hey @DaviRain-Su , thanks. Do you mean this one https://github.com/informalsystems/ibc-rs/blob/master/relayer/Cargo.toml#L44 ? And change from `=0.27` to strictly `0.28`?

https://github.com/deuszx/ibc-failing-sample/blob/35056337fe7240fcdc3fbda7479903b00408ff29/Cargo.lock#L762  change this line `bitcoin 0.28.0` to `bitcoin`

**Comment by deuszx** [comment]
Thanks. I would like to set the version to use  but `0.28` has other problems. Also, this issue should be fixed in the `ibc-rs` directly so I hope devs will do it soon.

**Comment by DaviRain-Su** [comment]
> Thanks. I would like to set the version to use but `0.28` has other problems. Also, this issue should be fixed in the `ibc-rs` directly so I hope devs will do it soon.

yet, using cargo update directly will cause this problem. whish this help you.

**Comment by romac** [comment]
This has been [fixed](https://github.com/informalsystems/ibc-rs/pull/2151) in v0.14.0, but still depends on `bitcoin` 0.27. We will update to `bitcoin` 0.28 in the next release (0.15.0).
