### ISSUE TITLE
Prepare release of v0.0.3

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#214]
## Summary

this laundry list is minimal:

- [x] Fill in changelog for v0.0.3
- [x] Bump all crate versions to v0.0.3
- [x] (just in case) don't forget`cargo fmt`
- [x] Cleanup issues: reassign unfinished issues of 0.0.3 to next milestone

**Comment by ebuchman** [comment]
Cool let's try to get this out Monday. Pretty small release, mostly focused on the initial ics02/07 handler implementations, removing some traits, and some specs/docs
