### ISSUE TITLE
Tutorial is outdated: `hermes create channel`

### ISSUE THREAD

**Issue by plafer** [informalsystems/ibc-rs#2154]
## Summary of Bug
According to the [hermes tutorial](https://hermes.informal.systems/tutorials/local-chains/relay-paths/create-new-path.html), I should be able to run

```shell
hermes create channel ibc-0 ibc-1 --port-a transfer --port-b transfer
```

to create a client, connection and channel between chains `ibc-0` and `ibc-1`. This current fails with error

```shell
error: Invalid value "ibc-1" for '<CONNECTION_A>': identifier ibc-1 has invalid length 5 must be between 10-64 characters
```

## Version

v0.14.0

## Steps to Reproduce

1. Spawn two chains (I used basecoin chains)
2. Make sure your `hermes` config knows about both chains
3. Run `hermes create channel ibc-0 ibc-1 --port-a transfer --port-b transfer`
4. Notice the aforementioned error

## Acceptance Criteria

The `hermes create channel` command succeeds.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
The guide is outdated, the syntax for `create channel` is now

```
hermes create channel [OPTIONS] --port-a <PORT_A> --port-b <PORT_B> <CHAIN_A> [CONNECTION_A]
```

ie. the second positional argument is now the connection id.

I will update the guide later today, thanks for noticing!

PS: I am more and more convinced that we should eventually (for v1) move away from positional arguments and use flags everywhere.

**Comment by adizere** [comment]
> PS: I am more and more convinced that we should eventually (for v1) move away from positional arguments and use flags everywhere.

++++1

**Comment by romac** [comment]
Guide is now up to date: https://hermes.informal.systems/tutorials/local-chains/relay-paths/create-new-path.html

**Comment by romac** [comment]
Output listed in the guide depends on https://github.com/informalsystems/ibc-rs/pull/2158

**Comment by dylanschultzie** [comment]
@romac it appears the guide isn't updated still:
<img width="846" alt="Screen Shot 2022-05-26 at 1 54 42 PM" src="https://user-images.githubusercontent.com/9121234/170578573-9a995587-10ec-49bd-bd72-4b6b24dfc4ec.png">

**Comment by adizere** [comment]
I was just about to approve #2245. Then I found this strange thing.

If I open
https://hermes.informal.systems/tutorials/local-chains/relay-paths/create-new-path.html

I see the correct, up-to-date instructions:
![Screenshot 2022-06-01 at 10 34 23](https://user-images.githubusercontent.com/1757002/171362894-3b730956-8a67-41ef-8be8-a4a759d68282.png)

But this page is not consistent with the source code
https://github.com/informalsystems/ibc-rs/blob/b7fc78e99f189f3fcad836008720ccec788ed1ff/guide/src/tutorials/local-chains/relay-paths/create-new-path.md?plain=1#L3-L6


What am I missing?

**Comment by romac** [comment]
I already pushed the guide update manually but we now need to merge this to update the repo so that the update will be kept for the next version.
