### ISSUE TITLE
Remove Uninitialized state from connection 

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#217]
## Summary of Bug

We should align with the ICSes.

> @adizere Is there a particular reason the Rust implementation uses the `Unitialized` state?
> If not, I suggest we remove it and likewise in the SDK (see above comment) to match the specification, then close this issue.

_Originally posted by @cwgoes in https://github.com/cosmos/ics/issues/452#issuecomment-683810821_

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
We should wait for the protobuf change in SDK before we proceed with this.

**Comment by cwgoes** [comment]
For reference, the SDK issue tracking this work is https://github.com/cosmos/cosmos-sdk/issues/7175.

**Comment by ancazamfir** [comment]
Channel messages need a significant rework and cleanup (#315 ) and the change for the channel state will be done there.
