### ISSUE TITLE
Client Ugrade Command Not Working in v0.14.1

### ISSUE THREAD

**Issue by rhuairahrighairidh** [informalsystems/ibc-rs#2185]
## Summary of Bug

The command `hermes tx raw upgrade-client` is failing in v0.14.1, but working in v0.14.0.

I believe it's due to this issue: https://github.com/informalsystems/ibc-rs/pull/2021

The command tries to fetch the upgraded consensus state from the last block of the old chain but fails to find it, because it uses the wrong block height.

Previously it used the last block as reported by /status rpc, but now uses another method. When the chain halts, the two methods differ: /status returns the uncommited halted height (listed in the upgrade plan), the other returns the last commited height (one before the upgrade plan).

Note, although technically the last commited consensus state is for one block before the upgrade height, the cosmo-sdk upgrade querier stores it under the upgrade height.

## Version

v0.14.1

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hmm, this is an interesting corner-case. Thanks for bringing it to our attention!
