### ISSUE TITLE
Investigate the use of Nix towards making our CI Docker-free

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#2190]
## Summary

Our CI, in particular the E2E tests based on `gaiad`, make use of Docker images. See the readme [here](https://github.com/informalsystems/ibc-rs/tree/master/ci#continous-integration-for-ibc-rs) for more details, but briefly it entails creating and maintaining Docker images for various Gaiad versions in our repository, which is cumbersome and manual.

## Problem Definition

1. Too much technical debt in our repository surrounding the use of custom-built Docker images for each Gaia version. See this for example: https://github.com/informalsystems/ibc-rs/tree/master/ci/chains/gaia.

2. It is difficult for us to upgrade our CI whenever a new Gaiad version appears. See this [PR](https://github.com/informalsystems/ibc-rs/pull/2092) for instance.

## Proposal

This is an investigation work to understand how easy would it be to completely remove the use of Docker in our CI and replace it with Nix. 

Alternatively, we should at least _not_ rely on our home-baked Docker images, and use the official ones: https://github.com/cosmos/gaia/pkgs/container/gaia

## Acceptance Criteria

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by soareschen** [comment]
> how easy would it be to completely remove the use of Docker in our CI and replace it with Nix.

FYI the Python E2E tests are already running inside the integration tests on master using `gaiad` provided from Nix: https://github.com/informalsystems/ibc-rs/blob/master/tools/integration-test/src/tests/python.rs

**Comment by adizere** [comment]
Good point, thanks for highlighting that!

> So there should be no disruption in removing any of the Docker tests.

I would add that a possible disruption can occur if we remove the Docker tests, because there will be a single person on the team who can debug, reproduce, & maintain the Nix-based tests. If Nix E2E tests start to fail, we'll be in a difficult situation. I'm in favor or removing the Docker tests, but I would recommend that before we remove them we make sure we can maintain the Nix tests reliably (i.e., at least two members of the team can install and run Nix locally and can maintain the tests confidently). Ps. This is part of an onboarding project for a reliability engineer.

**Comment by soareschen** [comment]
It will disrupt the CI, but not regular development. And if there is any issue with Nix, the integration test CI will also be disrupted, and I'm not sure if that is not more important that the Docker tests.

In the worst case, someone just needs to rewrite the GitHub Actions workflows to install `gaiad` from somewhere else. They could just add steps to download the `gaiad` binary from official release, or clone the `gaiad` source from GitHub and run `make install`.

Note that the CI environment itself is already a container. So there is little benefit of containerizing a CI environment for the sake of reproducibility. The only benefit I see from a dockerized CI is that the same Docker image can be run locally. Otherwise developers can choose any approach of installing `gaiad` and run the tests locally.

**Comment by adizere** [comment]
We decided today we'll go towards removing the Docker-based tests in our CI because of an error with the Ubuntu repository.

> - The two end-to-end integration tests using Docker are failing because [[APT fails to retrieve the Ubuntu repository](https://github.com/informalsystems/ibc-rs/runs/7517829110?check_suite_focus=true)](https://github.com/informalsystems/ibc-rs/runs/7517829110?check_suite_focus=true).
> - RR: Can reproduce locally. Tried upgrading the Docker image to 21.10 to no avail.
> - We’re already running the E2E tests from integration-tests framework.
>     - https://github.com/informalsystems/ibc-rs/blob/4956fb20369f030c0d14288e6da85e80b569b2d0/tools/integration-test/src/tests/python.rs#L48
