### ISSUE TITLE
Update Rust toolchain to 1.61

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#2260]
# Update to Rust release 1.61.0

🦀

- [x] Update the version in `rust-toolchain.toml` (#2259).
- [x] Run `cargo clippy --all-features --fix`, review and commit the automatic
      fixes, and fix all reported lints. Try to resolve the root causes for
      the lints rather than silencing them with `#[allow(...)]` (#2259).

## Update the MSRV (optional)

Additional steps to perform in order to make the new minimal supported
Rust version:

- [ ] Update the `rust-version` fields in all `Cargo.toml` files.
- [ ] Update the `msrv` field in `clippy.toml` and fix all lints reported by
      `cargo clippy --all-features`.
- [ ] Update the MSRV shields in README files:
  - `README.md`
  - `relayer-rest/README.md`
- [ ] Update the MSRV in the guide: `guide/src/pre_requisites.md`
- [ ] Add a `.changelog` entry to the `breaking-changes` section,
      announcing the new MSRV.

**Comment by mzabaluev** [comment]
We are not using any 1.61 features yet ([custom exit codes](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html#custom-exit-codes-from-main) could be handy?), so no need to update the MSRV. The clippy failures are an issue in CI, though.
