### ISSUE TITLE
GM uses old style `keys add` command

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#2262]
## Summary of Bug

Post-merging #2251 we broke `gm`, specifically command `gm hermes keys`:

```sh
$ gm hermes keys
2022-06-02T16:35:20.808814Z TRACE ThreadId(01) deserialized the encoded pub key into a ProtoAny of type '/cosmos.crypto.secp256k1.PubKey'
Success: Added key 'wallet2' (cosmos1vxx437j8y0xqg4mw7fegu6qqza8nep258gclu7) on chain ibc-0
error: Found argument '--name' which wasn't expected, or isn't valid in this context

	If you tried to supply `--name` as a value rather than a flag, use `-- --name`

USAGE:
    hermes keys add --key-file <KEY_FILE> --mnemonic-file <MNEMONIC_FILE> <CHAIN_ID>
```

## Version

4397e4f6394efa2a333cc9dc27c7f982295f1af3

## Acceptance Criteria

- [ ] `gm hermes keys` works as intended

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Ah good catch, sorry for not thinking of that earlier. 

@ljoss17 Can you please take a look?

**Comment by adizere** [comment]
No worries, I didn't think of this case either until I encountered it now.

I have a tentative fix https://github.com/informalsystems/ibc-rs/pull/2263 but we should scrub the repository for `.*keys add.*` and `.*keys restore.*` to double-check any lingering references to these CLIs.
