### ISSUE TITLE
English specification of SendPacketEvent handling

### ISSUE THREAD

**Issue by milosevic** [informalsystems/ibc-rs#229]
This task should specify handling of SendPacketEvent as part of relayer processing. 
https://github.com/cosmos/ics/tree/master/spec/ics-018-relayer-algorithms is under-specified so 
we need to fill missing details. 

Related to https://github.com/informalsystems/ibc-rs/issues/124.

**Comment by ancazamfir** [comment]
Solved with  https://github.com/informalsystems/ibc-rs/pull/236 and  https://github.com/informalsystems/ibc-rs/pull/230
