### ISSUE TITLE
Hermes not working over IPv6

### ISSUE THREAD

**Issue by mturkia** [informalsystems/ibc-rs#2380]
## Summary of Bug

When connecting to a full node RPC with IPv6, Hermes repeats following error over and over again
`task encountered ignorable error: error raised while trying to refresh client 07-tendermint-198: failed querying the application status of source chain: internal message-passing failure while sending inter-thread request/response`

Note that we have one chain configured over IPv6 for GRPC, and we are not getting spammed with this error on the logs. So GRPC might be working over IPv6 properly.

## Version

0.15.0+4e83aae8
0.15.0+e8746bec
0.15.0+e3d0b108

## Steps to Reproduce

Configure chain to use IPv6
```
rpc_addr = 'http://[::1]:26657'
grpc_addr = 'http://[::1]:9090'
websocket_addr = 'ws://[::1]:26657/websocket'
```
Note that we have tested this only with public IPv6 addresses, not link local, but don't see why the local should work any differently.

## Acceptance Criteria

Hermes can use nodes over IPv6

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mturkia** [comment]
I tested this with v0.13.0 version of Hermes to ensure this is not related to the abci_info issue. And getting following error message when starting up:
```
Jul 20 16:12:49 Brute hermes[1620509]: 2022-07-20T16:12:49.667336Z ERROR ThreadId(01) failed to subscribe to events of phoenix-1: internal message-passing failure while receiving inter-thread request/response: receiving on an empty and disconnected channel
Jul 20 16:12:49 Brute hermes[1620509]: 2022-07-20T16:12:49.667342Z ERROR ThreadId(84) failed to start runtime for chain 'phoenix-1': event monitor error: failed to create WebSocket driver for chain phoenix-1 with address ws://[...::1]:26657/websocket
```

**Comment by romac** [comment]
Ok thanks for trying it out, we'll look into this.

**Comment by mzabaluev** [comment]
Reproduced the WebSocket driver error, digging deeper.

**Comment by mzabaluev** [comment]
Should be fixed by https://github.com/informalsystems/tendermint-rs/pull/1167

**Comment by adizere** [comment]
@mturkia this branch can be used to test [the fix that Mikhail did](https://github.com/informalsystems/ibc-rs/issues/2380#issuecomment-1196817333) and see if IPv6 works.

```bash
$ git co adi/tryipv6
$ cargo build
$ ./target/debug/hermes version

  hermes 1.0.0-rc.1+cfefab347

```

**Comment by mturkia** [comment]
Initially it looks like adi/tryipv6 branch is working fine. Just a single chain connected via IPv6 for the initial test, but packets are flowing. tnx
