### ISSUE TITLE
Missing unit tests for ibc-rs module verification

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#24]
## Crate
ibc

## Summary
We currently don't have unit tests for verification methods. While the `ics23` crate functions are tested (in that crate), we still need tests for our wrappers, conversions, etc. 

## Acceptance Criteria

- [x] informalsystems/ibc-rs-tmp#22

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Wizdave97** [comment]
@hu55a1n1  would  love to pick this up soon, could you please help flesh out the acceptance criteria and tests required?

**Comment by hu55a1n1** [comment]
@Wizdave97 I opened this issue as a placeholder just to remind us to implement unit tests similar to the ones in ibc-go. Here are some tests that I had in mind ->
* https://github.com/cosmos/ibc-go/tree/main/modules/light-clients/07-tendermint/types 
* https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/keeper/verify_test.go 

We already have some tests for Tendermint `ClientState` which should give you a head start, for eg. the tests here (https://github.com/informalsystems/ibc-rs/blob/master/modules/src/clients/ics07_tendermint/client_state.rs#L361) are similar to the ibc-go tests here (https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/types/client_state_test.go#L74). Note that some of these tests use ibc-go's testing framework, so we can ignore them for now.

**Comment by Wizdave97** [comment]
> https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/types/client_state_test.go#L74

Thanks I'll work on them

**Comment by rnbguy** [comment]
The issue of the acceptance criteria is closed. Does that make this issue finished too?
