### ISSUE TITLE
ibc-proto: Add Cosmos SDK sources as a Git submodule

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#240]
Doing this instead of cloning the `master` branch of repository via the Makefile would:

a) ensure that we are pinned against a specific version of the SDK
b) allow us more control as to when we want to update the version of SDK we are running against
c) improve discoverability of the Cosmos SDK sources (they would show up in the GitHub UI)

**Comment by adizere** [comment]
Cool! How do we achieve a) exactly? Do we specify the pinned version in the `.gitmodules` file somehow? This is the only shady part to me, otherwise great idea!

**Comment by ancazamfir** [comment]
Do we need a finer grain than `v1`, `v2`, etc as dealt with in https://github.com/cosmos/cosmos-sdk/issues/7338?

**Comment by greg-szabo** [comment]
As an interim step, you can use the new version of proto-compiler from tendermint-rs: it allows you to check out the specific branch you want to work against.

Overall this has less overhead on repository management (try mentioning submodules to Ethan and see how he reacts).

Even with submodules you'll have to manage checkout, so looking at the updated code in tendermint-rs might be worth it.

**Comment by ancazamfir** [comment]
Closed via #365
