### ISSUE TITLE
Update to tendermint-rs v0.16

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#243]
Currently using tendermint-rs v0.15.

v0.16 includes minor changes, but two in particular that affect us:

1. Removed the `lite` module (we need to change all references to point to the light_client crate now)
2. Updated and removed some crypto dependencies (https://github.com/informalsystems/tendermint-rs/pull/522#pullrequestreview-477982589)

Tendermint-rs v0.17 is a work in progress with lots of breaking changes from the proto stuff. We should upgrade to v0.16 first to deal with the breaking changes from (1) independently. Looks like this will be a bunch of work and will require some refactoring of the `relayer` crate

We need the changes from (2) to get signing working, ie. to merge the code from #242 into the relayer-cli  

Could probably use help from @romac / @ancazamfir on this one

**Comment by romac** [comment]
I will take care of this as part of https://github.com/informalsystems/ibc-rs/issues/90.
