### ISSUE TITLE
`scripts/dev-env` needs an update

### ISSUE THREAD

**Issue by AlianBenabdallah** [informalsystems/ibc-rs#2436]
## Summary of Bug

`scripts/dev-env` will fail if executed many times. `hermes add keys` throws an error a key is already stored under the same name because it needs the flag `--overwrite`. 

## Version

1.0.0-rc.0+966ceadc
## Steps to Reproduce

run `./scripts/dev-env ~/.hermes/config.toml ibc-0 ibc-1` twice

## Acceptance Criteria

`./scripts/dev-env ~/.hermes/config.toml ibc-0 ibc-1` never fails

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Should we completely get rid of this code, i.e., delete `dev-env` related stuff under `scripts`?


`dev-env` is still referenced from https://hermes.informal.systems/tutorials/local-chains/start.html so it might be tricky to coordinate updating the guide <> updating the repo <> release. Note that Harveen already updated guide to shift focus from `dev-env` to `gm` #2360 it's just not deployed yet.
