### ISSUE TITLE
Unable to relay packets with error (serde parse error: missing field data)

### ISSUE THREAD

**Issue by achilleas-kal** [informalsystems/ibc-rs#2444]
## Summary of Bug
Hermes v0.15 won't relay packets on Injective Chain (ibc-go v3.1) with the error below. Downgrading to hermes v0.13 fixed the issue.

> Jul 14 18:21:10 i-fsn-01 hermes[1297]: 2022-07-14T16:21:10.116036Z  WARN ThreadId(48) refresh{client=07-tendermint-29 src_chain=injective-1 dst_chain=columbus-5}: task encountered ignorable error: error raised while trying to refresh client 07-tendermint-29: failed querying the application status of source chain: RPC error to endpoint http://xxx.com:4093/: serde parse error: missing field `data` at line 8 column 5

## Steps to Reproduce
This started happening upon a chain upgrade on Injective, the only change that could be related to IBC transfers was an upgrade from ibc-go v2 to ibc-go v3.1.

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Looks like the data returned by the `/abci_info` RPC endpoint of Injective chains is missing a couple fields, namely `data` and `version`. This used to work with Hermes < v0.15 because we only [started querying](https://github.com/informalsystems/ibc-rs/pull/2021) this endpoint to fix issue https://github.com/informalsystems/ibc-rs/issues/1970.

As far as I can tell, we do not use the value of these two fields, so we could make them optional.

### Injective

```
$ curl https://tm.injective.network/abci_info?
```

```json
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "response": {
      "last_block_height": "13111281",
      "last_block_app_hash": "nf/g23bemW4IAgz53DqCliUivcra12DFw/I60URaIcA="
    }
  }
}
```

### Cosmos Hub

```
$ curl https://rpc.cosmos.network/abci_info?
```

```json
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "response": {
      "data": "GaiaApp",
      "version": "v7.0.0",
      "last_block_height": "11338424",
      "last_block_app_hash": "FvCOSo05Doi2fuLkp66s79cm4a336Lti3pTylto/O6k="
    }
  }
}
```

**Comment by achilleas-kal** [comment]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/83584143/180033381-9c8436ca-5f97-4362-ab8e-84f9f5b8e683.png">

@romac we looked into it and had to add this from **MakeFile** so should be fixed in production too on our end soon, it might be a good idea to make them optional though since it's a manual process that has to be done.

**Comment by romac** [comment]
Good to hear, thanks! We will indeed look into making those optional on our end.

**Comment by mzabaluev** [comment]
This looks similar to https://github.com/informalsystems/tendermint-rs/issues/1132. I will backport https://github.com/informalsystems/tendermint-rs/pull/1131 to tendermint-rs 0.23.

**Comment by adizere** [comment]
> looked into it and had to add this from **MakeFile** so should be fixed in production too on our end soon, it might be a good idea to make them optional though since it's a manual process that has to be done.

Is it possible to provide further details here on what you changed to your Makefile, in case others encounter the same problem? Many thanks!

**Comment by adizere** [comment]
@achilleas-kal would you consider quickly running Hermes from https://github.com/informalsystems/ibc-rs/pull/2465 to see if this issue is still causing problems in production?

**Comment by achilleas-kal** [comment]
@adizere happy to but we're using kubernetes and we build docker images from the hermes repository so I can't exactly build from source. Could you push a docker image with the fix? If I get an image i.e. `informalsystems/hermes:0.13.0` that includes the fix I can test quickly.

**Comment by mzabaluev** [comment]
> @adizere sure. These two lines did the trick
> 
> ```
> COSMOS_VERSION_NAME = injective
> 
> install: export VERSION_FLAGS="-X $(VERSION_PKG).AppVersion=$(APP_VERSION) -X $(VERSION_PKG).GitCommit=$(GIT_COMMIT)  -X $(VERSION_PKG).BuildDate=$(BUILD_DATE) -X $(COSMOS_VERSION_PKG).Version=$(APP_VERSION) -X $(COSMOS_VERSION_PKG).Name=$(COSMOS_VERSION_NAME) -X $(COSMOS_VERSION_PKG).AppName=injectived -X $(COSMOS_VERSION_PKG).Commit=$(GIT_COMMIT)"
> ```

This does not change `/abci_info` output for the gaiad binary I'm trying to build locally (in a source tree with `v7.0.2` checked out, which I also built earlier).

**Comment by romac** [comment]
Since @mzabaluev [added test fixtures](https://github.com/informalsystems/tendermint-rs/pull/1164) to tendermint-rs for the case where the version and/or data are missing, I think we can go ahead an close this issue. I'll include a changelog entry in the v1.0.0-rc.1 release PR.

**Comment by albertchon** [comment]
@mzabaluev Looks like @achilleas-kal didn't include the other relevant variables for the version flags. Here's the relevant LDFLAGS from our Makefile 

```bash
GIT_COMMIT = $(shell git rev-parse --short HEAD)
COSMOS_VERSION_PKG = github.com/cosmos/cosmos-sdk/version
COSMOS_VERSION_NAME = injective

install: export GOPROXY=direct
install: export VERSION_FLAGS="-X $(COSMOS_VERSION_PKG).Version=$(APP_VERSION) -X $(COSMOS_VERSION_PKG).Name=$(COSMOS_VERSION_NAME) -X $(COSMOS_VERSION_PKG).AppName=injectived -X $(COSMOS_VERSION_PKG).Commit=$(GIT_COMMIT)"
install:
	cd cmd/injectived/ && go install -tags $(build_tags_comma_sep) -ldflags $(VERSION_FLAGS)
```
