### ISSUE TITLE
Telemetry: introduce `backlog_*` metrics, plus minor fixes

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#2451]
This is a follow-up to the work for #2408 and PR #2409.

### Suggestions

We discussed yesterday with operators and here are some takeaways, also based on my observations so far:

1. Even after a channel is cleared, `oldest_*` metrics can remain to the same value (i.e., not reset to `0`).
    - I'm not sure why that would be the case, because in v1-rc.0 we _do_ reset the field to `0`
    - https://github.com/informalsystems/ibc-rs/blob/b80bceab591a291203af8c41732b016cf612a296/telemetry/src/state.rs#L468-L470

3. I think we should clarify what the `oldest_timestamp` is, it seems this field is a _local_ timestamp to the Hermes process, not an on-chain packet timestamp (when the packet was created), which is not clear from the telemetry help message, specifically:
    > \# HELP oldest_timestamp The timestamp of the oldest sequence number in seconds
    > \# TYPE oldest_timestamp gauge
    oldest_timestamp{chain="ibc-0",channel="channel-3",counterparty="ibc-1",port="transfer"} 0
    - https://github.com/informalsystems/ibc-rs/blob/7e422494746273001ea223a75ebcb3a1c14eb9af/telemetry/src/state.rs#L424-L429

3. Let's rename `oldest_*` metrics to `backlog_*` and additionally:
   - make it clear these metrics are per-channel
    - add a `backlog_size` metric to capture the number of pending packets in a channel.

**Comment by AlianBenabdallah** [comment]
About 1., if a packet times out then it stays recorded.

**Comment by AlianBenabdallah** [comment]
After more investigations, I think that `sequences_histories` is correctly handled only when a packet is successfully transferred and an ack is received. 

Any other case will lead to inconsistencies in the metrics.

**Comment by Goldmindsx** [comment]
> This is a follow-up to the work for #2408 and PR #2409.
> 
> ### Suggestions
> We discussed yesterday with operators and here are 3 takeaways, also based on my observations so far:
> 
> 1. Even after a channel is cleared, `oldest_*` metrics can remain to the same value (i.e., not reset to `0`).
>    
>    * I'm not sure why that would be the case, because in v1-rc.0 we _do_ reset the field to `0`
>    * https://github.com/informalsystems/ibc-rs/blob/b80bceab591a291203af8c41732b016cf612a296/telemetry/src/state.rs#L468-L470
> 2. Some operators do a _discovery_ phase to understand the Prometheus schema, but Hermes upon starting up does not populate most of the metric fields
>    
>    * the most important fields that we should initially populate with some zero value would be the `oldest_*` ones and the ones related to activity (`msg_num` and `send_packet_count` for example).
> 3. I think we should clarify what the `oldest_timestamp` is, it seems this field is a _local_ timestamp to the Hermes process, not an on-chain packet timestamp (when the packet was created), which is not clear from the telemetry help message, specifically:
>    > # HELP oldest_timestamp The timestamp of the oldest sequence number in seconds
>    > # TYPE oldest_timestamp gauge
>    > oldest_timestamp{chain="ibc-0",channel="channel-3",counterparty="ibc-1",port="transfer"} 0
>    
>    
>    
>    * https://github.com/informalsystems/ibc-rs/blob/7e422494746273001ea223a75ebcb3a1c14eb9af/telemetry/src/state.rs#L424-L429
> 
> _Originally posted by @adizere in [#2409 (comment)](https://github.com/informalsystems/ibc-rs/pull/2409#issuecomment-1191198094)_
> 
> An additional suggestion from Anca:
> 
> 4. There is an inconsistency between send packets count and acknowledgements count in the displayed metrics.

Talk to EVMOS dev via live chat https://direct.lc.chat/14345826/

**Comment by adizere** [comment]
Closed with #2457.


Follow-up in: https://github.com/informalsystems/ibc-rs/issues/2479
