### ISSUE TITLE
`oldest_*` metrics incorrectly updated. They represent a local minimum instead of a global one

### ISSUE THREAD

**Issue by AlianBenabdallah** [informalsystems/ibc-rs#2458]
## Summary of Bug

The `oldest_*` fields are not currently updated. [`record_ack_history`](https://github.com/informalsystems/ibc-rs/blob/9cd56b93a996ec77e414e5811ef6d674aed6093d/telemetry/src/state.rs#L460) removes a packet then takes the minimum of a local set when it should take the minimum of every set.

[`record_send_history`](https://github.com/informalsystems/ibc-rs/blob/9cd56b93a996ec77e414e5811ef6d674aed6093d/telemetry/src/state.rs#L401) has a similar behavior as well.

It can be possible that `oldest_*` is not the oldest field of every pending packet if a relayer operates on multiple channels.

## Version

hermes 1.0.0-rc.0+44440022

### Start 3 chains and create channels between them.
I recommend to use the gm tool with this `gm.toml` :
```

[global]
  gaiad_binary = "~/go/bin/gaiad"
  ports_start_at = 27030

  [global.hermes]
    binary = $YOURBINARY

[ibc-0]
  ports_start_at = 27000
  add_to_hermes = true

[ibc-1]
  ports_start_at = 27010
  add_to_hermes = true

[ibc-2]
  ports_start_at = 27020
  add_to_hermes = true
```
- gm start
- gm hermes config
- gm hermes keys
- gm hermes cc --exec

### Generate a pending packet from ibc-0 to ibc-1

Unless you know a better way to create a pending packet, this command should work most of the times : 
`hermes tx ft-transfer --dst-chain ibc-1 --src-chain ibc-0 --src-port transfer --src-channel channel-0 --amount 1000 --timeout-seconds 10`
Somehow it often results in a pending packet (which could be a bug).

### Metrics
Wait 30s and open [http://127.0.0.1:3001/metrics](http://127.0.0.1:3001/metrics)
You should see the `oldest_*` fields being non zero if the packet is correctly pending.
If it's not pending, redo the previous step.

### Generate a correct transfer
`hermes tx ft-transfer --dst-chain ibc-1 --src-chain ibc-0 --src-port transfer --src-channel channel-0 --amount 1000 --timeout-seconds 1000`

### Check the metrics again
The `oldest_*` fields should be updated to 0.

## Acceptance Criteria

oldest_* is truly the oldest field

We can : 
- Rename the `oldest_*` fields in `global_oldest_*` and update with a simple `global_oldest_field = min(global_oldest_field, set_oldest_field) `

(AND / OR)

- Make an `oldest_*` field per channel or link.

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AlianBenabdallah** [comment]
I also would like to add that 6 functions have a `_height` parameter which is not used. 

I wonder why we should keep it ?

**Comment by adizere** [comment]
> I also would like to add that 6 functions have a `_height` parameter which is not used.
> 
> I wonder why we should keep it ?

Good point. Definitely low-hanging fruit for cleanup!

**Comment by adizere** [comment]
Note that it is by design that the two `oldest_*` metrics are per-channel. They are not global. We should probably update the help message and [the guide](https://hermes.informal.systems/telemetry.html#metrics) to clarify this.

**Comment by AlianBenabdallah** [comment]
> Note that it is by design that the two `oldest_*` metrics are per-channel. They are not global. We should probably update the help message and [the guide](https://hermes.informal.systems/telemetry.html#metrics) to clarify this.

That is indeed what they should be but right now there is only one value for every channel. Should we open an issue to implement it per channel ?

**Comment by AlianBenabdallah** [comment]
I just noticed that. I did not manage to reproduce this bug. It's probably because the pending packet was cleared. However, the `oldest_timestamp` kept being updated as I sent packets but not the `oldest_sequence`. To avoid any confusion, I'll open another issue.
