### ISSUE TITLE
Cleanup of `tx raw` content from the Hermes guide 

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#2466]
## Summary

Hermes users should avoid using `tx raw` (renamed into `tx`) CLIs, because these are mostly intended for developers and testing. The Hermes guide, however, instructs users to use `tx raw` at various points, eg [to create channel](https://hermes.informal.systems/tutorials/local-chains/raw/index.html). This can create confusion & can lead users to relying too much on these CLIs.

## Proposal

Move the `tx` related guidelines out of the guide and in a different place. The guide should increasingly be targeting end-users.

## Acceptance Criteria

- [ ] the Hermes guide focuses on user recipes, not developer use-cases.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AlianBenabdallah** [comment]
We might propose a new design for the guide. If so, there will be a lot of modifications including `tx raw`.
