### ISSUE TITLE
Extract the type_url explicit strings into constants

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#254]
## Summary
With the migration to the new protobufs we need to keep track of the `type_url` used by `prost_types::Any`.
Currently these are used in clear, e.g.:
https://github.com/informalsystems/ibc-rs/blob/3e60e67b679ffab65b1a173b1af12411eb08d4c5/modules/src/ics02_client/client_def.rs#L128-L130

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
We should use the fn `type_url` from trait Msg to encapsulate all calls to type_url:

https://github.com/informalsystems/ibc-rs/blob/12cb1d6187e878eee0e40295fe0b804ddef0b846/modules/src/tx_msg.rs#L21-L23

Currently this is only implemented for a handful of type, e.g., MsgCreateAnyClient:

https://github.com/informalsystems/ibc-rs/blob/12cb1d6187e878eee0e40295fe0b804ddef0b846/modules/src/ics02_client/msgs/create_client.rs#L81-L83

**Comment by ancazamfir** [comment]
This has been taken care over a number of PRs (see git blame :))
