### ISSUE TITLE
Move all crates into a `crates` subfolder in the repository

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#2541]
## Summary

Move all crates into a `crates` subfolder in the repository.

## Problem Definition

We have too many files and folders at the root of the repository, which makes it difficult to navigate the repo.

## Proposal

Consolidate all crates into a `crates` folder at the root of the repository and update the workspace `Cargo.toml`.

While we're at it, we could also rename the crates folders to the crate name, ie. `modules` would become `ibc`, `relayer` would be become `ibc-relayer`, etc.

## Acceptance Criteria

Implement the proposal above.

```
ibc-rs
├── CHANGELOG.md
├── CONTRIBUTING.md
├── Cargo.lock
├── Cargo.toml
│
├── (snip...)
│
├── crates
│   ├── ibc
│   ├── ibc-proto
│   ├── ibc-relayer
│   ├── ibc-relayer-cli
│   ├── ibc-relayer-rest
│   ├── ibc-telemetry
│   └── ibc-chain-registry (eventually)
│
├── etc...
```

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Let's keep in mind that we will soon split the repository into two repositories: one for the protos and modules and one for the relayer code.

**Comment by adizere** [comment]
Pls also take into account the discussion in #1437 in particular https://github.com/informalsystems/ibc-rs/discussions/1437#discussioncomment-1459913
