### ISSUE TITLE
`gm start` fails with chain binary using SDK 0.46

### ISSUE THREAD

**Issue by crodriguezvega** [informalsystems/ibc-rs#2581]
## Summary of Bug

`gm` doesn't start with chain binaries using SDK 0.46. 

If I run `gm start` I get the error:

```
Creating chain1 config...
Error: cannot add account at existing address
Usage:
  simd add-genesis-account [address_or_key_name] [coin][,[coin]] [flags]
```

## Version

`gm` from master.

## Steps to Reproduce

1. Download ibc-go's simd for [v5.0.0-beta1](https://github.com/cosmos/ibc-go/releases/tag/v5.0.0-beta1). 
2. Use the simd as the chain binary for `gm` and execute `gm start`.

## Acceptance Criteria

`gm` should create a valid genesis file and start the chain.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
@harveenSingh please have a look, should be a quick one.

**Comment by colin-axner** [comment]
I think this might be a bug in our simapp in ibc-go. Will report back later today

**Comment by colin-axner** [comment]
@crodriguezvega can we close this issue. It is due to a misconfiguration of ibc-go#`testing/simapp/simd/genaccounts.go`. I will open a pr on ibc-go
