### ISSUE TITLE
`tx upgrade chain` does not respect the format of other `tx` commands

### ISSUE THREAD

**Issue by AlianBenabdallah** [informalsystems/ibc-rs#2630]
## Summary 
Every tx command use `dst-chain` and `src-chain`. It should also be the case of tx upgrade-chain:

Instead of :
`tx upgrade-chain [OPTIONS] --reference-chain <REFERENCE_CHAIN_ID> --host-chain <HOST_CHAIN_ID> --host-client <HOST_CLIENT_ID> --amount <AMOUNT> --height-offset <HEIGHT_OFFSET>`

The command should be : 

`tx upgrade-chain [OPTIONS] --dst-chain <DST_CHAIN_ID> --src-chain <SRC_CHAIN_ID> --src-client <SRC_CLIENT_ID> --amount <AMOUNT> --height-offset <HEIGHT_OFFSET>`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
We chose these names on purpose because the notion of source and destination does not really apply here. Rather we use host and reference to distinguish between the client on the chain being upgraded and the one it points too.
