### ISSUE TITLE
IBC query features

### ISSUE THREAD

**Issue by boosik** [informalsystems/ibc-rs#2668]
## Question

Hi, I am boosik in a41 & decipher, korean blockchain research group.
We are making ibc-query implementation for ibc-go, and we also need to implement relayer for ibc-query.
Now we have forked ibc-rs and customize it, so when we successfully make it can we make new PR for ibc query?

What we are implementing,
* ibc-query module in ibc-go
* Some feature of hermes for ibc-query
* In ibc-query, relayer should query to counterparty chain, so we are implementing it.

**Comment by romac** [comment]
What do you mean by `ibc-query`? [Interchain Queries](https://github.com/cosmos/ibc/discussions/605)?

**Comment by boosik** [comment]
Yes, we are implementing interchain queies.

**Comment by romac** [comment]
I am confused as to what you are asking about here? Are you offering to implement support for Interchain Queries in Hermes?

On our side, we haven't started working on this yet, but we are tracking it in https://github.com/informalsystems/ibc-rs/issues/2362.

**Comment by boosik** [comment]
Ah no, I mean that our team is implementing interchain query and just for sharing it.
If we successfully implements interchain query, I want to share our branch or make PR.

**Comment by romac** [comment]
> Ah no, I mean that our team is implementing interchain query and just for sharing it.
> If we successfully implements interchain query, I want to share our branch or make PR.

Sounds great!

**Comment by romac** [comment]
Closing this in favor of https://github.com/informalsystems/ibc-rs/issues/2362, please post updates there if you have any or open an PR :)

**Comment by boosik** [comment]
Yeap great!
