### ISSUE TITLE
Prepare release of v0.0.4

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#271]
## Summary

- [ ] Fill in changelog for v0.0.4
- [ ] Bump all crate versions to v0.0.4
- [ ] Reassign unfinished issues of 0.0.4 to next milestone

**Comment by ancazamfir** [comment]
We were waiting for tendermint v0.17 before this new release.

**Comment by adizere** [comment]
Closed (again) by #319
