### ISSUE TITLE
Incomplete implementation of ICS-02 verification functions

### ISSUE THREAD

**Issue by devashishdxt** [informalsystems/ibc-rs#28]
## Crate

`modules/src/ics02_client`

## Summary

Not all the functions in [ICS-02](https://github.com/cosmos/ics/tree/master/spec/ics-002-client-semantics) are included in [`ClientDef`](https://github.com/informalsystems/ibc-rs/blob/master/modules/src/ics02_client/client_def.rs) trait.

## Problem Definition

I'm working on ICS-06 solo machine client implementation and found that a few functions mentioned in ICS-02 client specifications are missing from `ClientDef` trait in `modules/src/ics02_client`. To fully implement any client for IBC, we'll need these functions in base traits.

## Proposal

Add missing functions `ClientDef` trait. Currently, the `ClientDef` trait contains following functions:

- `check_header_and_update_state`
- `verify_client_consensus_state`
- `verify_connection_state`
- `verify_channel_state`
- `verify_client_full_state`

Following functions are missing:

- `checkMisbehaviourAndUpdateState` -- informalsystems/hermes#722 
- `verifyNextSequenceRecv`
- `verifyPacketReceiptAbsence`
- `verifyPacketAcknowledgement` -- informalsystems/hermes#737 
- `verifyPacketData` -- informalsystems/hermes#737 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
Closing this as stale and mostly a duplicate of the most recent #173.
