### ISSUE TITLE
IBC Modules ADR

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#3]
IBC Modules architecture/design in [`docs/architecture/adr-003-ibc-modules.md`](https://github.com/informalsystems/ibc-rs/blob/master/docs/architecture/adr-003-ibc-modules.md)

**Comment by adizere** [comment]
This was partially handled by [ADR 003](https://github.com/informalsystems/ibc-rs/blob/master/docs/architecture/adr-003-handler-implementation.md) (https://github.com/informalsystems/ibc-rs/issues/194), and the modules architecture seems to be still evolving (e.g., message structuring #367, #254, or error handling #68). So an ADR is relatively lower priority until the modules become more mature.

**Comment by adizere** [comment]
Closing as outdated. We may consider an ADR as we're advancing through non-SDK support, cf. https://github.com/informalsystems/ibc-rs/discussions/1318
