### ISSUE TITLE
Implement MBT for ICS04 Channel handlers

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/ibc-rs#30]
We need to initiate model-based testing for IBC-rs; while initially IBC client handlers (ICS02) have been chosen for that, we have decided to do it for ICS04 Channel handlers instead; see the [explanation below](https://github.com/informalsystems/ibc-rs/issues/546#issuecomment-767656002).

The goal is to complement the current manual tests for channel handlers with MBT-based ones, such that model-based tests will be able to explore unexpected corner cases.

We can split the work here in multiple parts, as follows:

- [x] ICS02: informalsystems/hermes#601 
- [x] ICS03: informalsystems/hermes#701 
- [ ] ICS04

Bugs found with MBT:
- informalsystems/hermes#626
- informalsystems/hermes#685
- informalsystems/hermes#699

**Comment by andrey-kuprianov** [comment]
We have figured out that client handlers are too primitive to throw the heavy MBT machinery at them; e.g. the [CreateClient handler](https://github.com/informalsystems/ibc-rs/blob/9d0a7b8f11a252e68e039a976910edd33107f074/modules/src/ics02_client/handler/create_client.rs#L24-L52) is only incrementing one counter, so no real logic to test.

Considering that now the Channel handlers are coming to completeness, we are shifting focus to them. They have quite non-trivial implementation, that deserves thorough testing; see e.g. the [ChanOpenTry handler](https://github.com/informalsystems/ibc-rs/blob/9d0a7b8f11a252e68e039a976910edd33107f074/modules/src/ics04_channel/handler/chan_open_try.rs#L16-L158).

The corresponding [TLA+ model](https://github.com/informalsystems/ibc-rs/blob/9d0a7b8f11a252e68e039a976910edd33107f074/docs/spec/tla/ibc-core/ICS04ChannelHandlers.tla#L64-L122) is also non-trivial, so this seems to be a good match for MBT.

**Comment by plafer** [comment]
Closing this as stale; we should reformulate these issues when we address #148 (and our correctness  strategy in general).
