### ISSUE TITLE
Allow specifying primary and witness peers for the light clients

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#311]
## Summary

We need to be able to somehow configure the primary and witness peers for the light client of a given chain.

## Problem Definition

Spawning a light client requires providing both a primary peer and one or more witness peers.
We currently do not track this information, and thus point both the primary and a single witness to the same node.
We need a way of specifying the primary and its witnesses via the command line.

## Proposal

Add new subcommands to the `light` command which will allow us to manage the primary and witness peers for a chain's light client. I propose the following API:

```
USAGE:
    relayer-cli light peer <OPTIONS>

DESCRIPTION:
    configure the peers of the light client for a given chain

SUBCOMMANDS:
    add       add a peer to the light client configuration
    rm        remove a peer from the light client configuration
```

```
USAGE:
    relayer-cli light peer add <OPTIONS>

DESCRIPTION:
    add a peer to the light client of a given chain

POSITIONAL ARGUMENTS:
    chain_id                  identifier of the chain

FLAGS:
    -a, --address ADDRESS     network address of the peer
    -i, --peer-id PEER_ID     identifier of the peer
    -p, --primary             make this peer the primary peer
```

```
USAGE:
    relayer-cli light peer rm <OPTIONS>

DESCRIPTION:
    remove a peer from the light client of a given chain

POSITIONAL ARGUMENTS:
    chain_id                  identifier of the chain

FLAGS:
    -i, --peer-id PEER_ID     identifier of the peer to remove
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
One question I have is where should those be stored?

a) in the `light_config.toml` file, just like the trust options
b) in the relayer config file

If we go with b), perhaps we should also merge the `light_config.toml` into the relayer config file?

**Comment by ancazamfir** [comment]
> One question I have is where should those be stored?
> 
> a) in the `light_config.toml` file, just like the trust options
> b) in the relayer config file
> 
> If we go with b), perhaps we should also merge the `light_config.toml` into the relayer config file?

I would prefer b) and add any required light client options to the the relayer config file. It includes some today already. Could you please add a link to a full light client config as reference?

**Comment by romac** [comment]
> Could you please add a link to a full light client config as reference?

It's currently just a map from `ChainId` to `TrustOptions`: https://github.com/informalsystems/ibc-rs/blob/master/relayer-cli/src/light/config.rs

**Comment by ancazamfir** [comment]
I was asking about the tendermint-rs light client config.

**Comment by romac** [comment]
There is no single struct which represents the full light client config at the moment (neither in ibc-rs nor tendermint-rs), but if we had one it would probably look like (in pseudo Rust):

```rust
struct PeerConfig {
    address: net::Address,
    trusted_header_hash: Hash,
    trusted_height: Height,
}

struct LightClientConfig {
    peers: PeerList<PeerConfig>;
    options: light_client::Options {
        trust_threshold: TrustThreshold,
        trusting_period: Duration,
        clock_drift: Duration,
    },
    rpc_timeout: Option<Duration>,
}
```

**Comment by romac** [comment]
Here is the config file we use for the light node: https://github.com/informalsystems/tendermint-rs/blob/master/light-node/light_node.toml.example

**Comment by ancazamfir** [comment]
We have a similar issue in #99, should we close that?

**Comment by romac** [comment]
Let's keep both issues, we'll do the configs merge first and then we can tackle the CLI for editing it.

**Comment by romac** [comment]
Done in #348
