### ISSUE TITLE
Infrastructure to support running integration tests

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#32]
## Summary

Implement integration tests for IBC queries.

## Problem Definition

As we implement more and more IBC queries, we need a way of making sure they are specified and executed properly, to avoid painstaking manual reviews like @ancazamfir did for #30.

## Proposal

This is just the initial issue, for kick-starting integration tests.

- Write integration tests for at least one IBC query or tx
- Set up the CI infrastructure need to run such a test automatically
- Allow specifying release (e.g. stargate-4) related to #204 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by andynog** [comment]
Working on creating images to support integration test on CI/CD and local machines (devs)
