### ISSUE TITLE
Model-based testing for ICS02 via ICS26

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/ibc-rs#324]
## Summary

As discussed during the IBC MBT meeting, the first target for MBT will be ICS26, more specifically, to replace these [manual tests](https://github.com/informalsystems/ibc-rs/blob/4819dd0b2b0dc2b26a8b0c0fa60aabd6cd0e2eb5/modules/src/ics26_routing/handler.rs#L61-L189) with the model-based tests auto-generated from [this model](https://github.com/informalsystems/ibc-rs/blob/d65ca7a26a7980127ad154eaaec3cbc1482df9cc/docs/spec/client/ICS02SingleChainEnvironment.tla#L1)

## Problem Definition

We want to get rid of tedious manual tests, and employ model-based tests instead. The benefits should be:
 * much easier to write tests
 * much more fun to do that
 * better test coverage

The possible drawback is that at the moment we will generate and store static JSON test fixtures, similar to how it's done for Tendermint-rs Light Client. This will change in the near future, when, with more integration, we'll need to either store only the TLA+ tests themselves (if running the model checker will fit in several seconds), or the example executions produced by Apalache. 

## Proposal

We will follow the same scheme we've done for the LightClient:
- [x] investigate the model and the code, and their relashionship
- [ ] extend the model with history tracking
- [ ] write several simple TLA+ tests
- [ ] write the Jsonatr transformation spec for translating the Apalache example execution into the test fixture
- [ ] write the test driver to execute the test fixtures.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by andrey-kuprianov** [comment]
as of now, the model and the code seem to be pretty aligned with each other. Here are the initial observations:
* The model is limited to creation and update of the clients; no connection handling is this variant
* The tests in the code are not independent; they update the shared context. This setting is similar to what we use in LC, and the test in that case is a sequence of those test calls.

**Comment by adizere** [comment]
MBT in ibc-rs is switching focus from testing the modules (ICS02 or others) to testing the relayer.
