### ISSUE TITLE
Write a system model for the IBC relayer

### ISSUE THREAD

**Issue by milosevic** [informalsystems/ibc-rs#325]
Define participants and roles in IBC protocol, fault-model assumed, synchrony assumptions and high level requirements IBC protocol ensures. These informations partially exists in ics repo (https://github.com/cosmos/ics/tree/master/spec/), but are scattered and segmented across various icses and written in the bottom up style. The idea behind this task is to write a document in a top down way, starting from participants, requirements and system model in which this can work. It should hopefully helps define test plan and inform engineering.

**Comment by adizere** [comment]
A system model description is also attempted in the ICS3 english spec, using the top-down approach. See mostly [level 1](https://github.com/informalsystems/ibc-rs/blob/master/docs/spec/connection-handshake/L1_2.md#l1-problem-statement--outside-view) and [level 2.1](https://github.com/informalsystems/ibc-rs/blob/master/docs/spec/connection-handshake/L1_2.md#21-system-model-specification). This focuses on ICS3 but may help inform the relayer system model.

**Comment by adizere** [comment]
Closing as no longer applicable.
