### ISSUE TITLE
ADR for Relayer v0 Concurrency Architecture

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#326]
## Summary
Specify the relayer concurrency architecture for the first release of the Relayer. The goal is to document this in ADR-005.

## Problem Definition
There are a few threads required by the v0 relayer, per chain and per relaying path or link. 

## Proposal

We would like to document the architecture in an ADR capturing the following decomposition:

![v0-concurrency](https://user-images.githubusercontent.com/1757002/98245376-1f30f600-1f71-11eb-943a-4c7830d6944f.jpg)

In this version of the relayer a single connection and channel are supported and they must be configured in the relayer configuration file. These limitations will be lifted in subsequent releases. 
`config executor` - single thread that runs upon start and creates a `link` associated with the relaying path. It also triggers initiation messages for objects included in the config file. These are the`ConnOpenStart` or `ChannOpenStart` that could potentially cause the relayer to build and send `ConnOpenInit` or `ChannOpenInit` messages to the chain. It should work even these events are received by the `link` in the same time with the live chain IBC events. In other words, no synchronization with starts of other threads should be required.

`chain` - one thread per chain that registers with the chain and forwards the notification messages to the `link`. Currently the relayer registers for `Tx` and `Block` notifications. It then extracts the IBC events from the `Tx` and generates a "NewBlock" event also for the block. Note that the notification may include multiple IBC Events. 

`chain light client` - one thread per chain that receives relayer requests, downloads and verifies headers, and returns the minimal header set in the response. In addition this thread should ensure latest locally stored state does not expire, i.e. when some timer fires it fetches and verifies the latest header. Timeout should be a fraction of the trusting period. Timer should be reset by the on-demand relayer requests. 

`link` - one thread per forwarding path. It receives events from the chains, performs queries and sends transactions synchronously.
____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by romac** [comment]
We should either close this now that #162 is merged, or rename it for `v1`, since there won't be any concurrency in `v0`.

**Comment by ancazamfir** [comment]
I would still like to say explicitly in someplace what happens when we start the relayer. Do we start the light clients? How do we interact with them? In listen mode (does this still work?), we have one monitor thread per chain, or used to. Do we still do this? Then state that all queries and transactions are blocking calls (will they stay like this in v0?). We can add to ADR004 or create a new one. We can change it over v0, v1, v2 releases to reflect the status quo.
