### ISSUE TITLE
Empty connection id may result in correct result - ConnOpenAck

### ISSUE THREAD

**Issue by livelybug** [informalsystems/ibc-rs#332]
## Summary of Bug

* This is the 3rd step in the connection opening handshake protocol.

* This is the 3rd step in connection opening handshake, the previous step should have already create the counter-party's connection, and set its state to TRYOPEN. As such, if the counter-party's connection id is empty, it would be an error. However, in ibc-rs, if the counter-party's connection id is empty, the response would be Ok. 
```
// Check that if the msg's counterparty connection id is not empty then it matches
// the old connection's counterparty.
let counterparty_matches = msg.counterparty_connection_id().as_str().is_empty()
|| old_conn_end.counterparty().connection_id() == msg.counterparty_connection_id();

if state_is_consistent && counterparty_matches {
    Ok(old_conn_end.clone())
}
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
The `counterparty_connection_id` has been added to the `ConnOpenAck` recently as part of the flexible identifier selection. If it is empty then the existing counterparty connection id is used and if all else is good the response will indeed be `Ok`.
This being said, the proper way to code this is to have `msg.counterparty_connection_id` as `Option<ConnectionId>`.
