### ISSUE TITLE
Modules: return owned value with ConnectionReader

### ISSUE THREAD

**Issue by CharlyCst** [informalsystems/ibc-rs#347]
## Crate

ibc

## Summary

Return `Option<ConnectionEnd>` instead of `Option<&ConnectionEnd>` in `ConnectionReader::connection_end`.

## Problem Definition

There are two motivations for this change:

1. The `ConnectionReader` trait's methods mostly return owned values (`client_state` returns a `Option<AnyClientState>`, `host_consensus_state` returns an owned value too), the only exception being `connection_end` which returns an `Option<&ConnectionEnd>`. For the sake of consistency, all methods should return either owned or borrowed values.
The `ClientReader` trait's methods return owned values, too.
2. More importantly, as I expect that most stores will use a raw byte storage format (tell me if I'm wrong) and thus need to de-serialize and allocate a new struct, it makes more sense to return objects rather than references. Due to the ownership system, returning data owned by the `connection_end` function can probably be worked around, but it doesn't seems to be ideal.

## Proposal

You can see the required changes [here](https://github.com/informalsystems/ibc-rs/compare/master...CharlyCst:connection_reader?expand=1).

Note that is is a breaking change.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by romac** [comment]
Agreed, on both points! 👍
