### ISSUE TITLE
Relayer CLI for MsgConnectionOpenConfirm

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#360]
## Crate

`relayer-cli` and probably `relayer`

## Proposal

Implement support for the following command:

`relayer tx raw conn-confirm <to-chain-B> <remote-chain-A> <conn-id-on-A> `  

- sends request to local client for `chain-A` to retrieve latest header `header_A` with height `ha`
- makes the following queries to `chain-A` at height `ha-1`:
         - the connection with id `conn-id-on-A` with proof, stores results in `connection` and `ack_proof`
- sends a `MsgUpdateState` to `chain-A` with: 
```
        client_id = client-A-on-B, 
        header = header_A, 
        signer = get_account(to-chain-B)
```
- sends a `MsgConnectionOpenAck` to `chain-A` with:
```
        connection_id = connection.counterparty_connection_id,
        ack_proof
        proofs_height=ha,
        signer = get_account(to-chain-B)
```

Note: `get_...` are functions that retrieve information from the relayer configuration.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
Believe this was done in #397
