### ISSUE TITLE
Split the `msgs.rs` in ICS02 in separate modules

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#367]
## Crate

`ibc`

## Summary

Similar to https://github.com/informalsystems/ibc-rs/issues/253, we should split the `msgs.rs` in ICS02/client into separate modules.

This is a follow-up work on #355.

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Fixed in #355
