### ISSUE TITLE
Implement relayer v0 event filtering

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#380]
## Crate

`relayer`

## Summary

At a given height the monitor may receive a number of events of different types. In V0, the relayer only processes the packet events and all the other events need to be filtered and dropped.

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Closed via #444
