### ISSUE TITLE
Relayer v0 config executor implementation

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#382]
## Crate

`relayer`

## Summary

Implement the config executor module as part of the relayer v0 architecture (#326).

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Closed via #449
