### ISSUE TITLE
Fix channel identifier format to be compatible with IBC-go

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#39]
## Summary of Bug

In the modules, we define a channel id to be represented as a `u64`.

https://github.com/informalsystems/ibc-rs/blob/baf0e3f60f37934cab89526f47f7cb6524f7d92c/modules/src/core/ics24_host/identifier.rs#L339

The code performs additional validation and requires channel IDs in received messages to have exactly the `channel-N` format. This is not part of the  IBC specification. Instead, channel identifiers should be validated as follows:
- should contain alphanumeric chars and
- should have a certain maximum length.

This problem only exists for channel IDs. Client and connection ID validation conforms with the IBC spec.

## Version

v0.15

## Acceptance Criteria

- [ ] Channel identifiers no longer restrict the format to `u64` based representation.
- [ ] Hermes has no assumptions on the format of channel identifiers aside from the validation rules described above.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
I think we should fix this in v1. I believe it also affects the relayer, if a chain uses something else than `channel-n` hermes will not relay for it.

**Comment by adizere** [comment]
> I think we should fix this in v1. I believe it also affects the relayer, if a chain uses something else than `channel-n` hermes will not relay for it.

Managed to confirm this:

```
$ hermes query channel end ibc-0 transfer chan-2
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/hermes query channel end ibc-0 transfer chan-2`
error: Invalid value "chan-2" for '<CHANNEL_ID>': channel identifiers are expected to be in `channel-{N}` format
```
