### ISSUE TITLE
Refactor versions methods in ICS03

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#393]
I think it would be nicer if these two methods `get_compatible_versions()` and `msg.counterparty_versions()` both return domain type objects `Vec<Version>` (instead of vector of strings). Then we can also avoid doing the conversion inside [pick_version](https://github.com/informalsystems/ibc-rs/blob/30422b1f793fcb0b0ca2a95a9d0e11b45a38f548/modules/src/ics03_connection/version.rs#L73), and pick version would only be concerned with the logic of computing intersection and picking version.

_Originally posted by @adizere in https://github.com/informalsystems/ibc-rs/pull/388#discussion_r520402095_

I agree. Started to do the changes earlier but they are more involved and was thinking to do it in a separate PR. However if you feel I should do it here let me know and will start on it.

_Originally posted by @ancazamfir in https://github.com/informalsystems/ibc-rs/pull/388#discussion_r520520772_

**Comment by ancazamfir** [comment]
Closed via #449
