### ISSUE TITLE
Permission in spec ics-004-channel

### ISSUE THREAD

**Issue by livelybug** [informalsystems/ibc-rs#406]
Hello,

I have a question about channel permissioning.

In spec 'ics-004-channel-and-packet-semantics', one of the desired properties is: 

```
Permissioning

Channels should be permissioned to one module on each end, ...

``` 
Will the property be implemented? 
Why I am asking is because from 'modules/src/ics04_channel/msgs/chan_open_init.rs', the following parameters, which are used to initialize a channel handshake, seem not able to meet the permissioning property.

```
        port_id: String,

        channel_id: String,

        version: String,

        order: i32,

        connection_hops: Vec<String>,

        counterparty_port_id: String,

        counterparty_channel_id: String,

        signer: AccountId,
```

It's appreciated if you can clarify it.
Thank you

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hi, and thanks for your interest in the permissioning model in ibc-rs.

> Will the property be implemented?

Yes, eventually. Most likely, permissioning will not be handled directly in the channel handshake messages (file `modules/src/ics04_channel/msgs/chan_open_init.rs`), but slightly higher on the stack. At the moment, however, support for permissioning has not made its way into any milestone (no part of ICS 005 module either). Note that our main focus is currently on the IBC Relayer, but we do plan to have the modules as well. Is there a specific use-case you have in mind?

**Comment by livelybug** [comment]
> Hi, and thanks for your interest in the permissioning model in ibc-rs.
> 
> > Will the property be implemented?
> 
> Yes, eventually. Most likely, permissioning will not be handled directly in the channel handshake messages (file `modules/src/ics04_channel/msgs/chan_open_init.rs`), but slightly higher on the stack. At the moment, however, support for permissioning has not made its way into any milestone (no part of ICS 005 module either). Note that our main focus is currently on the IBC Relayer, but we do plan to have the modules as well. Is there a specific use-case you have in mind?

Hi, Thank you for your reply.
No specific use-case in mind.
I am from Cdot network, developing substrate-ibc currently, and referring to ibc-rs frequently.
It's a question when studying ibc-rs.
Thank you

**Comment by andynog** [comment]
Hi @livelybug, I'm going to close this issue as per email response confirming this is not an issue anymore.
