### ISSUE TITLE
Add new query CLI: query ibc-transfer denom-trace 

### ISSUE THREAD

**Issue by DaviRain-Su** [informalsystems/ibc-rs#43]
## Problem Definition

For ics20 token transfer need a Query ibc-transfer denom-trace.

example: 
```shell
gaiad query ibc-transfer denom-trace CDC4587874B85BEA4FCEC3CEA5A1195139799A1FEE711A07D972537E18FDA39D --node https://rpc.testnet.cosmos.network:443

```

souece: https://tutorials.cosmos.network/tutorials/understanding-ibc-denoms/#

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ljoss17** [comment]
Hi @DaviRain-Su would the following query fit the requirements of this issue?

The command:

```hermes query transfer denom-trace <CHAIN_ID> --hash <HASH>```

And when successful would display the following:
```
Success:
  base_denom: <DENOM>
  path: <PATH>
```

**Comment by DaviRain-Su** [comment]
> 

This looks good.
