### ISSUE TITLE
Write to Substrate Storage

### ISSUE THREAD

**Issue by livelybug** [informalsystems/ibc-rs#433]
Hello,

We are trying to integrate ibc-rs in [substrate-ibc](https://github.com/cdot-network/substrate-ibc).

One of the steps is writing ibc-rs' data structure to substrate storage. Let's take `ics07_tendermint::consensus_state::ConsensusState` as an example.

### ics07_tendermint::consensus_state::ConsensusState 
* Let's name `ics07_tendermint::consensus_state::ConsensusState`  `ConsensusState` for short. 
* We consider `ConsensusState` belong to ibc-rs' `privateStore`.
* In [substrate-ibc](https://github.com/cdot-network/substrate-ibc), `privateStore`'s data is encoded by substrate's [SCALE Codec](https://substrate.dev/docs/en/knowledgebase/advanced/codec).
* To encode `ConsensusState` by SCALE, we create a similar data structure, which is encoded / decoded by SCALE, in substrate-ibc, as below:
```rust
use codec::{Encode, Decode};

#[derive(Encode, Decode)]
pub struct SbsConsensusState {
    pub timestam: u128, // datetime
    pub root: Vec<u8>,
    pub next_validators_hash: [u8; 32],
}
```
* Then convert the fields in  `ConsensusState` to []u8, and copy to the newly created `SbsConsensusState`.
* The description above is the general idea to write ibc-rs' `ConsensusState` to substrate storage. Is it the expected way to integrate ibc-rs, generally? It's really appreciated if you have any advice. 

Thank you

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hello,


There is one major interface that captures all the interaction between a chain, on the one hand, and the IBC module of that chain, on the other hand. This is the `ICS26Context` context:

https://github.com/informalsystems/ibc-rs/blob/65e4f268efc176d861d30949dc7bde049e0b3bb5/modules/src/ics26_routing/context.rs#L7-L9

Any chain that wishes to integrate ibc-rs will need to implement the above mentioned trait.

To get back to your question(s)

> One of the steps is writing ibc-rs' data structure to substrate storage. Let's take ics07_tendermint::consensus_state::ConsensusState as an example.

> The description above is the general idea to write ibc-rs' ConsensusState to substrate storage. Is it the expected way to integrate ibc-rs, generally? It's really appreciated if you have any advice.


The action of writing a `ConsensusState` into your underlying substrate storage would need to be implemented as part of  the [`store_consensus_state`](https://github.com/informalsystems/ibc-rs/blob/ec494b1342c69f2e6046333a7b2aa059f41c3a96/modules/src/ics02_client/context.rs#L56) method. Within this method, you can convert and encode the `ConsensusState` using your SCALE codec, and persist the data in that format. 

Three remarks here:

1. Note that there is also a [`consensus_state`](https://github.com/informalsystems/ibc-rs/blob/ec494b1342c69f2e6046333a7b2aa059f41c3a96/modules/src/ics02_client/context.rs#L17) method, which is for reading a `ConsensusState` for a given client. This is where you would implement decoding from `u8` into consensus state fields. The two methods for reading and writing a consensus state to/from storage are part of the `ClientReader` and `ClientKeeper` traits, respectively; both of these traits are part of `ICS26Context`.

2. These two methods for reading & writing a consensus state do not work directly with `ics07_tendermint::consensus_state::ConsensusState` but instead a higher-level wrapper type called [`AnyConsensusState`](https://github.com/informalsystems/ibc-rs/blob/8ddc68804c9bbafb6f9f925cb1536592e97c7d61/modules/src/ics02_client/client_def.rs#L259), which abstracts over different kinds of consensus states (not necessarily Tendermint-specific). You would need to handle downcasting from this type into the ICS07 specific consensus state type.

3. We have a [`MockContext`](https://github.com/informalsystems/ibc-rs/blob/8ddc68804c9bbafb6f9f925cb1536592e97c7d61/modules/src/mock/context.rs#L265) which implements the above mentioned methods as part of `ICS26Context` (and also methods for connection-specific objects), which you may find useful as a guiding example. You can see in that implementation that, for instance, our implementation of the `store_consensus_state` method does not do any conversion/encoding for storing a consensus state, but we simply add it in a hashmap:

https://github.com/informalsystems/ibc-rs/blob/8ddc68804c9bbafb6f9f925cb1536592e97c7d61/modules/src/mock/context.rs#L384-L401

**Comment by burtchensu** [comment]
@adizere many thanks, the answer is a great guide for our development!

**Comment by andynog** [comment]
Hi @livelybug, I'm going to close this issue as per email response confirming this is not an issue anymore.
