### ISSUE TITLE
Amino decoding for the tendermint client state included in the ABCI client query response

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#45]
## Summary
Amino decoding the tendermint client state included in the ABCI client query response is needed.
(the change should go [here](https://github.com/informalsystems/ibc-rs/tree/anca/add_consensus_query_cmd))

## Details
The query is performed here:
https://github.com/informalsystems/ibc-rs/blob/b603ccc6a0ddeaa37caf3d78dded3374d4a7056d/relayer/relay/src/query/client_state.rs#L116

The response is unmarshalled into ClientStateResponse: https://github.com/informalsystems/ibc-rs/blob/anca/add_consensus_query_cmd/relayer/relay/src/query/client_state.rs#L59-L64

with ClientState amino encoded for Tendermint concrete type.

ClientState trait is defined here: https://github.com/informalsystems/ibc-rs/blob/b603ccc6a0ddeaa37caf3d78dded3374d4a7056d/modules/src/ics02_client/state.rs#L23-L42

Tendermint concrete type: https://github.com/informalsystems/ibc-rs/blob/b603ccc6a0ddeaa37caf3d78dded3374d4a7056d/modules/src/ics07_tendermint/client_state.rs#L37-L62

amino registration in SDK:
https://github.com/cosmos/cosmos-sdk/blob/8d26b7fd1426bca90d2dca1ac9a9c021df2b4733/x/ibc/07-tendermint/types/codec.go#L12-L14

example of handling of response in Go relayer:
https://github.com/iqlusioninc/relayer/blob/5e71020ccf10db9d2f4af38a4bfd8c7c04e3da2c/relayer/query.go#L222-L228

**Comment by Liamsi** [comment]
Thanks for the summary @ancazamfir. Will open a PR against your branch :-)

**Comment by Liamsi** [comment]
BTW: https://github.com/cosmos/cosmos-sdk/pull/5704

**Comment by fedekunze** [comment]
FYI I'll update the PR above to use this tendermint branch: https://github.com/tendermint/tendermint/pull/4624

**Comment by ancazamfir** [comment]
Closing this as we will only do protobuf.
