### ISSUE TITLE
Create and submit a transaction to SDK/TM chain

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#47]
## Summary
Create and submit an IBC transaction to SDK/TM chain.

## Problem Definition
relayer needs to submit transactions that include the IBC messages and packets.

## Proposal
Evaluate https://github.com/iqlusioninc/crates/tree/develop/stdtx for submitting an IBC transaction.  Could be for ClientCreate or ClientUpdate, or other. 
Keystore doesn't have to be part of this if a workaround is found. We will deal with this in another issue.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
Let's start with a ConnOpenInit - https://github.com/cosmos/ics/tree/master/spec/ics-003-connection-semantics#opening-handshake

**Comment by ebuchman** [comment]
We should open a new issue listing the set of transactions so we can start knocking them off

**Comment by ebuchman** [comment]
Protobuf txs have not landed yet on the SDK so lets bump the milestone on this for now

**Comment by tarcieri** [comment]
Related:

- [stdtx: tracking issue for Protobuf transaction support (#459)](https://github.com/iqlusioninc/crates/issues/459)
- [tmkms tx-signer: post-Stargate roadmap](https://github.com/iqlusioninc/tmkms/issues/96)

**Comment by ebuchman** [comment]
This is effectively done in #242 but bringing it into the relayer-cli is now blocking on #243 or some other resolution of dependency hell.

**Comment by andynog** [comment]
Got a basic keystore working. You can test against branch `andy/tx-sign`. Running the command below

```
 ./target/debug/relayer -c ./relayer-cli/tests/fixtures/two_chains.toml keys restore ibc0 test "mixture fatigue fold federal hour frequent atom seek apart diesel armed start lawn hello milk say steak peasant wonder inquiry vague mind reduce rib"
```

Should give the result:
```
key restore result:  "55d4ae3492a831453fc273aff431fc76094e9b1c"
```

Next step is to use the private key to sign the message in the transaction.

**Comment by andynog** [comment]
I believe the tx signing is working but getting a `internal` error testing against stargate-4 chains (running with go relayer dev-env script)

```
./target/debug/relayer -c ./relayer-cli/tests/fixtures/two_chains.toml tx raw conn-init ibc0 ibc1 ibczeroclient ibconeclient ibczeroconn ibconeconn
     Message ConnectionOpenInitOptions { src_client_id: ClientId("ibczeroclient"), dest_client_id: ClientId("ibconeclient"), src_connection_id: ConnectionId("ibczeroconn"), dest_connection_id: ConnectionId("ibconeconn"), src_chain_config: ChainConfig { id: chain::Id(ibc0), rpc_addr: Tcp { peer_id: None, host: "localhost", port: 26657 }, account_prefix: "cosmos", key_name: "testkey", store_prefix: "ibc", client_ids: ["cla1", "cla2"], gas: 200000, trusting_period: 1209600s }, dest_chain_config: ChainConfig { id: chain::Id(ibc1), rpc_addr: Tcp { peer_id: None, host: "localhost", port: 26557 }, account_prefix: "cosmos", key_name: "testkey", store_prefix: "ibc", client_ids: ["clb1"], gas: 200000, trusting_period: 1209600s } }
TxRAW "0a9f010a9c010a2d2f6962632e636f72652e636f6e6e656374696f6e2e76312e4d7367436f6e6e656374696f6e4f70656e496e6974126b0a0d6962637a65726f636c69656e74120b6962637a65726f636f6e6e1a1c0a0c6962636f6e65636c69656e74120a6962636f6e65636f6e6e1a002205312e302e302a283235454635364341373935313335453430393336384536444238313130463232413442453035433212500a4e0a460a1f2f636f736d6f732e63727970746f2e736563703235366b312e5075624b657912230a2103af916c8d01cfdb919cc875539c759b4adb210f324d716c7ab4e4d74d408cc9ac12040a0208011a400bb6dd5cca614c3217eb75203e1b5559ee0f88d4f01314ec90223f2e50c4e1bd62fe531a1fb9311c989e227330274602c27f142f43ac70a2627f4387962c6e6a"
Tx Error Response: Response { code: Err(1), data: Data([]), log: Log("internal"), hash: transaction::Hash(D2969C20DA35EBA7B1883F1679BD3AE272B07DCCF3559B02FF41511DDD325AB4) }
conn init failed, error:  tx error: Message transaction failure: failed to initialize open connection: RPC error: RPC error: internal
```

if I send the tx via broadcast_tx_sync directly also get the error

```
curl localhost:26657/broadcast_tx_sync?tx=0x0a9f010a9c010a2d2f6962632e636f72652e636f6e6e656374696f6e2e76312e4d7367436f6e6e656374696f6e4f70656e496e6974126b0a0d6962637a65726f636c69656e74120b6962637a65726f636f6e6e1a1c0a0c6962636f6e65636c69656e74120a6962636f6e65636f6e6e1a002205312e302e302a283235454635364341373935313335453430393336384536444238313130463232413442453035433212500a4e0a460a1f2f636f736d6f732e63727970746f2e736563703235366b312e5075624b657912230a2103af916c8d01cfdb919cc875539c759b4adb210f324d716c7ab4e4d74d408cc9ac12040a0208011a400bb6dd5cca614c3217eb75203e1b5559ee0f88d4f01314ec90223f2e50c4e1bd62fe531a1fb9311c989e227330274602c27f142f43ac70a2627f4387962c6e6a
```
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "code": 1,
    "data": "",
    "log": "internal",
    "codespace": "undefined",
    "hash": "D2969C20DA35EBA7B1883F1679BD3AE272B07DCCF3559B02FF41511DDD325AB4"
  }
```

The error doesn't show up in the chains log so not sure where it's happening. Haven't been able to debug it directly on gaia or cosmos-sdk yet.

**Comment by andynog** [comment]
The `tx raw conn-init` command works now. Signing the message is working and the gaia chain (stargate-4) accepts the transaction. 

For now, I've added two parameters to the command

* signer-key (-k) -> you specify a key file (name and location) that will be used as the signer. This key seed file has a mnemonic (seed phrase) that can be used to retrieve the private key (BIP-39)
*  account_sequence (-s) -> this is the account sequence value, basically every time a tx is committed by the account this number increases

### Testing the transaction: 

1. Start two chains using the `dev-env` script from the [ovrclk/relayer](https://github.com/ovrclk/relayer) (checkout stargate-4)
2. After you run the script, the Go relayer will create a `data` folder for the chains. Open the key seed file `./data/ibc1/key_seed.json` for chain `ibc-1` and look for the account value

```
{"name":"user","type":"local","address":"cosmos1tqzwwr5hrnq2ceg5fg52m720m50xpfy08at7l9","pubkey":"cosmospub1addwnpepq08wntxejcla5hd93stgudw02htdpa9vu5a2ds8xkvmgrkrrpwlj6sdhkz6","mnemonic":"[MNEMONIC WORDS"}
```

3. In order to find the account sequence run:

`gaiad query account cosmospub1addwnpepq08wntxejcla5hd93stgudw02htdpa9vu5a2ds8xkvmgrkrrpwlj6sdhkz6 --home ./data/ibc1 --chain-id ibc1 --node tcp://localhost:26557`

this will return the sequence number at the end. Make a note of that, you will need this number as an argument to the transaction command.

```
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "0"
address: cosmos1tqzwwr5hrnq2ceg5fg52m720m50xpfy08at7l9
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: A87prNmWP9pdpYwWjjXPVdbQ9KzlOqbA5rM2gdhjC78t
sequence: "12"
```

4. Run the transaction command. We will try to initialize an `ibczeroconn2` connection

`cargo run --bin relayer -- -c ./relayer-cli/tests/fixtures/two_chains.toml tx raw conn-init ibc0 ibc1 ibczeroclient ibconeclient ibczeroconn2 ibconeconn -s 12 -k key_seed.json`

if you get an empty response it means the tx worked

`conn init, result:  []`

5. Check if the connection was created on `ibc-1` using the Golang relayer

`rly query connections ibc1 | jq .`

you should see an entry in the JSON file that points to the `ibczeroconn2` connection with state `STATE_INIT`

```
{
      "id": "ibczeroconn21",
      "client_id": "ibczeroclient",
      "versions": [
        "\n\u00011\u0012\rORDER_ORDERED\u0012\u000fORDER_UNORDERED"
      ],
      "state": "STATE_INIT",
      "counterparty": {
        "client_id": "ibconeclient",
        "connection_id": "ibconeconn",
        "prefix": {
          "key_prefix": "aWJj"
        }
      }
    },
```

**Comment by ancazamfir** [comment]
Looks good. A few observations:

1)
> In order to find the account sequence run:
gaiad query account cosmospub1addwnpepq08wntxejcla5hd93stgudw02htdpa9vu5a2ds8xkvmgrkrrpwlj6sdhkz6 --home ./data/ibc1 --chain-id ibc1 --node tcp://localhost:26557

here we need to pass the `address`, `cosmos1tqzwwr5hrnq2ceg5fg52m720m50xpfy08at7l9` in the example.

2)
If we try to create the same connection twice we should get an error. You should call `broadcast_tx_commit()` in `broadcast_tx()`, this will return the `Code` (success or failure) and some `Log` and `Data` to show in case of failure.

Currently it returns creating the connection second time returns:
 `conn init, result:  []`

Here are the current logs (removed some):
```
D[2020-10-27|13:31:55.968] Invalid tx                                   module=state code=2 log="\ngithub.com/cosmos/cosmos-...(*localClient).DeliverTxAsync
failed to execute message; message index: 0: connection handshake open init failed: ibczeroconn4: connection already exists"
```

**Comment by ancazamfir** [comment]
With `broadcast_tx_commit()` it returns something like:
```
conn init, result:  TxResult { code: Err(2), data: None, log: Log("\ngithub.com/cosmos/cosmos-sdk/x/ibc/core/03-connection/keeper.Keeper.ConnOpenInit\n\tgithub.com/cosmos/cosmos-sdk@v0.40.0-rc0/x/ibc/core/03-connection/keeper/handshake.go:27\ngithub.com/cosmos/cosmos-sdk/x/ibc/core/03-connection.HandleMsgConnectionOpenInit\n\tgithub.com/cosmos/cosmos-sdk@v0.40.0-rc0/x/ibc/core/03-connection/handler.go:13\ngithub.com/cosmos/cosmos-sdk/x/ibc/core.NewHandler.func1\n\tgithub.com/cosmos/cosmos-sdk@v0.40.0-rc0/x/ibc/core/handler.go:36\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs\n\tgithub.com/cosmos/cosmos-sdk@v0.40.0-rc0/baseapp/baseapp.go:692\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx\n\tgithub.com/cosmos/cosmos-sdk@v0.40.0-rc0/baseapp/baseapp.go:653\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx\n\tgithub.com/cosmos/cosmos-sdk@v0.40.0-rc0/baseapp/abci.go:271\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/abci/client/local_client.go:87\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/proxy/app_conn.go:85\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/state/execution.go:313\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/state/execution.go:138\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:1569\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:1487\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:1420\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:1459\ngithub.com/tendermint/tendermint/consensus.(*State).addVote\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:2044\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:1846\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:803\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine\n\tgithub.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/consensus/state.go:752\nfailed to execute message; message index: 0: connection handshake open init failed: ibczeroconn4: connection already exists") }
```
we will need to get a shorter explanation for that ` Err(2)`

**Comment by andynog** [comment]
Thanks @ancazamfir  I will look into those error cases for an existing connection.
