### ISSUE TITLE
Add --json flag to force JSON output in relayer CLI

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#500]
## Crate

`relayer-cli`

## Summary

Add a `--json` flag to force JSON output in all the CLI commands.

### Why do we need this?

- @andynog expressed the need for JSON output as part of his work on the CI
- other users may want to use the CLI programmatically without relying on using regular expressions to parse the output of the commands

## Proposal

- Add a `--json` flag to all commands, which enables JSON output.
- When this flag is set, a command should not use the `status_ok!`, `status_info!` and `status_err!` macros but instead emit a single-line JSON-encoded message.
- The message _must_ include a `status` field which must be set to one of `"success"`, `"info"`, or `"error"`.
- The message _should_ include a `msg` field with a human-readable description of the result of the command.
- The message _may_ include other fields.

### Example:

```json
{"status": "success", "msg": "client created", "client_id": "tendermint-07"}
```

```json
{"status": "info", "msg": "no action taken"}
```

```json
{"status": "error", "msg": "client not found", "client_id": "tendermint-07"}
```

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Maybe also take into consideration the following problem highlighted elsewhere (in #469):

Sort-out error messages and make them consistent. For example, updating a non-existing client results in a panic, but querying for a non-existing client returns an error. The commands are:
> rrly -c loop_config.toml tx raw update-client ibc-0 ibc-1 07-tendermint-X
> rrly -c loop_config.toml query client state ibc-0 07-tendermint-X

**Comment by romac** [comment]
Agreed!

On top of that, we should also return a proper UNIX error code on exit, via [`abscissa_core::application::fatal_error`](https://docs.rs/abscissa_core/0.5.2/abscissa_core/application/fn.fatal_error.html). See the [`light rm` command](https://github.com/informalsystems/ibc-rs/blob/76134e257113ab4fe883346a4d97f66848f392cc/relayer-cli/src/commands/light/rm.rs#L70-L78) for an example of how to do this.

**Comment by adizere** [comment]
I'm thinking we should make `--json` always on and simply stop using status_ok!, status_info! and status_err! macros altogether.

**Comment by ancazamfir** [comment]
I like the way the tx CLIs return the result of the transaction, decoded with the interesting information. It would be nice to include that. For example channel `openInit` is confirmed with the `OpenInitChannel` event included in the result. Maybe we can have something like:
```
{"status": "success",  "msg": {"OpenInitChannel": {"height": "1", "port_id": "transfer", "channel_id": "channel-3", "connection_id": "connection-0", "counterparty_port_id": "transfer", "counterparty_channel_id": null}}}
```

Or `result` instead of `msg`.
We also need to add similar format for queries (see @adizere 's #506) so we need a proposal to unify the Tx and query CLIs.

**Comment by romac** [comment]
Sounds good.

So, should we say that:

- the relayer _must_ only output JSON (specifically, [JSON Lines](https://jsonlines.org)) on `stdout`
- the relayer _may_ output arbitrary text (including ANSI escape codes) on `stderr`

This would allow us to pipe the relayer stdout to [`jq`](https://stedolan.github.io/jq/) while also retaining debug and tracing information on stderr.

What do you think?

**Comment by romac** [comment]
If we stick with the [`tracing`](https://docs.rs/tracing/0.1.22/tracing/) crate, we may be able to support both human-readable output and JSON output by [configuring the tracing subscriber](https://docs.rs/tracing-subscriber/0.2.15/tracing_subscriber/fmt/index.html) at runtime, eg. based on a command-line flag, or an environment variable.

What remains to be seen is if that's doable with Abscissa,

**Comment by adizere** [comment]
I like the idea of configuring the output format at runtime. After a bit of digging, Abscissa [has support](https://docs.rs/abscissa_core/0.5.2/abscissa_core/command/struct.EntryPoint.html) for `verbose` and `help` global flags, but does not support, out-of-the-box, something like a global `json` command-line flag. So configuring JSON globally for the whole application seems easier based on environment variables.


But to focus on @andynog's work on CI, I'm curious what's important there..
- Is JSON output necessary for queries or txs or both?
- Is non-JSON output ever useful in the CI?
- Is anything beside the `"status"` field in the JSON output parsed by the CI?

**Comment by ancazamfir** [comment]
> Is JSON output necessary for queries or txs or both?

Both

> Is non-JSON output ever useful in the CI?

Probably not

> Is anything beside the "status" field in the JSON output parsed by the CI?

Yes, for example IDs should be extracted from the init/ create Tx results and used in subsequent CLIs. Verification should also issue query commands and check fields from the output.

**Comment by ancazamfir** [comment]
Since Andy is working on CI already, can we just default everything to json for now and we look at a nicer output for us/ human users later? The json output is actually not too bad.

**Comment by andynog** [comment]
I agree that Json output for tx and query should be the default. Eventually we might have a better configurable logging mechanism (support multiple log outputs and formats). 

But for now, automating things will be easier I believe sing Json and is the way to go. It's easier to programmatically extract values then trying to parse text which is difficult and error prone.
