### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by en** [informalsystems/ibc-rs#508]
## Crate

[substrate-ibc](https://github.com/cdot-network/substrate-ibc)

## Summary

Improve ibc-rs to support no_std

## Problem Definition

As substrate is a modular framework, assuming ibc is an optional component, we should implement it as a pallet.

ref: [Your Pallet's std Feature](https://substrate.dev/docs/en/tutorials/create-a-pallet/#your-pallets-std-feature)

Currently, ibc-rs, which is a dependent library of substrate-ibc, does not support no_std. After the integration of ibc-rs, substrate-ibc can no longer support no_std.

Although we can choose not to compile runtime to wasm to continue the integration, the chain using substrate-ibc loses the feature that can be upgraded without restarting.

## Proposal

This feature is not urgent, but we hope ibc-rs will eventually support no_std.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Thanks for informing us on these requirements! I'll close this issue and we'll keep the older #29 open to track the work & discussions.
