### ISSUE TITLE
Module scoping in the libraries

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#522]
## Crate

`ibc` and `relayer`

## Summary

We should consider exporting modules with more restrictive scoping, e.g., `pub(crate)` instead of `pub`.

## Original discussion

I actually wanted to ask this before, why don't we use the crate scope more often. I believe in this case for example all mods, except application, can be public at crate level.

_Originally posted by @ancazamfir in https://github.com/informalsystems/ibc-rs/pull/518#discussion_r557330247_

I don't thin it matters too much for the `relayer-cli` crate, but yeah in general it wouldn't hurt either to make more modules crate scoped, to limit the surface area of our libs.

_Originally posted by @romac in https://github.com/informalsystems/ibc-rs/pull/518#discussion_r557340030_

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Let's keep exporting most things publicly until we get a better idea of what is the surface area needed by downstream users of the `ibc` and `ibc-relayer` crate.
