### ISSUE TITLE
Compilation failure due to mismatching `bitcoin` dependencies in v0.0.6

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#525]
## Crate

`relayer`

## Description

version: 239fd6f

We are seeing some github action failures.
The error seems to be with dependencies. 
Perhaps originating from the `bitcoin` crate, but that may be misleading, as even fixing this dependency to `= 0.25` [the error still appears](https://github.com/informalsystems/ibc-rs/pull/515/checks?check_run_id=1707646038):

```
...
   Compiling secp256k1-sys v0.4.0
   Compiling secp256k1 v0.20.0
   Compiling bitcoin v0.26.0
   Compiling relayer v0.0.6 (/Users/adi/Hammers/ibc-rs/relayer)
error[E0277]: the trait bound `DerivationPath: From<StandardHDPath>` is not satisfied
   --> relayer/src/keyring/store.rs:140:61
    |
140 |             .and_then(|k| k.derive_priv(&Secp256k1::new(), &DerivationPath::from(hd_path)))
    |                                                             ^^^^^^^^^^^^^^^^^^^^ the trait `From<StandardHDPath>` is not implemented for `DerivationPath`
```

____

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
I still don't understand why `bitcoin v0.26.0` is pulled when `=0.25` is specified. And also why we don't see this when running locally.

**Comment by ancazamfir** [comment]
Ok, i see it now after `cargo upate`, thanks Adi!

**Comment by adizere** [comment]
On master, cargo computes the following dep graph, as far as I can tell:

```
relayer v0.0.6 (/Users/adi/Hammers/ibc-rs/relayer)
├── anomaly v0.2.0 (*)
├── async-trait v0.1.42 (proc-macro) (*)
├── bech32 v0.7.2
├── bitcoin v0.25.2     <-------
├── hdpath v0.6.0
│   ├── bitcoin v0.26.0 <-------
```

where the two bitcoin versions differ.
This happens because hdpath [specifies](https://github.com/emeraldpay/hdpath-rs/blob/5762d6904af1698c933db37794a00b1551e6eecc/Cargo.toml#L16-L19)

```
bitcoin = { version = ">= 0.21",
```

Still, I don't understand why having the two versions of bitcoin (0.25.2 and 0.26) would lead to this issue.
