### ISSUE TITLE
relayer-cli build fails without `--all-features`

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#533]
## Crate
`relayer-cli`

## Summary of Bug
Rust 1.49
```
cargo build -p relayer-cli
```
fails with:
```
error[E0277]: the trait bound `DerivationPath: From<StandardHDPath>` is not satisfied
   --> relayer/src/keyring/store.rs:140:61
    |
140 |             .and_then(|k| k.derive_priv(&Secp256k1::new(), &DerivationPath::from(hd_path)))
    |                                                             ^^^^^^^^^^^^^^^^^^^^ the trait `From<StandardHDPath>` is not implemented for `DerivationPath`
    |
    = help: the following implementations were found:
              <DerivationPath as From<&'a [ChildNumber]>>
              <DerivationPath as From<Vec<ChildNumber>>>
    = note: required by `std::convert::From::from`

error: aborting due to previous error
```

It succeeds when run with all-features:
```
cargo build -p relayer-cli --all-features
```

## Version
v0.0.6
master (133524aeeb941ba869fd1ccc177c62913d47ea39)

## Steps to Reproduce
```
cargo build -p relayer-cli
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
I can't reproduce the error on my machine with a fresh clone.

Here are the steps I followed:

1. `$ cd /tmp`
2. `$ git clone https://github.com/informalsystems/ibc-rs.git`
3. `$ git rev-parse --short HEAD` ==> 133524a
4. `$ cargo build -p relayer-cli`

```
Finished dev [unoptimized + debuginfo] target(s) in 2m 14s
```

Can you please try with a fresh clone as well if you haven't already?

Alternatively, you could try running `cargo update` in case you have an outdated `Cargo.lock` file.

**Comment by greg-szabo** [comment]
Possibly it must have been an outdated `Cargo.lock`. Now I can't reproduce the issue either. Thanks for looking into it!
