### ISSUE TITLE
Cleanup output of relayer commands 

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#536]
## Crate
relayer
relayer-cli

## Summary of Bug
All debugs are currently `info!` or same level, making the output very chatty.

## Version
master

## Steps to Reproduce
Run the CLIs
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
@vitorenesduarte mentioned:
```
It’s possible to filter logs by application. For example, RUST_LOG=hyper=info would only should logs for hyper.
(Nevertheless, the first line “Message CreateClient for…” in the log above doesn’t seem to come from tracing, so this probably won’t help)
...
it’s also possible to say something like RUST_LOG=app1=info,app2=debug

```

**Comment by andynog** [comment]
I thought that the RUST_LOG would work but apparently there are some messages (see below) that use status_info! macro from abscissa and that seems that it doesn't use log or tracing. So not sure there's a way to control, seems a custom macro.

https://github.com/informalsystems/ibc-rs/blob/1a77c0af20dee97d45096c4bcafe189c6a4f7689/relayer-cli/src/commands/tx/client.rs#L83-L89
