### ISSUE TITLE
Relayer documentation

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#542]
## Summary

Documentation for the Rust Relayer

## Problem Definition

Currently the documentation for setting up a relayer with two chains is outdated or missing. There's not current easy way to setup a relayer without some previous knowledge on how to do it or ask for assistance. 

## Proposal

Create initial documentation and instructions up to date for the relayer. 

Create docs using some framework e.g. mdbook or VuePress that can render the site automatically when docs are updated.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
- [ ] cleanup the sample .toml configurations: there's currently three of them under version control and it's not clear why and what are each used for: 
    - `relayer/tests/config/fixtures/relayer_conf_example.toml` and 
    - `relayer-cli/tests/fixtures/two_chains.toml` and 
    - `relayer/tests/config/fixtures/simple_config.toml`.
