### ISSUE TITLE
Inconsistent implementations of CLI commands

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#573]
## Crate

`relayer-cli`

## Summary

We should refactor and make the fields in command structs more consistent.
This is for the sake of code hygiene and maintainability; it's not user visible.

See [the discussion](https://github.com/informalsystems/ibc-rs/pull/559#discussion_r565183958)

and todo:

https://github.com/informalsystems/ibc-rs/blob/4e13a10e5f35528e3f9870b3ef21301686633c3b/relayer-cli/src/commands/query/client.rs#L22-L24

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Is this a dup of #572?

**Comment by adizere** [comment]
Closing this in favor of #572.
