### ISSUE TITLE
Speed up CI by re-using relayer binary for E2E tests

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#582]
We could likely significantly speed up the end-to-end test job by copying the relayer binary built as part of the `Rust` job into the image instead of rebuilding it.

___

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
The original CI infrastructure was done as part of https://github.com/informalsystems/ibc-rs/pull/544.
This was later extended with comprehensive tests in https://github.com/informalsystems/ibc-rs/pull/571.

The work in the original CI consists of three docker images:
- two of them were gaia chain images called "informaldev/ibc-0" and "informaldev/ibc-1" 
- the third image is for the relayer, and is dependent on the gaia images; this is built on-the-fly upon every commit to a pull-request

There are two basic differences between the original work and the new PR:
1. the relayer binary is now compiled as part of the Github action, and then this binary is made available (`cp`) to the relayer docker image:

https://github.com/informalsystems/ibc-rs/blob/81af0b0b0418c4a365617e3cbf6006db80a3c831/.github/workflows/e2e.yaml#L13-L17


 in the original work, the binary was compiled directly inside the `docker-compose` task:

https://github.com/informalsystems/ibc-rs/blob/148e196308a217542f2dc49bfe5881362bf1013d/ci/relayer.Dockerfile#L28

2. the `cargo build` command for obtaining the relayer binary no longer relies on `--all --release`, shortening the build cycle by ~5 minutes (almost halved)
