### ISSUE TITLE
Documentation of e2e Python library

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#591]
## Crate

End-to-end testing library written in Python (See `e2e` folder)

## Summary

Add documentation (README, doc comments, section in guide) for the Python library forend-to-end testing.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Superseded by #797.
