### ISSUE TITLE
Clarify relayer algorithm with respect to consensus state changes via clientUpdates

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#61]
## Summary
In the presence of multiple realyers or relayer threads, it can happen that a consensus update will fail if its height is smaller than the client state height.
This issue is here just to facilitate discussion and its resolution will be incorporated in the Relayer ADR.

## Problem Definition
The relayer scans IBC store for a source chain and creates datagrams for a destination chain. Many of these datagrams include proofs that must verify against a specified client consensus state.
Due to the fact that the `appHash` for block `n` is stored in `n+1,` a typical relayer action for X will include:
```
 queryX(X, h-1) -> {x, proof, h-1}
 getHeader(h) -> header
 sendMsgs(MsgClientUpdate{cl, h}, MsgX{X, proof, h})
```
One or both of the above messages may fail. This issue is concerned with failure of `MsgClientUpdate`, when it can happen and how it can be solved.

## Proposal
It is possible that there are two relayers scanning for different items, X vs Y, and they require consensus state (CS) updates on the same destination chains but at different heights. This could result on one of the relayer transactions to fail, as a `clientUpdate` for height `h` fails if the latest client height is `H >=h`.

Here is a proposal of overall handling for message X relaying in general that covers this scenario. 
We assume relaying for A->B path, the client on B has been created and maybe updated a number of times. The relayer in this example periodically scans the source chain A, but it would work the same for event driven relayer. Here are the steps:
- relayer gets the latest height `hx` on A and queries the client height on B, `ha`.
- takes the maximum of the two, `h = max(hx, ha)`
- queries for X at `h-1` and gets the proof `p`
- with `ha` being the latest trusted header, it gets header `h` and any intermediate headers
- at this point the relayer builds a number of `MsgUpdateClient(hi)` datagrams and the `MsgX(X, p, h)` datagram, and sends them in a transaction to B.
  - if `hx < ha` there will be no `MsgUpdateClient` datagrams
- if the transaction result indicates client update failure then(*):
  - it queries the (new) latest state of client on A, `hA` and queries X at `ha-1`
  - sends `MsgX(X, p, hA)` to A

If a failure is seen for the `MsgX..` transaction at either step, it is probably safe for the relayer to ignore it, as it could be caused by another "competing" relayer having submitting the same transaction for X. This needs more investigation but not part of this issue which is only for CS update failures.
(*) 
- Not clear if the result includes failure code/ codespaces for all failed transactions (? I only see one). It is possible that `clientUpdate` fails and `MsgX` succeeds if `ha` CS is present on B. 

Here is a diagram for the above.
![CS_handling](https://user-images.githubusercontent.com/6361427/81168554-81477900-8f97-11ea-8a0b-ae58834cd108.jpeg)

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by cwgoes** [comment]
One option worth considering is that state machines should be relatively easily able to implement an idempotent version of `MsgUpdateClient` (thereby trying to receive the packet even if another relayer already updated the client).

To alleviate race problems somewhat, the ICS 7 specification can be changed to:
- Allow submission of older headers (within some time bound) to provide intermediate consensus states
- Allow submission of header updates starting from an older (non-current) header within a bound

Alternatively, applications could elect to commit to old consensus states (in the application state), which could then be verified (instead of using the light client update algorithm from an old state).

**Comment by milosevic** [comment]
I think that this is more or less what we have been discussing with @ancazamfir. It seems that changes to the spec are minimal, and there are nice benefits of it.

**Comment by ancazamfir** [comment]
One clarification, this issue and its description is for a relayer logic that does not require changes in ICS07 and implementation. 
It is not as nice as with the changes we imagine in ICS07.  However, for now we will move with this in the Rust implementation and if/ when the modifications to ICS07 and SDK are ready we will make the changes in the realyer which I believe, after drawing the flow for both, shouldn't be significant.  
Also, probably some thought needs to go into allowing creation of older consensus states in the app, how verification will work in this case and the implications (e.g. MsgUpdateClient changes).

To move things forward, @Chris should we create an issue for cosmos/ics? And continue the discussion there?

**Comment by cwgoes** [comment]
(I am @cwgoes, let's not ping the other Christopher)

An issue for cosmos/ics would be perfect, I can make the changes quickly.

**Comment by ancazamfir** [comment]
> (I am @cwgoes, let's not ping the other Christopher)

sorry about this!
Here is the issue: https://github.com/cosmos/ics/issues/420

**Comment by ancazamfir** [comment]
Documented now in https://github.com/informalsystems/ibc-rs/pull/28.
