### ISSUE TITLE
modules: Fix panic in conn open try when no connection id is provided

### ISSUE THREAD

**Issue by vitorenesduarte** [informalsystems/ibc-rs#626]
## Crate

modules

## Summary of Bug

Currently, a conn open try can only succeed if some `previous_connection_id` is provided in the `MsgConnectionOpenTry`:
https://github.com/informalsystems/ibc-rs/blob/b1b9dac6132a2fd2a86fa1c6f0179f47db3e3454/modules/src/ics03_connection/msgs/conn_open_try.rs#L26-L35
However, to have a valid `previous_connection_id`, one has to have a successful conn open try. This circular dependency makes it so that it's never possible to have successful conn open try.

## Version

277426eaa1ffbdd201cd3b7de8b1db387ecccf9b

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Fixed in #615
