### ISSUE TITLE
Connection create CLI

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#630]
## Crate

`ibc-relayer` and `ibc-relayer-cli`

## Summary

Sub-issue of #628.
> Establish a new IBC connection (not channel) between two chains. Either have a script, or builtin functionality to keep retrying the process until it succeeds.

- `create connection <chain-a-id> <chain-b-id>`
    - Optional: `[--delay <delay>]`
- `create connection <chain-a-id> --client-a <client-a-id> --client-b <client-b-id>`
    - Optional: `[--delay <delay>]`

### Historical info

Originally, we wanted this CLI to resemble the [channel handshake command](https://hermes.informal.systems/relayer_loop.html#example-2), as follows:

```bash
hermes connection handshake ibc-0 ibc-1 client-ibc-0 client-ibc-1
```

In the meantime, however, we made a more formal list of use-cases we want to support in v0.2.0 which was captured in [ADR 006](https://github.com/informalsystems/ibc-rs/blob/master/docs/architecture/adr-006-hermes-v0.2-usecases.md), and fleshed out a concrete decision for the connection handshake CLI, consistent with other CLIs.

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Could we discuss/ review https://github.com/informalsystems/ibc-rs/issues/637 before starting on this issue?
