### ISSUE TITLE
modules: Cleanup access to the state in handler messages

### ISSUE THREAD

**Issue by vitorenesduarte** [informalsystems/ibc-rs#631]
## Crate

modules

## Problem Definition

Currently we have getters for `pub` fields in the handler messages.

References:
- https://github.com/informalsystems/ibc-rs/pull/601#discussion_r572743614
- https://github.com/informalsystems/ibc-rs/pull/618#discussion_r571911838

## Proposal

Decide on a convention (likely just use `pub`) and apply it to all handler messages.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Wizdave97** [comment]
@vitorenesduarte @adizere is your suggestion to remove the getters and allow direct access to the properties?
