### ISSUE TITLE
Cannot submit a tx on a chain that has a Bech32 prefix other than "cosmos"

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#635]
## Crate

modules, ibc-relayer

## Summary of Bug

Testing the ibc-relayer-cli against two chains, one is an Akash chain and the other a Simapp chain. When I tried to perform a `tx raw create-client` got an error that `invalid Bech32 prefix`

## Version

v0.1.0

## Steps to Reproduce

* Spin two chains, with at least one chain where the address prefix is not `cosmos` e.g. Akash is `akash`
* Try to submit a `tx raw`

Basically the string "cosmos" is hard-coded in a couple of places. The logic needs to change to use the `account_prefix` value from the chain configuration (config file)

One location that needs to change is here https://github.com/informalsystems/ibc-rs/blob/b654af39c0c658d831cff42ccb11ac5562a43793/modules/src/address.rs#L11

And I believe there's another location here https://github.com/informalsystems/ibc-rs/blob/b654af39c0c658d831cff42ccb11ac5562a43793/relayer/src/keyring/store.rs#L149

Using the `account_prefix` might be the best option but might require some refactoring because the config (or this value) would need to be passed as a parameter to this functions
____

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by andynog** [comment]
Doing some investigation on this issue, realised that the `account_to_string` method from `address.rs` in `modules` is used throughout the modules crate. But I have the feeling this function and the `string_to_account` method are a lot more closer to a chain implementation, maybe we should move this to the `relayer` crate and invoke the function from there because we need the config to know what is the `account_prefix`

For example, here's the `create_client` message, we should modify the signer in all these `from` Msg functions
https://github.com/informalsystems/ibc-rs/blob/b654af39c0c658d831cff42ccb11ac5562a43793/modules/src/ics02_client/msgs/create_client.rs#L104

Any thoughts @ancazamfir or @romac ?

**Comment by ancazamfir** [comment]
We have a long due issue on this https://github.com/informalsystems/ibc-rs/issues/219. We don't really need the account info in the domain type messages. I would rather fix this issue now instead of adding a short-diff patch to fix this.

**Comment by adizere** [comment]
FYI also #416
