### ISSUE TITLE
Replace rust-crypto crate with alternatives

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#641]
## Crate

* ibc-relayer
* ibc-relayer-cli

## Summary of Bug

Currently when running `cargo audit` there's a warning about `rust-crypto` is unmaintained

## Version

v0.1.0

## Steps to Reproduce

`cargo audit`

```
Crate:         rust-crypto
Version:       0.2.36
Warning:       unmaintained
Title:         rust-crypto is unmaintained; switch to a modern alternative
Date:          2016-09-06
ID:            RUSTSEC-2016-0005
URL:           https://rustsec.org/advisories/RUSTSEC-2016-0005
Dependency tree: 
rust-crypto 0.2.36
├── ibc-relayer 0.1.0
│   └── ibc-relayer-cli 0.1.0
└── bitcoin-wallet 1.1.0
    └── ibc-relayer 0.1.0
```

We need to find alternative crypto crates, possible use the same as tendermint-rs for hashing and if used by the tx sign logic we should find alternatives
____

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Dup of #352 ? (pls use search before submitting new bug)
