### ISSUE TITLE
Update Relayer ADR

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#67]
## Summary
More work that needs to be done on the Relayer ADR:
- remove parts that do not belong to the ADR
- add the details of the generic IBC Event handler and reduce the details on the actual handshake datagrams

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Closing as outdated.
