### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Fraccaman** [informalsystems/ibc-rs#679]
## Crate
- ibc-relayer-cli

## Summary of Bug

First of all, pretty well done documentation. I think there are a couple of wrong commands in [Channel handshake](https://hermes.informal.systems/tutorial_chan_open_raw.html) and [Packet relaying on existing path](https://hermes.informal.systems/tutorial_relay_existing_path.html). Basically most of them are missing FLAGS. 
For example: 
`hermes tx raw chan-open-ack ibc-0 ibc-1 connection-0 transfer transfer channel-0 channel-1`
 should be `hermes tx raw chan-open-ack ibc-0 ibc-1 connection-0 transfer transfer -d channel-0 -s channel-1` (it throws an error otherwise)

Also, I have another question about hermes and the [Connect the chains using raw transactions](https://hermes.informal.systems/tutorial_raw.html). 
Let's say I want to create a client. Following the documentation I use:
```hermes tx raw create-client ibc-0 ibc-1```. 
Now, I need to to the same for `ibc-1`. Using the following command
```hermes tx raw create-client ibc-1 ibc-0``` 
I receive, as output, a json containing the same `client_id` as the previous command, i.e: `07-tendermint-0`, but with `revision_number` is equal to 1.
The same happens for channel and connection, they are always the same. Instead, reading the documentation, they always differ.
Is this okay or am I making something wrong?

## Version

- hermes: `building from master branch (25c4da14c86ffcf0c7f1e191eb259b74666d48a0)`
- rustc: `1.50.0 (cb75ad5db 2021-02-10)`
- cargo: 1.50.0 (f04e7fab7 2021-02-04)
- gaiad: `4.0.0`

## Steps to Reproduce

I just followed the commands as in [here](https://hermes.informal.systems/tutorial_raw.html)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by milosevic** [comment]
Hey @Fraccaman, thanks for creating the issue. I am happy to see you are around. Can I ask you if you are following this for fun or you are working on some related project?

**Comment by Fraccaman** [comment]
Hi @milosevic ! Happy to hear from you too! I'm testing stuff out as I'm working on some projects with heliax :) (the company I'm working atm)

**Comment by romac** [comment]
> The same happens for channel and connection, they are always the same. Instead, reading the documentation, they always differ.
> Is this okay or am I making something wrong?

That's totally okay, but it is possible to set things up so that the identifiers line up with the documentation. We address this in the "Identifiers" section of the tutorial: https://hermes.informal.systems/tutorial_raw.html#identifiers

> For clarity, the tutorials run on a setup where the identifiers allocated to the client, connection and channel on ibc-0 are 07-tendermint-0, connection-0 and channel-0 respectively. Identifiers allocated to the client, connection and channel on ibc-1 are 07-tendermint-1, connection-1 and channel-1 respectively.
> 
> If you want to ensure you get the same identifiers while following the tutorial, run the above three commands once on ibc-1 before going over the next sections.

**Comment by Fraccaman** [comment]
Okay, I'll try again but somehow I wasn't able to match the documentation.

**Comment by andynog** [comment]
Hi @Fraccaman the documentation will have a lot of updates for the next release. Hopefully things will be more clear. Will revisit this when the next release is out.

**Comment by adizere** [comment]
Closing this as outdated.
