### ISSUE TITLE
Update images, CI and scripts to use gaia v4.1.0

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#702]
## Summary
We should update the docker images, CI and scripts to use gaia `v4.1.0`.
We should also have a process in place to track new gaia releases and do the required changes to our CI and scripts.
 

## Problem Definition
gaia v4.1.0 includes SDK v0.42.0 that, among other things, has the support required for misbehavior detection. I expect this  (or later version) would be used in the next upgrade.

## Proposal

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by andynog** [comment]
we should use gaia 4.1.0 that was released today https://github.com/cosmos/gaia/releases/tag/v4.1.0
