### ISSUE TITLE
Cannot run relayer e2e test script locally

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#710]
## Crate

ibc-relayer-cli

## Summary of Bug

Get error when running the command `docker exec relayer /bin/sh -c /relayer/e2e.sh

## Version

v0.1

## Steps to Reproduce

Run the commands from `e2e.yml` in your local machine (not in the CI environment). Used to work but I think the logic changed to build `hermes` locally and copy to the docker image as opposed to the old logic of building it inside the container.

Maybe there's a workaround but couldn't find in the documentation. 

This is trying to run on a MacOS, get error `/relayer/e2e.sh: /relayer/e2e.sh: /usr/bin/hermes: Exec format error`
____

## For Admin Use

- [ ] Not duplicate issue
- [X] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
I think this is no longer relevant. Please reopen if necessary.
