### ISSUE TITLE
Account number hardcoded

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#752]
## Crate

ibc-relayer

## Summary of Bug

Account number is hard-coded to '0' in the logic to sign a transaction

## Version

v0.1.1

## Steps to Reproduce

When using a key for an account that is not '0' the `tx raw` transaction will not work. For example testing with a chain where the key was for an account with number '1' the tx failed with unauthorized. 

Change the logic to use the account number retrieved from the chain.
____

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by romac** [comment]
@andynog Can you please open a PR for your fix if it's ready?

**Comment by andynog** [comment]
> @andynog Can you please open a PR for your fix if it's ready?

Hi @romac this was fixed on PR #753, not sure why the issue was not closed

**Comment by romac** [comment]
Oh right, will close it then :)
