### ISSUE TITLE
Gas fee has denom and amount hard-coded

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#754]
## Crate

ibc-relayer

## Summary of Bug

Currently in the `sent_tx` method of the `cosmos.rs` file, the gas fee logic has the denom (`stake`) and amount (`

https://github.com/informalsystems/ibc-rs/blob/9e6848494332ffa8283b92c113beea5833e100bc/relayer/src/chain/cosmos.rs#L182

## Version

v0.1.1

## Steps to Reproduce

There are no steps to reproduce. Currently with this logic there's no way to submit transactions to a chain if the gas fee denom is not `stake`. And the gas fee amount should also be dynamic (allowed to be specified trough a command line parameter)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Trying a transaction on `akashnet-2` I get this:
```{"status":"success","result":{"ChainError":"check_tx reports error: log=Log(\"insufficient fees; got: 10000stake required: 75000uakt: insufficient fee\")"}}```

**Comment by andynog** [comment]
This issue needs to be fixed to allow custom fee and denom
