### ISSUE TITLE
Introduce a newtype wrapper for the timestamp

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#758]
## Crate

`ibc`

## Summary

We could introduce a newtype wrapper for the timestamp, here and in other places where we currently use a `u64`, eg. a `pub struct Timestamp { seconds: u64 }` in the `host` module.

_Originally posted by @romac in https://github.com/informalsystems/ibc-rs/pull/737#discussion_r597109688_

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by soareschen** [comment]
To keep a better semantics of tracking the time, I will try to use define `TimeStamp` as a newtype over [`chrono::DateTime`](https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html).
