### ISSUE TITLE
Add chain ID to the connection section of the relayer configuration

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#76]
## Summary of Bug
Connection end part is missing chain_id in the relayer configuration

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by Shivani912** [comment]
We don't need this one anymore since we're not validating params against this config, right? @ancazamfir

**Comment by Shivani912** [comment]
> We don't need this one anymore since we're not validating params against this config, right? @ancazamfir

I misunderstood. We don't need it to validate params for queries but the relayer will still need chain ID 🙃
