### ISSUE TITLE
Introduce and try out `rust-stainless`

### ISSUE THREAD

**Issue by yannbolliger** [informalsystems/ibc-rs#760]
[`rust-stainless`](epfl-lara/rust-stainless) is an (experimental) Rust frontend to the Stainless formal verification tool. To see whether it is already fit for "outdoor" use, we need a testbed and some example benchmarks. The IBC handlers seem to fit very well to that.

- [x] Create standalone cargo project
- [x] Try out `rust-stainless` to find bugs and missing features
- [x] Add/fix the features in `rust-stainless`
- [x] Update benchmark to make use of new features
- [ ] Repeat

**Comment by adizere** [comment]
Yann defended his thesis with success! https://youtu.be/rXZgaMIX3-4
