### ISSUE TITLE
Create a 'disclosure' log

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#82]
## Summary

Create a document to record all bugs/issues we uncover while specifying & formally verifying the IBC protocols.

## Problem Definition

This feature addresses the problem of keeping a historical log of contentious matters in the IBC specs. We can share this log with external collaborators and disclose any issue we find in a transparent manner.

It is unclear if a markdown file is the right format to record these matters. Main disadvantage is that this document might be difficult to maintain over time.

## Proposal

- A basic markdown file `docs/disclosure-log.md` will help us keep track and disclose all the problems we find.
- Each entry in this file will consist of a brief description + a commit hash. The hash will usually point to the full details of that problem.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by cwgoes** [comment]
Thanks, this would be helpful. I'm open to any sort of process changes in the specification repository or procedures which you think would make this easier.

**Comment by ebuchman** [comment]
Why not just open issues in cosmos/ics?

**Comment by adizere** [comment]
We are opening issues in the other repo in addition to this disclosure log. The point of the log was to have a single place with the history of all issues we discussed so we can easily report/refer to them.
