### ISSUE TITLE
Hermes management, API specification and implementation (bootstrap)

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#843]
## Crate
relayer

## Summary
Define the architecture for hermes operation management and implement it. Specify the initial APIs and implement a demo sample.

## Problem Definition
Current hermes operation is defined via the configuration file loaded at startup, cannot be changed programmatically or reloaded dynamically.

## Proposal
- [ ] Write a specification for the required APIs, including:
    - query, add, delete chain configuration
    - query, add, delete(or disable) relaying policy elements (e.g. “relay between chains A and B”, “relay on connection X for chain A”, etc.). This is evolving but at minimum specify the ones currently supported.
    - all queries currently supported by the CLIs: keys, clients, connections, channels, packets
    - all operations supported by the CLIs (mainly create/ update client, connections and channels)

- [ ] Decide on a client/ server architecture, be it REST or other, based on the above.
- [ ] Server implementation and the APIs for query, create and update client.

## Acceptance Criteria
Ability to interact with hermes via the agreed APIs and architecture to query, create, update clients.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by andynog** [comment]
I can work with @romac and others to evaluate from the technical side what's the best framework/crate to use for a REST API if we're going with that.
