### ISSUE TITLE
Allow fee/gas to be specified per transaction instead of using the default from config

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#865]
## Crate

ibc-relayer, ibc-relayer-clie

## Summary

Hermes should allow a fee to be specified when submitting a transaction.

## Problem Definition

The problem right now is that we use the same fee (via config) for all transactions. In reality different commands might 'cost' different because of gas used. 

## Proposal

Added a fee (and denom) to the cli commands for txs. Also provide support for that in the future REST API endpoints.

## Acceptance Criteria

All the txs commands have a way to specify the fee

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hermes dynamically computes the fees now, via /tx_simulate endpoint. Closing as outdated.
