### ISSUE TITLE
Relay on all paths

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#867]
## Crate

`relayer`, `relayer-cli`

## Summary

The relayer should relay on all existing paths between the chains in the config, not just the ones defined in the `[connections]` section (which will be removed). To filter out which paths to relay on, a policy language will be introduced at a later stage.

## Problem Definition

This is a hard requirement for the Gravity DEX.

## Proposal

Listen from events from all configured chains and start workers as needed.

## Acceptance Criteria

When the `start-multi` command relays all incoming packets from all the chains in the config.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Covered by #862, #784
