### ISSUE TITLE
sp-std in ibc-rs

### ISSUE THREAD

**Issue by livelybug** [informalsystems/ibc-rs#876]
To make ibc-rs no_std compatible(#29 ), one of the steps is refactoring the rust built-in std , like [this](https://github.com/outmove/nopetgraph/commit/0d5c4c7057bb587f8f5cb5639bbda3a5f760909c#diff-c94dcc50cc46e9c4994422c189906cf46597986c9727b99ad3b6f94f238aaa81L15).

Is it appropriate to use crate sp-std in the refactoring?

**Comment by livelybug** [comment]
@romac As per the meeting, kindly comment if any. Thank you.

**Comment by romac** [comment]
> one of the steps is refactoring the rust built-in std , like this.

I would rather not have to change all imports to `core::` or `alloc::` but instead keep using the `std::` namespace, and re-export everything from `core` and `alloc` under the `std` name.

> Is it appropriate to use crate sp-std in the refactoring?

Can you explain why you would choose `sp-std` over an established crate like [`no-std-compat`](https://docs.rs/crate/no-std-compat/0.4.1) for this purpose? I unfortunately don't have to look very closely at `sp-std` right now, so any information would be very welcome :)

**Comment by livelybug** [comment]
> I would rather not have to change all imports to core:: or alloc:: but instead keep using the std:: namespace, 

Yes, that's the way we are working.

> Can you explain why you would choose sp-std over an established crate like no-std-compat for this purpose?

"sp-std" is verified in substrate, which is actively maintained and the framework we are working on.
"no-std-compat" is not maintained so actively and less dependent on by other crates.
Technically, "sp-std" may be more reliable.
