### ISSUE TITLE
Test scenarios for multi-network IBC

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#897]
## Crate
relayer-cli / scripts

## Summary
Define test scenarios for a set of networks interconnected in a full mesh of IBC paths.

## Problem Definition
To test the stability of relaying we should define a few test scenarios assuming that there are multiple interconnected networks.

This would help the stability goal of the gravity-dex release.

Test scenarios:

1. CI where a chain is restarted and where we assert that hermes can recover after the restart
    - originally proposed here: [@ancazamfir's comment](https://github.com/informalsystems/ibc-rs/issues/1026#issuecomment-852892958)

## Proposal
Let's define test scenarios either in English language or programmatically that we can run against a working network.

## Acceptance Criteria
Test scenarios are documented and any programmatic ones ran against a network at least manually.

Optional goal: CI.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
@soareschen please keep this in mind while working on #797.
(FYI The [`gm`](https://github.com/informalsystems/ibc-rs/tree/master/scripts/gm) tool may prove useful to bootstrap an arbitrary number of Cosmos SDK networks.)

**Comment by adizere** [comment]
Closing as this overlaps with #1572
