### ISSUE TITLE
Add issue/PR template

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#9]
See https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by ancazamfir** [comment]
wanted to ask about this in the planning meeting but we can start making some templates, for feature requests (code and specs), bugs, etc.

**Comment by romac** [comment]
Here's `tendermint-rs`current PR checklist: https://github.com/interchainio/tendermint-rs/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by marbar3778** [comment]
is it defined who will be [code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) of this repo? would be good to include in order to complete this issue

**Comment by ancazamfir** [comment]
> is it defined who will be [code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) of this repo? would be good to include in order to complete this issue

Romain and me for now.
