### ISSUE TITLE
Clean up light client related code 

### ISSUE THREAD

**Issue by milosevic** [informalsystems/ibc-rs#90]
Review the relayers use of the light-client and tendermint and clean up any lose ends. Minimize the code the relayer needs to setup and manage the light-client by adding more functionality to the light-client crate and to ics07 module as necessary. Any light-client specific logic should be handled in the light-client Eg. light-client needs to properly handle initialization (https://github.com/informalsystems/tendermint-rs/issues/484).

**Comment by ebuchman** [comment]
Some cleanup can probably already be done but this also blocks on https://github.com/informalsystems/tendermint-rs/issues/484

**Comment by ebuchman** [comment]
Related to #243 - need to update to tendermint-rs v0.16 and replace all use of the now removed `lite` module
