### ISSUE TITLE
Query clients only returns 100 entries

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#946]
## Crate

imc-relayer-cli, imc-relayer

## Summary of Bug

When query the clients for a chain, only 100 clients are returned in the result

## Version

Branch: Master (v0.3.0)

## Steps to Reproduce

Executing the command `hermes query clients cosmoshub-4` only displays 100 clients. The Cosmos Hub currently has more than 100 clients already (around ~146 clients)

## Acceptance Criteria

Allow all client entries to be returned either adding a pagination logic or increasing the results returned.

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
All the clients are returned but the order confuses the user. This was fixed as part of  #995
