### ISSUE TITLE
Upgrade to SDK v0.43

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#947]
## Crate
all

## Summary
For the upcoming upgrade we need to support gaia `v5.0`. 

## Proposal

- fix the `dev-env` scripts, which currently fails with
    - `Error: unknown flag: --grpc-web.address`
    - this is because gaia temporarily [required allocation](https://github.com/informalsystems/ibc-rs/pull/948/files#diff-9da4a7b76c85035105f66c4f35a8f8ef35633602d4829b0f27b34ce6a33d0230) of an additional port (for a "grpc web" interface) which was removed in the meantime, and now we also have to remove it

- upgrade the protos

> - ibc-go commit: [0d9eef8925fd539bb864126ee84726dbe56f5cbe](https://github.com/cosmos/ibc-go/commit/0d9eef8925fd539bb864126ee84726dbe56f5cbe)
> - sdk commit: [0ab5726a7aa5c2d66916b14becb696e6e19a1efb](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.43.0-rc2)

- make the required changes, check for backwards compatibility
- determine minimum sdk version support and test with chains having different versions
- test thoroughly the modifications to the upgrade CLIs (e.g., [this file](https://github.com/informalsystems/ibc-rs/pull/948/files#diff-aa1f46f9c22ea7597f8d210df7a99501f3625943d55f6ed1c2932c2954055046))

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
Another breaking change is the [removal of the height attribute](https://github.com/cosmos/ibc-go/pull/166/files#diff-b225d8b78960f1ed19ccabcbdcda5ff708075790adac8463fbb0a83a8a63b78aL126) in the MsgSubmitMisbehaviour event

**Comment by ancazamfir** [comment]
> Another breaking change is the [removal of the height attribute](https://github.com/cosmos/ibc-go/pull/166/files#diff-b225d8b78960f1ed19ccabcbdcda5ff708075790adac8463fbb0a83a8a63b78aL126) in the MsgSubmitMisbehaviour event

Thanks! we will make the change soon.  I didn't get to this change yet as testing requires custom images and relayer. As we have not yet finished coding for sending the misbehaviour to the fullnodes, we don't use the event, except for displaying it when in listen mode.
