### ISSUE TITLE
Improve code quality of unreceived-packets or unreceived-acks

### ISSUE THREAD

**Issue by brapse** [informalsystems/ibc-rs#956]
Follow up from: https://github.com/informalsystems/ibc-rs/pull/907

The current factoring on the `unreceived-packets` and `unreceived-acks` CLIs rely on duplicate and code and might not use the best queries to get channel_id. Improve the code quality by providing a standard using a more efficient query route and method for getting the counter party chain id.

**Comment by ancazamfir** [comment]
Thanks! We use `channel_connection_client` (maybe not the best name) that: gets the channel end from `channel_id`, then the connection end from which the `client_id` is obtained, then we query the client state so we get the `chain_id` which is the id of the counterparty chain. I am not aware of a more efficient way. Agreed on the dup code.
