### ISSUE TITLE
Investigate potential re-ordering of events from the websocket

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#964]
## Crate
relayer? rpc lib?

## Summary of Bug
Not sure what happens but noticed that `hermes listen ibc-1` sometimes shows batches with the `NewBlock` event interleaved with other events at same height`. In contrast the Go relayer doesn't show this problem.
While this is not of immediate concern, it would be great to understand where the order is changed and why.

Some logs here

https://gist.github.com/ancazamfir/f66fe219d038c5f71cebb0e14de78448

## Version
`romac/batch-events` (found when reviewing #958 but probably not related)

## Steps to Reproduce
Start both hermes and go relayer in listen mode. Send 2 Tx-es to `ibc-1` using the patched `ft-transfer` that uses `broadcast_tx_commit` (branch `anca/evets_multi_tx`). 
`hermes tx raw ft-transfer ibc-0 ibc-1 transfer channel-0 9999 -o 1000 -n 2`
Repeat a few times until the issues appears.

Logs from the relayers in the gist. The events com with the order 
- `(NewBlock, Tx, Tx) ` for the Go relayer
- `(Tx, NewBlock, Tx) ` for hermes

## Acceptance Criteria

____

## For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Now that we sort the events in each batch to have `NewBlock` first, do we still need to look into this?

**Comment by ancazamfir** [comment]
> Now that we sort the events in each batch to have `NewBlock` first, do we still need to look into this?

Probably not, let's close this
