### ISSUE TITLE
Versioning is not fully consistent with ICS-es

### ISSUE THREAD

**Issue by Shivani912** [informalsystems/ibc-rs#97]
**Problem**
- Cosmos SDK does not allow "*empty*" version strings but ICS-03 and ICS-04 suggest using a default version of `""` if needed.
- A lot of places in code use `Version` string and require some validation on `version` -> `String` and `versions` -> `Vec<String>`. For now, this is handled by two functions which are part of Connection module in code and this is simply to get the work done fast but this needs to be discussed on how we want to do it moving forward.

**Proposed Solution**
- I suggest we adhere to the ICS-es to allow empty version strings and raise an issue about this on the SDK side. 
- I think it will be helpful to have a concrete Version type with its own implementation. I remember @ancazamfir saying this was being discussed and that it's not clear yet.

**Comment by adizere** [comment]
Which ADR-03 and ADR-04 are we talking about exactly? (They're not in this repo, right?)

**Comment by ancazamfir** [comment]
For now let's leave it like it is in SDK code and your PR. I will move this to a later milestone (the relayer delivery one)

**Comment by Shivani912** [comment]
> Which ADR-03 and ADR-04 are we talking about exactly? (They're not in this repo, right?)

My bad @adizere I was talking about the ICSes 03 and 04

**Comment by ancazamfir** [comment]
Final fixes with #388
