### ISSUE TITLE
Align relayer config file with the light client config

### ISSUE THREAD

**Issue by milosevic** [informalsystems/ibc-rs#99]
The relayer config file contains parameters needed to initialise light clients. We should try to align this section of config file with the light client config file format, so ideally we can copy light client config file into relayer config file.

**Comment by adizere** [comment]
This issue is not entirely clear to me. When we say "relayer config file" are we talking about https://github.com/informalsystems/ibc-rs/blob/master/relayer/relay/tests/config/fixtures/relayer_conf_example.toml ?

**Comment by ebuchman** [comment]
Perhaps we include the light client config context directly in the relayer config file. I think this is how the Go does it.

Bumping the milestone since they may depend on Abscissa changes.

**Comment by ancazamfir** [comment]
Closed via #348
