### ISSUE TITLE
Hermes client update fails if client was recently created

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#997]
## Crate

`ibc-relayer` mostly

## Summary of Bug

Running `hermes create client` and immediately updating that client with `hermes update client` will fail.

```
./target/debug/hermes create client ibc-1 ibc-0 ; ./target/debug/hermes update client ibc-1 07-tendermint-6
May 26 18:46:52.144  INFO ibc_relayer_cli::commands: using default configuration from '/Users/adi/.hermes/config.toml'
Success: CreateClient(
    CreateClient(
        Attributes {
            height: Height {
                revision: 1,
                height: 6605,
            },
            client_id: ClientId(
                "07-tendermint-6",
            ),
            client_type: Tendermint,
            consensus_height: Height {
                revision: 0,
                height: 6652,
            },
        },
    ),
)
May 26 18:46:54.264  INFO ibc_relayer_cli::commands: using default configuration from '/Users/adi/.hermes/config.toml'
Error: tx error: error raised while updating client: chain ibc-1 is missing trusted state smaller than target height 0-6652
```

## Version

041ef642f7080e1faea60fc1325abde5afcf5c0a

## Steps to Reproduce

Compile hermes, then make sure you know the counter for the client that will be created (in this case, it's `07-tendermint-6`) and run:

```
./target/debug/hermes create client ibc-1 ibc-0 ; ./target/debug/hermes update client ibc-1 07-tendermint-6
```

## Acceptance Criteria

- ~~an appropriate error should be returned if the client cannot be updated; or if the update should succeed, then the bug should be fixed~~
- ~~after a closer look, it seems that the semantics of the CLI should be as follows: after running `hermes update client X`, client `X` should have the latest header installed; these semantics are already fulfilled by the current implementation of update client, yet the method returns `error`, so the correct return value from the method should be `success`~~
- update: make the `update client` CLI call blocking until the chain advances sufficiently so that method can effectively submit a newer consensus state to the target client
- also fix: "this probably silently fails sometime in our CI as we retry in `cmd.py`" -- comment by @ancazamfir

____

## For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
I am wondering now why we want to fix this? We know this "issue" is seen when runing the `e2e/run.py` but the script should recover as it has a retry mechanism built in. For the relayer (both passive, i.e. `hermes start` and active, e.g. `hermes create channel..`) this should also be already dealt with via retries. 
I think we should take a step back and give a good justification why this is something that needs fixing.

**Comment by ancazamfir** [comment]
I am wondering now why we want to fix this? We know this "issue" is seen when runing the e2e/run.py but the script should recover as it has a retry mechanism built in. For the relayer (both passive, i.e. hermes start and active, e.g. hermes create channel..) this should also be already dealt with via retries.
I think we should take a step back and give a good justification why this is something that needs fixing.

**Comment by adizere** [comment]
> I am wondering now why we want to fix this? We know this "issue" is seen when runing the e2e/run.py but the script should recover as it has a retry mechanism built in. For the relayer (both passive, i.e. hermes start and active, e.g. hermes create channel..) this should also be already dealt with via retries.
> I think we should take a step back and give a good justification why this is something that needs fixing.

The basic justification why we'd like to fix this is, in my opinion: to be more clear about the semantics of the `update` operation.

We can choose between two flavors of semantics:

Semantics version A:
> After running `hermes update client X -h Y`, client X should have header Y (or the latest header if -h is omitted) installed. Under these semantics, the correct return value should be success (but currently Hermes returns error).

Version A of the semantics is described in the acceptance criteria above.

Semantics version B:

> Upon running `hermes update client X -h Y`, Hermes will submit to the chain hosting client X a transaction to update client X with header Y (or latest header if option -h is omitted). Under these semantics, if client X already has header Y installed, Hermes should return an error (because Hermes will not resubmit a transaction in the case when header Y, or latest is already installed) so the operation effectively fails.

Version B of the semantics is described in [ADR 006](https://github.com/informalsystems/ibc-rs/blob/master/docs/architecture/adr-006-hermes-v0.2-usecases.md#create--update-a-client).

Other semantics probably exist. Among these two, version A is less ambiguous (more sound).

Once we decide on a version of semantics, we can probably adopt the same pattern for other operations as well. For instance, if we choose A, then the semantics of `hermes tx raw conn-try ibc-1 ibc-0 07-tendermint-1 07-tendermint-0 -s connection-0` would be "after running the command, `connection-0` on chain `ibc-1` should be in tryopen state", and if the connection is _already_ in that state, then Hermes should return success.

**Comment by soareschen** [comment]
The difference between the update-client semantics and other semantics like conn-try is that the target height is usually not under the user's control, or of the user's interest. The user do not really care about the current height of the chain, and the notion of time is fuzzy anyway. The main issue lies in that the post-condition of create-client do not always match the pre-condition of update-client, and instead introduce a time sensitive step in between that the caller must wait for the height of the chain to increment before the pre-condition of update-client is satisfied. On the other hand, operations like conn-try will result in post-condition that never change, so the user can have high confidence that the pre-condition of the next step is always satisfied, assuming there is no race condition with other relayers.

**Comment by adizere** [comment]
Closing as outdated.
