### ISSUE TITLE
Hermes feature: New query channel client CLI

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#999]
## Crate
relayer-cli

## Summary
Add following query to check the channel's client state:
`hermes query channel client <chain> <port-id> <channel-id`

## Acceptance Criteria

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by adizere** [comment]
For context: This was originally a requirement from Gravity Dex, but it seems no longer required by them. Adding it to backlog.
